### ISSUE TITLE
Quantized inference performance

### ISSUE THREAD

**Issue by shanumantesc** [google/XNNPACK#1022]
Have you compared quantized (unsigned 8-bit) inference with QNNPACK? Given that this library was forked off of QNNPACK, are there any optimizations in XNNPACK on top which could make it faster for quantized inference (maybe for some particular layers)?

**Comment by Maratyszcza** [comment]
Unsigned quantized inference is less efficient than QNNPACK. Compared to QNNPACK, it has some optimizations removed.
The focus of quantized inference in XNNPACK is on signed quantization format.

**Comment by shanumantesc** [comment]
@Maratyszcza As a follow-up, are there benchmarks comparing signed quantized inference from XNNPACK with QNNPACK? There seem to be certain benefits to using signed arithmetic based on https://www.tensorflow.org/lite/performance/quantization_spec

**Comment by Maratyszcza** [comment]
We don't have any data to share, but you may run `end_to_end_bench` from XNNPACK on your device. Look at cases starting with `QS8`.
