### ISSUE TITLE
about _cvtu32_mask16 is missing on macOS10.13.6 + xcode 10.1

### ISSUE THREAD

**Issue by llv22** [google/XNNPACK#1081]
Dear colleagues:

I tried with building pytorch on macOS10.13.6 + xcode 10.1. And one show-blocker during this process is that  
XNNPACK is missing with symbol   "__cvtu32_mask16".

I double-checked with clang version, which is 10 not 11. so when compiler linked object to executable file, it can't find "__cvtu32_mask16" in clang.

Also refer to discussion in https://discuss.pytorch.org/t/pytorch-build-almost-succeeds-but-fails-undefined-symbols-for-architecture-x86-64-cvtu32-mask16/73000.

My question is:
if we try to make building working on macOS10.13.6 + xcode 10.1, can we have some tweaks to solve such issue? I means  to **tell compiler use __cvtu32_mask16 defined within XNNPACK instead of clang library**, where such function does not exist.

any hints?
https://github.com/google/XNNPACK/blob/master/src/xnnpack/intrinsics-polyfill.h#L36

**Comment by Maratyszcza** [comment]
`src/xnnpack/intrinsics-polyfill.h` provides a polyfill for `_cvtu32_mask16` function for all compilers, but it seems that our version detection macros are incorrect. Please adjust and submit a PR.

**Comment by llv22** [comment]
@Maratyszcza I thought for pytorch compilation, it is only necessary to add 

1, in src/xnnpack/intrinsics-polyfill.h
```c
static inline __attribute__((__always_inline__, __artificial__))
__mmask64 _kshiftli_mask64(__mmask64 a, unsigned int count) {
  return (__mmask64) ((unsigned long long) a << count);
}

static inline __attribute__((__always_inline__, __artificial__))
__mmask64 _kshiftri_mask64(__mmask64 a, unsigned int count) {
  return (__mmask64) ((unsigned long long) a >> count);
}
```
2, in src/qs8-gemm/MRx16c8-avx512skx.c.in
```c
//for adding missing symbol inside library
#include <xnnpack/intrinsics-polyfill.h>
```
the root cause is when use template of MRx16c8-avx512skx.c.in to generate code for NN of avx512, it miss to link with _kshiftli_mask64, _kshiftri_mask64 and _cvtu32_mask16

but I'm not sure if that is all of the picture, are other codegen template also have the same issue or not?

**Comment by Maratyszcza** [comment]
1. Was recently added in b9deb96933d8398aed5ba71aa088a190757e4aab and e5b5deabd5b111f4f35933becc62d5690f8aadd8
2. Is already there

**Comment by Maratyszcza** [comment]
It is possible that other templates have the same issue. If you discover it, please let me know.

**Comment by llv22** [comment]
@Maratyszcza OK, haven't checked your update, as this week a little busy for work. 
sure, if found, I will @ you ^-^
thanks for quick confirmation
