### ISSUE TITLE
SPMM slower with higher sparsity rate.

### ISSUE THREAD

**Issue by tlzhao-casia** [google/XNNPACK#1133]
I read the excellent paper 'Fast Sparse Convolutions'  in CVPR2020 and I'm very interested in it. However, when I run the SPMM benchmark implemented in XNNPACK, it seems that in some cases it is even slower with higher sparsity. My codes are as follows:
```cpp
pthreadpool_t threadpool = pthreadpool_create(1);
  status = xnn_initialize(NULL);
  fprintf(stderr, "mr = %d, nr = %d\n", xnn_params.f32.spmm.mr, xnn_params.f32.spmm.nr);
  xnn_operator_t spmm_op;
  status = xnn_create_convolution2d_nchw_f32(
    // padding
    0, 0, 0, 0,
    // kernel size
    1, 1,
    // stride
    1, 1,
    // dilation
    1, 1,
    // groups
    1,
    // input/output channels per group
    K, N,
    // input/output channel stride
    K, N,
    // kernel, bias     
    weight, bias,
    // min/max value of output
    0, FLT_MAX,
    // input tensor stored in NCHW order
    0,
    &spmm_op
  );
  status = xnn_setup_convolution2d_nchw_f32(
    spmm_op,
    1,
    1, M,
    input, output,
    threadpool
  );
```
According to the implementation of xnn_convlution2d_nchw_f32 in XNNPACK/src/operators/convolution_nchw.c, it will run the convolution with SPMM when the kernel size/stride/dilation are all 1, and input/output tensors are stored in NCHW layout. I run the operator with M = 49[spatial dimension of fmap], N = 512[output channels], K = 1024[input channels] under different weight sparsity, results are shown as follows:
sparsity   |   time (ms)
0.0               12.60
0.1               12.64
0.2               25.52
0.3               22.94
0.4               19.84
0.5               16.77
0.6               13.36
0.7               9.76
0.8               5.80
0.9               2.06

**Comment by Maratyszcza** [comment]
Have you tried to run `f32-spmm-bench` from XNNPACK itself?
