### ISSUE TITLE
Is there any plan to support lstm operation?

### ISSUE THREAD

**Issue by vonchenplus** [google/XNNPACK#1182]
Hi,

I created a model using [lstm](https://www.tensorflow.org/api_docs/python/tf/keras/layers/LSTM) operations. 

I used performance tools and used xnnpack delegate, and found that the lstm operation is not supported by xnnpack delegate. Are there any plans to support this operation?

Thanks.

**Comment by Maratyszcza** [comment]
We plan to eventually support all TFLite operators, but don't have an ETA for LSTM availability.
