### ISSUE TITLE
Is there any plan to support HalfPixelCenters for resize_bilinear_nhwc?

### ISSUE THREAD

**Issue by lina128** [google/XNNPACK#1184]
TF recently added support for HalfPixelCenters for resize_bilinear op: https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/resize-bilinear

Is there any plan to add this attr too in XNNPack?

**Comment by Maratyszcza** [comment]
It is already supported: https://github.com/tensorflow/tensorflow/blob/06fb72020d3af8c2b27fd4f80993ff3f6b110d36/tensorflow/lite/delegates/xnnpack/xnnpack_delegate.cc#L2602-L2607

**Comment by lina128** [comment]
This is great, thank you for the quick response, Marat!
