### ISSUE TITLE
Enabling XNNPACK in TFLite for ARM64?

### ISSUE THREAD

**Issue by Montana** [google/XNNPACK#1215]
Hey my fellow developers, 

Was peaking around the build instructions,  and upon inspecting the bash script `download_dependencies.sh` nothing shows XNNPACK being downloaded from anywhere. 

I wasn't sure if this is a TensorFlow issue or post this issue directly to XNNPACK. 

Thank you for any support I can get.

-Montana

**Comment by Maratyszcza** [comment]
Please direct this question to TensorFlow repository.
