### ISSUE TITLE
Unable to build the tflite & xnnpack from CMakeLists.txt

### ISSUE THREAD

**Issue by dhirajnitk** [google/XNNPACK#1260]
The CmakeLists doesn't support emscripten.  I am building the tflite with emscripten. I am able to build all the required static libraries of libtensorflowlite. I need a delegate to launch the interpreter. But emscripten build also have source code dependencies on xnnpack_delegates.h/cc [](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/xnnpack/xnnpack_delegate.cc).
So can you please guide me on how to build xnnpack and xnnpack_delegate.cc  so that i could register the xnnpack as delegate using low level delegate api(or any other means) listed in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/delegates/xnnpack

**Comment by Maratyszcza** [comment]
This is expected. CMake build for Emscripten is currently not supported, you need to use Bazel for WebAssembly and WebAssembly SIMD targets.

**Comment by dhirajnitk** [comment]
I am building the tflite with emscripten. I am able to build all the required static libraries of libtensorflowlite. I need a delegate to launch the interpreter. But emscripten build also have source code dependencies on xnnpack_delegates.h/cc .
So can you please guide me on how to build xnnpack and xnnpack_delegate.cc so that i could register the xnnpack as delegate using low level delegate api(or any other means) listed in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/delegates/xnnpack


I want to build  these files 
```
if(TFLITE_ENABLE_XNNPACK)
  find_package(xnnpack REQUIRED)
  populate_tflite_source_vars("delegates/xnnpack"
    TFLITE_DELEGATES_XNNPACK_SRCS
    FILTER ".*(_test|_tester)\\.(cc|h)"
  )
  list(APPEND TFLITE_TARGET_DEPENDENCIES
    XNNPACK
  )
  list(APPEND TFLITE_TARGET_PUBLIC_OPTIONS "-DTFLITE_BUILD_WITH_XNNPACK_DELEGATE")
endif()
```
If I use  bazel for xxnpack then should I be able to get libxnnpack.a(I dont want js/wasm)
Then I would need to link xnnpack_delegate.o with libxnnpack.a .

**Comment by dhirajnitk** [comment]
I m forcing the xnnpack_delegate.cc commenting on find_package(xnnpack)
its failing on "fp16.h' file not found". I see that this is half float library. Is this supported like numpy(not at cpu/compiler level)
If I am able to build xnnpack_delegate.o then I can use emcc to link it with libxnnpack.a(from bazel) ??

**Comment by dhirajnitk** [comment]
How I can build the bazel for webassembly or WebAssembly  simd. The config is not defined in .rc file. 
`bazel build -c opt --config emscripten_wasm : wasm_ukernels`

**Comment by Maratyszcza** [comment]
Bazel doesn't support building for WebAssembly out of the box. You'd need a custom toolchain specifications to enable this use case. You may the [Bazel toolchain specification from TensorFlow.js](https://github.com/tensorflow/tfjs/tree/master/tfjs-backend-wasm/toolchain) which was tested to work with XNNPACK.

**Comment by Kasthooriraja** [comment]
@dhirajnitk have you resolved the issue?
I want to build libxnnpack.a using emscripten, so that I can link this with libtensorflowlite.a
could you please post the procedure here?
