### ISSUE TITLE
output and input address change dynamically in operators

### ISSUE THREAD

**Issue by pablogh-2000** [google/XNNPACK#1268]
Dear all,

we are evaluating the use of  XNNPACK for our own development. I have seen that the `input` and `output` vectors are set in the `*_setup_*` method that construct the operator.

I wonder if it possible to extend the API to set the output and input address after the `***_setup*** `has been called?
We are happy to develop the change ourselves, but wanted to be sure if this is all together possible?

Thanks,

Pablo.

**Comment by Maratyszcza** [comment]
You can call `xnn_setup_` multiple times. Just call it every time the address of `input`/`output` buffers change.

**Comment by pablogh-2000** [comment]
Hi @Maratyszcza 
massive thanks! That helps a lot.

Regards,
Pablo.
