### ISSUE TITLE
question about notation of micro kernel's arguments

### ISSUE THREAD

**Issue by chunseoklee** [google/XNNPACK#1288]
I have look into micro kernel implementation for personal study. 

Due to the lack of documentation, I am little confused about notation.

For example, `xnn_qu8_gemm_ukernel_function` benchmark in https://github.com/google/XNNPACK/blob/15c0036c46c1ebe91f4fcdbc44503aeb4246a973/bench/qu8-gemm.cc#L36-L39

takes mr, nr, kr as arguments. 

My question is which is the dimension for fully-connected operation's kernel(weight) ? I think `nr*kr` is the size of FC's kernel and `mr*kr` is the size of FC's input. Please let me know if this is incorrect. 

Thank you.

**Comment by Maratyszcza** [comment]
`mr*nr` are the dimensions of the output tile produced in one invocation of the inner loop of GEMM/IGEMM microkernel call. `kr` and `sr` are internal weight packing parameters.

I suggest you read [this classical paper of matrix-matrix multiplication](https://www.cs.utexas.edu/~flame/pubs/GotoTOMS_revision.pdf) to better understand how the GEMM microkernels are organized.
