### ISSUE TITLE
'vdotq_lane_s32' is invalid in C99 [-Wimplicit-function-declaration]

### ISSUE THREAD

**Issue by Chinneil** [google/XNNPACK#1359]
[ 10%] Building C object _deps/xnnpack-build/CMakeFiles/XNNPACK.dir/src/qs8-igemm/gen/6x8c4-minmax-neondot.c.o
/home/chendongmin/project/tensorflow_lite_cmake/dtln_aec_android_build/xnnpack/src/qs8-gemm/gen/1x16c4-minmax-neondot.c:64:20: warning: implicit declaration of function
      'vdotq_lane_s32' is invalid in C99 [-Wimplicit-function-declaration]
      vacc0x0123 = vdotq_lane_s32(vacc0x0123, vb0123x0123, va0x01234567, 0);
                   ^
/home/chendongmin/project/tensorflow_lite_cmake/dtln_aec_android_build/xnnpack/src/qs8-gemm/gen/1x16c4-minmax-neondot.c:64:18: error: assigning to 'int32x4_t'
      (vector of 4 'int32_t' values) from incompatible type 'int'
      vacc0x0123 = vdotq_lane_s32(vacc0x0123, vb0123x0123, va0x01234567, 0);
                 ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/chendongmin/project/tensorflow_lite_cmake/dtln_aec_android_build/xnnpack/src/qs8-gemm/gen/1x16c4-minmax-neondot.c:65:18: error: assigning to 'int32x4_t'
      (vector of 4 'int32_t' values) from incompatible type 'int'
      vacc0x4567 = vdotq_lane_s32(vacc0x4567, vb0123x4567, va0x01234567, 0);
                 ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Chinneil** [comment]
git clone xxx.git
mkdir build
cd build 
cmake -DCMAKE_TOOLCHAIN_FILE=/home/chendongmin/project/ndk/android-ndk-r18b/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a ../tensorflow/lite
cmake --build . -j

**Comment by Maratyszcza** [comment]
You need a newer Android NDK. Clang in NDK r18b doesn't support the intrinsic functions used in some XNNPACK microkernels.

**Comment by mhsmith** [comment]
When building PyTorch version 1.8.1 with NDK r18, I hit this issue on both the armeabi-v8a and arm64-v8a ABIs. The x86 and x86_64 ABIs were OK.

It looks like NDK r19c supports the needed functions, but I wasn't able to use that to build PyTorch either because of a compiler crash on all ABIs:

```
  1.    <eof> parser at end of file
  2.    Per-file LLVM IR generation
  3.    aten/src/ATen/native/cpu/UnaryOpsKernel.cpp.DEFAULT.cpp:306:3 <Spelling=aten/src/ATen/native/cpu/UnaryOpsKernel.cpp.DEFAULT.cpp:309:9>: Generating code for declaration 'at::native::(anonymous namespace)::sinc_kernel(at::TensorIterator &)::(anonymous class)::operator()()::(anonymous class)::operator()()::(anonymous class)::operator()'
  4.    aten/src/ATen/native/cpu/UnaryOpsKernel.cpp.DEFAULT.cpp:306:3 <Spelling=aten/src/ATen/native/cpu/UnaryOpsKernel.cpp.DEFAULT.cpp:312:18>: LLVM IR generation of compound statement ('{}')
  #0 0x000000000234c8c6 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/home/smith/git/chaquo/python/target/toolchains/armeabi-v7a/bin/clang80+++0x234c8c6)
  #1 0x000000000234b4d0 llvm::sys::RunSignalHandlers() (/home/smith/git/chaquo/python/target/toolchains/armeabi-v7a/bin/clang80+++0x234b4d0)
  #2 0x000000000234cbaa (/home/smith/git/chaquo/python/target/toolchains/armeabi-v7a/bin/clang80+++0x234cbaa)
  #3 0x00007f3f2c4ee0c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x110c0)
  #4 0x0000000003638bb1 clang::VarDecl::isThisDeclarationADefinition(clang::ASTContext&) const (/home/smith/git/chaquo/python/target/toolchains/armeabi-v7a/bin/clang80+++0x3638bb1)
  #5 0x0000000003638f8b clang::VarDecl::getDefinition(clang::ASTContext&) (/home/smith/git/chaquo/python/target/toolchains/armeabi-v7a/bin/clang80+++0x3638f8b)
  #6 0x00000000036396d1 clang::VarDecl::getTemplateInstantiationPattern() const (/home/smith/git/chaquo/python/target/toolchains/armeabi-v7a/bin/clang80+++0x36396d1)
  #7 0x00000000025de075 (/home/smith/git/chaquo/python/target/toolchains/armeabi-v7a/bin/clang80+++0x25de075)
  #8 0x00000000025de082 (/home/smith/git/chaquo/python/target/toolchains/armeabi-v7a/bin/clang80+++0x25de082)
  [repeats]
  #255 0x00000000025de082 (/home/smith/git/chaquo/python/target/toolchains/armeabi-v7a/bin/clang80+++0x25de082)
  clang80++: error: unable to execute command: Segmentation fault
```

I then tried NDK r21e, which worked fine.
