### ISSUE TITLE
Compilation error for RPI 4

### ISSUE THREAD

**Issue by pablogh-2000** [google/XNNPACK#1360]
Hi all,

Just got this error compiling in raspberry pi 4 and AmazonEC2 ARM64:

```
./XNNPACK/src/qs8-gemm/2x8c16-aarch64-neon-mlal-padal.S: Assembler messages:
./XNNPACK/src/qs8-gemm/2x8c16-aarch64-neon-mlal-padal.S:51: Error: operand mismatch -- `mov v17.4s,v16.4s'

```

could you please let me know if I am doing something wrong or is it an actual compilation error in the repo?

Thanks,

Pablo.

**Comment by Maratyszcza** [comment]
This is a bug in XNNPACK. The line should be `mov v17.16b, v16.16b`
