### ISSUE TITLE
Does XNNPACK support SeparableConv2D?

### ISSUE THREAD

**Issue by venkatou** [google/XNNPACK#1368]
Hi,
I have a model that uses SeparableConv2D layers extensively. The results from model with XNNPACK is very different than without XNNPACK i.e. unable to reproduce the original results with XNNPACK. Does XNNPACK support SeparableConv2D?

**Comment by Maratyszcza** [comment]
Separable convolution is a combination of pixelwise convolution (convolution with 1x1 kernel) and depthwise convolution. XNNPACK supports both.

**Comment by Maratyszcza** [comment]
Could you post a sample TFLite model that produce wrong results?

**Comment by venkatou** [comment]
Thanks for the response. I think I found the issue. I was using `ReleaseNonPersistentMemory()` and `AllocateTensors()` in every loop due to memory limitations. I removed `ReleaseNonPersistentMemory()` and allocated tensors once at the beginning, the results agreed between the two runs. Not sure if this is a bug or a limitation.

**Comment by Maratyszcza** [comment]
XNNPACK does its own memory allocation (also, typically is consumes less memory than the default TFLite kernels).
