### ISSUE TITLE
Issue with multithread on Windows/mingw64

### ISSUE THREAD

**Issue by venkatou** [google/XNNPACK#1400]
Hi, I cross-compiled TFLite (v2.4.1 and pre-release 2.5.0) with XNNPACK for Windows using Mingw-w64 cmake. On a single thread, the model inference works as expected. When choosing more than 1 thread (example: 2 or 4), the program quits during `Invoke()` unexpectedly (no errors printed).

I used the following command to set number of threads: `InterpreterBuilder (*model, resolver)(&interpreter, num_threads)`

A direct compile for Linux works fine when `num_threads` is greater than 1. Inference, as expected, is faster on 2 threads than 1.

When using default TFLite kernels on Windows (cross compiled as well), the model works fine for any number of threads (Threads set via `SetNumThreads(num_threads)`).

Am I missing any configuration steps when trying to cross-compile? Any assistance is appreciated. Thank you.

**Comment by Maratyszcza** [comment]
This configuration is expected to work out of the box, but I can't diagnose the issue without additional information. Please try to build & run a debug build, or use a debugger to find why the program quits.

**Comment by venkatou** [comment]
Hey Marat, thanks for your response. I went ahead, built a debug build and ran my program in debugger. It's hitting a seg. fault. Output is below:

`(gdb)`
`Thread 5 received signal SIGSEGV, Segmentation fault.`
`[Switching to Thread 3316.0x2958]`
`xnn_f32_maxpool_minmax_ukernel_9p8x__sse_c4 (output_pixels=128, kernel_elements=4, channels=64, input=0x2917ff60,
    input_offset=0, output=0x125f2040, input_increment=4294967276, output_increment=0, params=0xfe0e890)
    at /home/nc/tflite_debug_build/xnnpack/src/f32-maxpool/9p8x-minmax-sse-c4.c:28
28      /home/nc/tflite_debug_build/xnnpack/src/f32-maxpool/9p8x-minmax-sse-c4.c: No such file or directory.`
`(gdb)`

`Thread 5 received signal SIGSEGV, Segmentation fault.`
`xnn_f32_maxpool_minmax_ukernel_9p8x__sse_c4 (output_pixels=128, kernel_elements=4, channels=64, input=0x2917ff60,
    input_offset=0, output=0x125f2040, input_increment=4294967276, output_increment=0, params=0xfe0e890)
    at /home/nc/tflite_debug_build/xnnpack/src/f32-maxpool/9p8x-minmax-sse-c4.c:28
28      in /home/nc/tflite_debug_build/xnnpack/src/f32-maxpool/9p8x-minmax-sse-c4.c`
`(gdb)`

Looks like line 28 (`const __m128 voutput_max = _mm_load_ps(params->sse.max)`) is causing it. The missing file error is probably because I am running it on a different machine (Windows) than the one it was compiled on (Linux). Not sure if `sse.max` is the source of the trouble.

On a separate note, I forgot to mention this in my original message. I also had to add the following definition to ./tflite_debug_build/cpuinfo-source/src/x86/windows/init.c:
`static inline uint32_t max(uint32_t a, uint32_t b) { return a > b ? a : b; }`
as I was getting undefined reference to `max` error during compile time of my program (not during tflite_build).

Appreciate your help and time.

**Comment by Maratyszcza** [comment]
I don't see anything that would have explained the crash, all code paths you're hitting are neither MinGW-specific, nor multithreading-specific. Could you rebuild with Address Sanitizer and re-run the test again?

**Comment by venkatou** [comment]
@Maratyszcza I think I finally tracked down the issue. My cross-compiler was not picking up `ifdef _WIN32` correctly (not exactly sure why) and that resulted in several incorrect `#include` and other things. I am honestly surprised that it even compiled and worked on a single thread in the first place. After sorting that up and recompiling the code, multithreading runs work as expected. Appreciate your pointers in helping me get to the bottom of this.
