### ISSUE TITLE
Does iPhoneOS armv7 support neon dot and neon v8?

### ISSUE THREAD

**Issue by larryliu0820** [google/XNNPACK#1402]
In CMakeLists.txt we have:
```
IF(CMAKE_SYSTEM_PROCESSOR MATCHES "^armv[5-8]" OR IOS_ARCH MATCHES "^armv7")
...
  SET_PROPERTY(SOURCE ${XNNPACK_NEONV8_MICROKERNEL_SRCS} APPEND_STRING PROPERTY COMPILE_FLAGS " -march=armv8-a -mfpu=neon-fp-armv8 ")
  SET_PROPERTY(SOURCE ${XNNPACK_NEONDOT_MICROKERNEL_SRCS} APPEND_STRING PROPERTY COMPILE_FLAGS " -march=armv8.2-a+dotprod -mfpu=neon-fp-armv8 ")
...
ENDIF()
```
In pytorch we are not able to build this on iphoneos armv7 because in arm_neon.h (clang 10.0.0) it fails these checks:
```
#if __ARM_ARCH >= 8 && defined(__ARM_FEATURE_DIRECTED_ROUNDING)
...
#if defined(__ARM_FEATURE_DOTPROD)
```
Is it possible for us to not include neon_dot and neon_v8 for iphoneos armv7? Or can we have a macro to exclude those two features?

**Comment by Maratyszcza** [comment]
I imagine the `neon_dot` build error is the same as tensorflow/tensorflow#48464, but what is failing in `neon_v8` microkernels? It is plausible that Apple toolchain for ARMv7 doesn't support `neon_dot` because the only Apple SoCs that support it are ARM64-only, but IMO `neon_v8` should still compile fine, at there are AArch32-compatible Apple SoCs with ARMv8.

**Comment by Maratyszcza** [comment]
Currently, there is no way to exclude `neon_dot` and `neon_v8` microkernels from the build. I'm looking into a possible solution.

**Comment by larryliu0820** [comment]
Are armv8 SoCs passing CMakeLists.txt check: `IOS_ARCH MATCHES "^armv7"` ?

**Comment by Maratyszcza** [comment]
I'd expect so. `"armv7"` really means AArch32 with ARMv7 or higher instruction set.

**Comment by larryliu0820** [comment]
> "armv7" really means AArch32 with ARMv7 or higher instruction set.

Somehow armv7 is passing this check
```
if (cpuinfo_has_arm_neon_v8())
```
in init.c, but eventually it fails arm_neon.h:
```
#if __ARM_ARCH >= 8 && defined(__ARM_FEATURE_DIRECTED_ROUNDING)
```

> I imagine the neon_dot build error is the same as tensorflow/tensorflow#48464

The error signature looks similar. I've got:
```
xplat/third-party/XNNPACK/XNNPACK/src/qs8-gemm/gen/4x16c4-minmax-neondot.c:102:18: error: assigning to 'int32x4_t' (vector of 4 'int32_t' values) from incompatible type 'int'
      vacc0x0123 = vdotq_lane_s32(vacc0x0123, vb0123x0123, va0x01234567, 0);
                 ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Maratyszcza** [comment]
> hence a lot of `vrndz` `vrndu` symbols are not found

Do you actually get compilation errors about these symbols? XNNPACK sets `" -march=armv8-a -mfpu=neon-fp-armv8 "` when compiling ARMv8 NEON microkernels, which should make Clang include the declarations of these intrinsics.

**Comment by larryliu0820** [comment]
Yes the compiler errors looks like this:
```
XNNPACK/src/f32-vrnd/gen/vrndu-neonv8-x4.c:31:23: error: initializing 'const float32x4_t' (vector of 4 'float32_t' values) with an expression of incompatible type 'int'
    const float32x4_t vy0123 = vrndpq_f32(vx0123);
                      ^        ~~~~~~~~~~~~~~~~~~
```
I've made sure the compiler flags are there.

**Comment by Maratyszcza** [comment]
The fix for NEONDOT microkernels is in #1404

**Comment by Maratyszcza** [comment]
@larryliu0820 Bazel build use `" -mcpu=cyclone -mtune=generic "` (https://github.com/google/XNNPACK/blob/6e8c0ce93ccabd084852c2b3c3bd1658956f7c45/BUILD.bazel#L3971-L3974) for NEONV8 microkernels. Could you try these options with CMake?

**Comment by larryliu0820** [comment]
For neondot I ran into these errors after pulling latest commit:
```
stderr: Undefined symbols for architecture armv7:
  "_xnn_qs8_igemm_minmax_ukernel_4x8c4__neondot", referenced from:
      _init in libXNNPACKApple-2065260873.a(init.c.o)
  "_xnn_qs8_igemm_minmax_ukernel_1x8c4__neondot", referenced from:
      _init in libXNNPACKApple-2065260873.a(init.c.o)
  "_xnn_qs8_gemm_minmax_ukernel_1x8c4__neondot", referenced from:
      _init in libXNNPACKApple-2065260873.a(init.c.o)
  "_xnn_qs8_gemm_minmax_ukernel_4x8c4__neondot", referenced from:
      _init in libXNNPACKApple-2065260873.a(init.c.o)
```
I'm going to see if I can build with cmake

**Comment by larryliu0820** [comment]
Good news is 
```
 apple_aarch32_copts = [ 
     "-mcpu=cyclone", 
     "-mtune=generic", 
 ],
```
Fixes issue for neonv8 microkernels.

**Comment by Maratyszcza** [comment]
> Good news is
> 
> ```
>  apple_aarch32_copts = [ 
>      "-mcpu=cyclone", 
>      "-mtune=generic", 
>  ],
> ```
> 
> Fixes issue for neonv8 microkernels.

Would you create a PR?

**Comment by Maratyszcza** [comment]
> For neondot I ran into these errors after pulling latest commit:
> 
> ```
> stderr: Undefined symbols for architecture armv7:
>   "_xnn_qs8_igemm_minmax_ukernel_4x8c4__neondot", referenced from:
>       _init in libXNNPACKApple-2065260873.a(init.c.o)
>   "_xnn_qs8_igemm_minmax_ukernel_1x8c4__neondot", referenced from:
>       _init in libXNNPACKApple-2065260873.a(init.c.o)
>   "_xnn_qs8_gemm_minmax_ukernel_1x8c4__neondot", referenced from:
>       _init in libXNNPACKApple-2065260873.a(init.c.o)
>   "_xnn_qs8_gemm_minmax_ukernel_4x8c4__neondot", referenced from:
>       _init in libXNNPACKApple-2065260873.a(init.c.o)
> ```
> 
> I'm going to see if I can build with cmake

Fix coming in #1405 1405

**Comment by larryliu0820** [comment]
> if (!XNN_PLATFORM_IOS && cpuinfo_has_arm_neon_dot()) {

Wouldn't that disable iphoneos arm64?

**Comment by Maratyszcza** [comment]
No, this code is in AArch32-specific section
