### ISSUE TITLE
 Is there any plan to support sparse int8/uint8? 

### ISSUE THREAD

**Issue by qingqing01** [google/XNNPACK#1419]
[The work spase computing for 1x1 conv](https://github.com/google-research/google-research/tree/master/fastconvnets) is  great, it seems now only support fp32.spmm in https://github.com/google/XNNPACK/blob/master/src/operators/convolution-nchw.c .

And how use sparse fp16? And do you have plan to support sparse int8/uint8?

Thanks!

**Comment by Maratyszcza** [comment]
We have a long-term goal to support sparse int8-quantized inference, but nothing concrete so far.

**Comment by qingqing01** [comment]
@Maratyszcza Thanks!  How do think the speed between sparse fp16 and sparse int8?

**Comment by Maratyszcza** [comment]
I expect sparse FP16 to be faster than sparse int8, because sparse int8 doesn't benefit from NEON DOT instructions (unlike dense int8).
