### ISSUE TITLE
Performance comparison with ARM Compute Library

### ISSUE THREAD

**Issue by wjc404** [google/XNNPACK#1435]
@Maratyszcza I see some perf data with MobileNet in README. Is there any data about the speed of ARM Compute Library (or ARM NN) in those tasks available? Thanks.

**Comment by Maratyszcza** [comment]
XNNPACK includes [convolution benchmarks that compare to ARM Compute Library](https://github.com/google/XNNPACK/blob/master/bench/convolution.cc#L728-L1051), but they are not enabled in the open-source build, and we don't provide any measurements for these benchmarks.
