### ISSUE TITLE
Compilation in Ubuntu 16.04 for ARM64

### ISSUE THREAD

**Issue by pablogh-2000** [google/XNNPACK#1463]
Hi,

I am getting the following error when compiling for Ubuntu 16.04 in a AWS ARM64 architecture:

`/home/ubuntu/development/thirdparties/XNNPACK/src/f16-dwconv/gen/up8x4-minmax-neonfp16arith-acc2.c:1:0: error: unknown value 'armv8.2-a+fp16' for -march`

Could you please let me know if I am doing something wrong or if there is a workaround to get XNNPACK compiled in this setup?

Thanks,

Pablo.

**Comment by Maratyszcza** [comment]
It looks like the compiler is too old

**Comment by pablogh-2000** [comment]
Thanks for this. I upgraded GCC to 7.5.0, now I get:

```
Assembler messages:
Error: unknown architectural extension `dotprod'
```

Same happens with GCC 8.5.0.

I guess this is a gcc problem, rather than XNNPACK's. However, any ideas, will be massively appreciated.

**Comment by Maratyszcza** [comment]
AFAICT you get this error from system assembler, which doesn't recognize NEON DOT product ISA extension.

**Comment by fwz-fpga** [comment]
> Hi,
> 
> I am getting the following error when compiling for Ubuntu 16.04 in a AWS ARM64 architecture:
> 
> `/home/ubuntu/development/thirdparties/XNNPACK/src/f16-dwconv/gen/up8x4-minmax-neonfp16arith-acc2.c:1:0: error: unknown value 'armv8.2-a+fp16' for -march`
> 
> Could you please let me know if I am doing something wrong or if there is a workaround to get XNNPACK compiled in this setup?
> 
> Thanks,
> 
> Pablo.

hello, do you resolve this problem, I also meet this. I have arm arrch64 device with ubuntu os, confused whether the gcc version is too low(gcc (Ubuntu/Linaro 6.5.0-2ubuntu1~16.04) 6.5.0 20181026)?

**Comment by pablogh-2000** [comment]
Hello.
Unfortunately, we did not manage to the problem fixed. We tried changing some code, but eventually it was just too much to change to make it to work without the GCC flags mentioned above.

We have ended up going for docker as a solution.

Thanks,
Pablo.

**Comment by fwz-fpga** [comment]
> Hello.
> Unfortunately, we did not manage to the problem fixed. We tried changing some code, but eventually it was just too much to change to make it to work without the GCC flags mentioned above.
> 
> We have ended up going for docker as a solution.
> 
> Thanks,
> Pablo.

thanks, you mean that there are official images with  pre-built xnnpack in docker hub? What's the image name...

**Comment by xloem** [comment]
Looks like the system assembler (`as`) is in the binutils package, not the gcc (`cc1`) package.

**Comment by pablogh-2000** [comment]
> > Hello.
> > Unfortunately, we did not manage to the problem fixed. We tried changing some code, but eventually it was just too much to change to make it to work without the GCC flags mentioned above.
> > We have ended up going for docker as a solution.
> > Thanks,
> > Pablo.
> 
> thanks, you mean that there are official images with pre-built xnnpack in docker hub? What's the image name...

Sorry, I did not see this question before. No, we built our own docker image.
