### ISSUE TITLE
Per-channel quantization support

### ISSUE THREAD

**Issue by dev0x13** [google/XNNPACK#1497]
Is there a plan for per-channel quantization support for U8 kernels? I am asking because per-channel quantization is default for post training full integer quantization in TF 2.4+.

**Comment by Maratyszcza** [comment]
Per-channel quantization is being worked on, but it will be supported only for signed quantization schema.

**Comment by Maratyszcza** [comment]
I expect this to land in 1-2 weeks for a limited set of platforms.

**Comment by dev0x13** [comment]
Cool! Thank you again!
