### ISSUE TITLE
fp16 is used automatically in newer devices?

### ISSUE THREAD

**Issue by andrew-yang0722** [google/XNNPACK#1508]
The newer devices has fp16 arithmetic capability. 
Will fp16 be used automatically for faster inference on supported devices ?
Or Should I change something or build xnnpack with options?

I found compile flag " -march=armv8.2-a+fp16+dotprod" in CMakeLists.txt

Especially, I am using Interpreter.Options setUseXNNPACK() of TF lite.
I am wondering that fp16 function is working in TF Lite xnnpack mode.

**Comment by Maratyszcza** [comment]
FP16 arithmetic is **NOT** currently used in the XNNPACK delegate for TensorFlow Lite.

**Comment by andrew-yang0722** [comment]
@Maratyszcza 
Is there any way to make Tf lite to use FP16 of XNNPACK?
or Any plan to support fp16 XNNPACK to TF Lite?

**Comment by Maratyszcza** [comment]
XNNPACK implements several operators in FP16. When those would be exposed in the TensorFlow Lite delegate is TBD.
