### ISSUE TITLE
cmake build error

### ISSUE THREAD

**Issue by fwz-fpga** [google/XNNPACK#1551]
I have build xnnpack on arm platform(aarch64).
mkdir build && cd build && cmake .. && make -j20
but it throws error:
XNNPACK/src/qs8-gemm/gen/1x8c4-minmax-fp32-neondot.c:1:0: error: invalid feature modifier in ‘-march=armv8.2-a+dotprod’

device doesn't support armv8.2 dot instruction?

**Comment by Maratyszcza** [comment]
This usually means that your compiler is too old and doesn't support NEON dot product instructions. Try using a newer version of the compiler.

**Comment by ninn55** [comment]
is there a way to disable xnnpack from using NEON dot product instructions?
Changing the compiler is sometimes not an option. The Hardware may not support newer compiler.

**Comment by Maratyszcza** [comment]
No, this is not supported

**Comment by adamjstewart** [comment]
Any idea what the minimum version of GCC required for arm support is?

**Comment by adamjstewart** [comment]
Looks like the answer is GCC 8: https://www.gnu.org/software/gcc/gcc-8/changes.html

Wish this flag was only added when the compiler supported it...

**Comment by adamjstewart** [comment]
I wonder if `-DXNNPACK_ENABLE_ARM_DOTPROD=OFF` would help? Not sure if it's possible to use that when building PyTorch though.

**Comment by Maratyszcza** [comment]
GCC-10 IIRC
