### ISSUE TITLE
cross-compile on x86_64  to aarch64

### ISSUE THREAD

**Issue by fwz-fpga** [google/XNNPACK#1558]
I have a armv8 device with ubuntu OS.  I am confused with cross-compile tool-chain.  Which tool-chain can i use on x64_64 machine to compile target code run with  aarch64 device.
I download gcc-arm-8.2-2018.08-x86_64-aarch64-linux-gnu from [arm-gcc](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-a/downloads) . 
With this tool-chain && x86_64 machine, I set CC && CXX env and build xnnpack master , cmake throws a error like googlebenchmark error:
`CMake Error at build/googlebenchmark-source/CMakeLists.txt:261 (message):
  Failed to determine the source files for the regular expression backend`
Then I annotated goolebenchmark releated  code in cmakelist.txt, then it throws error :
`In file included from /xnnpack/build/cpuinfo-source/src/x86/init.c:5:
/xnnpack/build/cpuinfo-source/src/x86/cpuid.h:5:11: fatal error: cpuid.h: No such file or directory
  #include <cpuid.h>` why it compile x86 code here ...

**Comment by Maratyszcza** [comment]
This question is out of scope for XNNPACK. Please refer to support channels for CMake and the cross-toolchain that you use.
