### ISSUE TITLE
Low granularity of compilation logic in CMake for aarch64 

### ISSUE THREAD

**Issue by robert-kalmar** [google/XNNPACK#1559]
The compilation logic in CMake for aarch64 platform has hardwired the  Arm8.2-a architecture:
```
IF(XNNPACK_TARGET_PROCESSOR MATCHES "^(aarch64|arm64)$" OR IOS_ARCH MATCHES "^arm64.*")
  SET_PROPERTY(SOURCE ${XNNPACK_AARCH64_NEONFP16ARITH_MICROKERNEL_SRCS} APPEND_STRING PROPERTY COMPILE_FLAGS " -march=armv8.2-a+fp16 ")
  SET_PROPERTY(SOURCE ${XNNPACK_NEONDOT_MICROKERNEL_SRCS} APPEND_STRING PROPERTY COMPILE_FLAGS "  -march=armv8.2-a+dotprod ")
  SET_PROPERTY(SOURCE ${XNNPACK_AARCH64_ASM_MICROKERNEL_SRCS} APPEND_STRING PROPERTY COMPILE_FLAGS "  -march=armv8.2-a+fp16+dotprod ")
  IF(IOS)
    SET_PROPERTY(SOURCE ${XNNPACK_AARCH64_ASM_MICROKERNEL_SRCS} APPEND_STRING PROPERTY COMPILE_FLAGS " -arch ${IOS_ARCH} ")
  ENDIF()
  IF(XNNPACK_TARGET_PROCESSOR STREQUAL "arm64" AND CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "x86_64")
    SET_PROPERTY(SOURCE ${XNNPACK_AARCH64_ASM_MICROKERNEL_SRCS} APPEND_STRING PROPERTY COMPILE_FLAGS " -arch arm64 ")
  ENDIF()
ENDIF()
```
 Based on specification from Arm (https://developer.arm.com/-/media/Arm%20Developer%20Community/PDF/Cortex-A%20R%20M%20datasheets/Arm%20Cortex-A%20Comparison%20Table_v3.pdf) this corresponds to e.g. Cortex-a55 platform.

If compiled for Cortex-a53 platform (Armv8-a architecture)) with XNNPACK_ENABLE_ASSEMBLY=on, the compilation fails, as some *.S files are using instructions for Armv8.2-a: 
```
XNNPACK/src/f16-gemm/gen-inc/1x8inc-minmax-aarch64-neonfp16arith-ld64.S: Assembler messages:
XNNPACK/src/f16-gemm/gen-inc/1x8inc-minmax-aarch64-neonfp16arith-ld64.S:68: Error: selected processor does not support `fmla v16.8h,v20.8h,v0.h[0]'
...
```
(**Steps to reproduce**: Replace `-march=armv8.2-a+fp16+dotprod` with `-mcpu=cortex-a53` in previous CMakeLists.txt snippet)

The problem is the compilation logic does not distinguish btw. various aarch64 variants and bundles all the *.S files together.

**Does this mean the XNNPACK with  `XNNPACK_ENABLE_ASSEMBLY=on` option support only Armv8.2-a architecture?** There are also assembly source files specifically for Cortex-a53 platform.

**Comment by Maratyszcza** [comment]
You don't need to set `-mcpu=cortex-a53` when building XNNPACK. XNNPACK includes microkernels targeting various instruction set extensions that exist on ARM and x86. It sets appropriate flags for each microkernel, and does runtime dispatch to the most optimized microkernel based on supported instruction sets, architecture, and microarchitecture.

**Comment by robert-kalmar** [comment]
Thanks @Maratyszcza, 
I see the logic for the suitable microkernel runtime dispatch is located in the `src/init.c `.
