### ISSUE TITLE
How to build XNNPACK with cmake for IOS.

### ISSUE THREAD

**Issue by Mrlyk423** [google/XNNPACK#1560]
I find that the supported CMAKE_SYSTEM_NAME in the CMakeLists.txt is only Darwin|Linux|Android|Windows|CYGWIN|MSYS. So how can I build XNNPACK with cmake for IOS.

**Comment by Maratyszcza** [comment]
I don't think we ever tested it, but it is supposed to work with [this toolchain](https://github.com/leetal/ios-cmake).

**Comment by Mrlyk423** [comment]
I build xnnpack with IOS toolchain, but fail with the following errors:
``
CMake Error at  ../xnnpack/CMakeLists.txt:86 (MESSAGE):
  Unrecognized CMAKE_SYSTEM_NAME = iOS
``

**Comment by zhitaop** [comment]
@Maratyszcza  Sorry for replying to this closed issue, but I was also trying to build xnnpack for iOS using cmake, with the toolchain mentioned above. I also got the same error:

> @Maratyszcza I build xnnpack with IOS toolchain, but fail with the following errors: `CMake Error at ../xnnpack/CMakeLists.txt:86 (MESSAGE): Unrecognized CMAKE_SYSTEM_NAME = iOS`

It looks like iOS build with CMake is not supported yet. Will there be any plan to add this support in the future?
