### ISSUE TITLE
Segfault in minmax-fma3-broadcast

### ISSUE THREAD

**Issue by mharshe** [google/XNNPACK#1602]
While testing xnnpack with some of my code, I get the following segfault:
```
received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe9c0b700 (LWP 105637)]
xnn_f32_igemm_minmax_ukernel_5x16__fma3_broadcast (mr=<optimized out>, nc=64, kc=12, ks=360, a=<optimized out>, w=0x5555557d8fc0, c=0x7fffd09311c0, cm_stride=256, cn_stride=64, a_offset=0, zero=0x5555557b1500, params=0x5555557b2640)
    at ../../src/f32-igemm/gen/5x16-minmax-fma3-broadcast.c:160
160	      _mm256_storeu_ps(c4, vacc4x01234567);
(gdb) bt
#0  xnn_f32_igemm_minmax_ukernel_5x16__fma3_broadcast (mr=<optimized out>, nc=64, kc=12, ks=360, a=<optimized out>, w=0x5555557d8fc0, c=0x7fffd09311c0, cm_stride=256, cn_stride=64, a_offset=0, zero=0x5555557b1500, params=0x5555557b2640)
    at ../../src/f32-igemm/gen/5x16-minmax-fma3-broadcast.c:160
#1  0x00007ffff33c0b9a in xnn_compute_igemm (context=context@entry=0x5555557b2580, mr_block_start=mr_block_start@entry=37635, nr_block_start=<optimized out>, mr_block_size=mr_block_size@entry=5, nr_block_size=<optimized out>) at ../../src/operator-run.c:179
#2  0x00007ffff341a474 in thread_parallelize_2d_tile_2d (threadpool=0x5555557aecc0, thread=0x5555557aeec0) at pthreadpool-source/src/portable-api.c:245
#3  0x00007ffff3423ff2 in thread_main (arg=0x5555557aeec0) at pthreadpool-source/src/pthreads.c:210
#4  0x00007ffff76946db in start_thread (arg=0x7fffe9c0b700) at pthread_create.c:463
#5  0x00007ffff39a271f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
I ran this with XNNPACK compiled in `RelWithDebInfo` on an Intel machine running Ubuntu 18.04 LTS. Now sure how I should go about resolving this. Would be happy to provide any additional details if necessary.

**Comment by Maratyszcza** [comment]
Are you using XNNPACK with the TFLite delegate?

**Comment by mharshe** [comment]
We are using XNNPACK directly with our own code (without TFLite). This error occurred while trying to run inference with the vggnet. The error doesn't occur with Alexnet or Mobilenet v1.

**Comment by Maratyszcza** [comment]
If you can reproduce the error with a TensorFlow Lite model, please share the details. Otherwise, I don't have enough details to investigate.

**Comment by mharshe** [comment]
No issues. I'll try to recreate the network using the xnnpack functions similar to the examples and see if the problems persists. I'll update and reopen this issue with the sample code if I can reproduce the problem.

**Comment by mharshe** [comment]
FYI, the problem was not in xnnpack code, but rather in some unrelated portion of my code triggering a segfault.
