### ISSUE TITLE
There is no function for mod operation in include file of xnnpack.h

### ISSUE THREAD

**Issue by carrycooldude** [google/XNNPACK#1612]
For addition we have 
> enum xnn_status xnn_create_add_nd_f32(
  float output_min,
  float output_max,
  uint32_t flags,
  xnn_operator_t* add_op_out);

>enum xnn_status xnn_setup_add_nd_f32(
  xnn_operator_t add_op,
  size_t num_input1_dims,
  const size_t* input1_shape,
  size_t num_input2_dims,
  const size_t* input2_shape,
  const float* input1,
  const float* input2,
  float* output,
  pthreadpool_t threadpool);

[This is the link for it](https://github.com/google/XNNPACK/blob/master/include/xnnpack.h)

**Comment by Maratyszcza** [comment]
Right, `MOD` operator is not supported, and there are no short-term plans to support it.
