### ISSUE TITLE
can't support loongarch64

### ISSUE THREAD

**Issue by outyang** [google/XNNPACK#1695]
loongarch64 is an new  architecture,it error like this while i built tensorflow-lite:
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
CMake Error at /home/yang/123/tflite_build/xnnpack/CMakeLists.txt:80 (MESSAGE):
  Unrecognized XNNPACK_TARGET_PROCESSOR = loongarch64

-- Configuring incomplete, errors occurred!

**Comment by Maratyszcza** [comment]
Loongarch64 is not supported, and there are no plans to support it.
