### ISSUE TITLE
QS8 convolution is slower than floating point for WASM (without SIMD)

### ISSUE THREAD

**Issue by shanumantesc** [google/XNNPACK#1696]
Platform: Chrome 91.0.4472.164 on Macbook Pro 16-inch, 2019. SIMD is not enabled for now to understand behavior on browsers which do not support SIMD. Chrome is used to in order to get precise layer-wise measurements instead of rounding to 1 ms as done by browsers like Safari.

Tested on commit : https://github.com/google/XNNPACK/commit/ab952f146afb7c764664e2c2233cfc8a09992ac2

We observe that QS8 convolution is slower than floating point; a subset of configurations for which  QS8 conv is more than 10% slower in our measurements:

Input Shape (NHWC) | Output Shape (NHWC) | Dilation W/H | Strides W/H | Padding L/T/B/R | Kernel Shape W/H | XNNPACK float (ms) | XNNPACK QS8 (ms) | Slowdown %
-- | -- | -- | -- | -- | -- | -- | -- | --
1x168x96x4 | 1x84x48x16 | 1,1 | 2,2 | 1,1,1,1 | 3x3 | 3.05 | 4.27 | 0.4
1x84x48x16 | 1x42x24x64 | 1,1 | 2,2 | 0,0,0,0 | 2x2 | 4.845 | 5.805 | 0.1981424149
1x21x12x24 | 1x21x12x96 | 1,1 | 1,1 | 0,0,0,0 | 1x1 | 0.685 | 0.915 | 0.3357664234
1x21x12x24 | 1x21x12x24 | 1,1 | 1,1 | 2,0,2,0 | 5x1 | 0.685 | 1.02 | 0.4890510949

Expected result : QS8 inference is faster than floating point

**Comment by Maratyszcza** [comment]
There shouldn't be an expectation that quantized inference is faster than floating-point inference on all platforms. Whether it is faster depends on architectural and microarchitectural characteristics of the host processor.

In case of WebAssembly 1.0, quantized microkernels use a very limited number of general-purpose registers for both data pointers and data values, while floating-point microkernels use floating-point registers to store data values, resulting in much lower register pressure. Thus, it is not surprising that floating-point inference is faster on this platform.
