### ISSUE TITLE
depthwise conv params set 

### ISSUE THREAD

**Issue by fwz-fpga** [google/XNNPACK#1751]
In tflite, xnnpack operators used by subgraph.  
Like xnn_define_depthwise_convolution_2d, this api add a depthwiseconv2d op to subgraph. In this api, there is a param depth_multiplier means filter_channels/input_channels.
However, I want to use xnn_create_convolution2d_nhwc_f32 to realize the depthwiseconv2d operator. And I am confused how to specific the 
  ```
  uint32_t groups,
  size_t group_input_channels,
  size_t group_output_channels,
  size_t input_channel_stride,
  size_t output_channel_stride,
```
params in xnn_create_convolution2d_nhwc_f32 when depth_multiplier != 1

**Comment by fwz-fpga** [comment]
![image](https://user-images.githubusercontent.com/29475777/128120726-b7534c13-d4d9-40f2-be1f-98e96096034b.png)

**Comment by Maratyszcza** [comment]
Please refer to https://github.com/google/XNNPACK/blob/0c2a31ee2d0b9189a316e216f8615208a6a510c9/src/runtime.c#L520-L541 for translation between Depthwise Convolution attributes and `xnn_create_convolution2d_nhwc_f32`.
