### ISSUE TITLE
Miss bench/google ?

### ISSUE THREAD

**Issue by lum1n0us** [google/XNNPACK#1759]
Do they exist ?

* "bench/google/conv.h"*
https://github.com/google/XNNPACK/blob/e145d567a3e435631430bd5238c5a5b487d7bad0/BUILD.bazel#L7449

*"bench/google/dwconv.h",* in https://github.com/google/XNNPACK/blob/e145d567a3e435631430bd5238c5a5b487d7bad0/BUILD.bazel#L7531

**Comment by Maratyszcza** [comment]
These headers are not meant to be open-sourced. The references in the `BUILD.bazel` file are removed in #1760.
