### ISSUE TITLE
why use XNN_EXTRA_BYTES

### ISSUE THREAD

**Issue by fwz-fpga** [google/XNNPACK#1890]
In my project, I allocate mem size = input.size, not input.size + XNN_EXTRA_BYTES. It works fine. So why need XNN_EXTRA_BYTES, is it affect the kernel performance?

**Comment by Maratyszcza** [comment]
If you don't allocate `XNN_EXTRA_BYTES`, you may get access violations (segfault) from XNNPACK microkernels.

**Comment by fwz-fpga** [comment]
`#include<xnnpack.h>
#include "stdio.h"
#include <vector>
#include <string>
#include <cstring>
#include <stdexcept>
#include <limits>

#include <memory>
#include <chrono>

using namespace std;

#define FP32_MAX  +std::numeric_limits<float>::infinity()
#define FP32_MIN  -std::numeric_limits<float>::infinity()

struct Deleter final {
  void operator()(const xnn_operator_t op) const {
    xnn_delete_operator(op);
  }
};

using XnnOperator = std::unique_ptr<xnn_operator, Deleter>;

void init_data(float* data, int size) {
    for(int i =0; i< size; i++) {
       data[i] = 1.0;
    }
}

struct convParams{
   std::vector<int> sPadding;
   std::vector<int> sKernel;
   std::vector<int> sStride;
   std::vector<int> sDilation;
   int sGroup;
   std::vector<int> sWeightShape;
};

bool create_conv_op(convParams& opts, std::vector<XnnOperator>& convolution_op, float* weight_data){
    xnn_status create_status;
    xnn_operator_t xnn_convolution_op;
    create_status = xnn_create_convolution2d_nhwc_f32(
        opts.sPadding[0],                                       // output_padding_top
        opts.sPadding[3],                                       // output_padding_right
        opts.sPadding[1],                                       // output_padding_bottom
        opts.sPadding[2],                                       // output_padding_left
        opts.sKernel[0],                                        // kernel_height
        opts.sKernel[0],                                        // kernel_width
        opts.sStride[0],                                        // subsampling_height
        opts.sStride[1],                                        // subsampling_width
        opts.sDilation[0],                                      // dilation_height
        opts.sDilation[1],                                      // dilation_width
        opts.sGroup,                                            // groups
        opts.sWeightShape[3],                                 // group_input_channels
        opts.sWeightShape[0],                                 // group_input_channels
        opts.sWeightShape[3],                                 // group_input_channels
        opts.sWeightShape[0],                                 // group_input_channels
        weight_data,
        nullptr,  // bias
        FP32_MIN, // output_min
        FP32_MAX,                                               // output_max
        0u,                                                     // flags
        &xnn_convolution_op);                                   // operator
    if (create_status != xnn_status_success) {
       printf("create error\n");
       return false;
    }
    convolution_op.emplace_back(XnnOperator(xnn_convolution_op));
    return true;
}

bool setup_and_run(const float* input, std::vector<int>& input_shape, float* output, std::vector<XnnOperator>& convolution_op) {
    xnn_status setup_status, run_status;
    setup_status = xnn_setup_convolution2d_nhwc_f32(
        convolution_op[0].get(),                                        // operator
        input_shape[0],                                        // batch_size
        input_shape[1],                                     // input_height
        input_shape[2],                                      // input_width
        input,
        output,
        nullptr  /* thread pool */);

    if (setup_status != xnn_status_success) {
        printf("failed to setup FP32 Convolution operator\n");
        return false;
    }
    run_status = xnn_run_operator(convolution_op[0].get(), nullptr /* thread pool */);
    if (run_status != xnn_status_success) {
        printf("failed to run FP32 Convolution operator\n");
        return false;
    }
    return true;
}

int main() {
  bool is_initialized_ = false;
  if (!is_initialized_) {
    const xnn_status status = xnn_initialize(nullptr);
    is_initialized_ = (xnn_status_success == status);

    if (!is_initialized_) {
      if (xnn_status_out_of_memory == status) {
        printf("Failed to initialize XNNPACK! Reason: Out of memory.");
      } else if (xnn_status_unsupported_hardware == status) {
        printf("Failed to initialize XNNPACK! Reason: Unsupported hardware.");
      } else {
        printf("Failed to initialize XNNPACK! Reason: Unknown error!");
      }
    }
  }

    std::vector<int> input_shape{1,180,160,3};
    std::vector<int> sPadding{1,2,1,2};
    std::vector<int> sKernel{7,7};
    std::vector<int> sStride{4,4};
    std::vector<int> sDilation{1,1};
    std::vector<int> sWeightShape{24,7,7,3};
    std::vector<XnnOperator> conv_op;

    convParams params1{.sPadding = sPadding,
                       .sKernel = sKernel,
                       .sStride = sStride,
                       .sDilation = sDilation,
                       .sGroup = 1,
                       .sWeightShape = sWeightShape};
    std::vector<float> weight(24*7*7*3);
    init_data(weight.data(), weight.size());

    create_conv_op(params1, conv_op, weight.data());

    std::vector<float> input(1*3*180*160);
    //std::vector<float> input(1*3*180*160+XNN_EXTRA_BYTES/4);  // here with XNN_EXTRA_BYTES
    std::vector<float> output(1*45*40*24);
    init_data(input.data(), input.size());
    init_data(output.data(), output.size());
    for (size_t i = 0; i< 10; i++) {
        setup_and_run(input.data(), input_shape, output.data(), conv_op);
    }

    for (size_t i = 0; i< 10; i++) {
      auto t_start = std::chrono::high_resolution_clock::now();
      setup_and_run(input.data(), input_shape, output.data(), conv_op);
      auto t_end = std::chrono::high_resolution_clock::now();
      float ms   = std::chrono::duration<float, std::milli>(t_end - t_start).count();
      printf("finish! time used: %f ms\n", ms*1000);
    }
    return 0;
}`

**Comment by fwz-fpga** [comment]
I write a project, above is the code.   Input without XNN_EXTRA_BYTES malloc, it works fine, not crash.... What's the reason :(

**Comment by Maratyszcza** [comment]
If you're lucky, your code **may** not crash without `XNN_EXTRA_BYTES`. However, if you want to be sure that it doesn't crash, add `XNN_EXTRA_BYTES` to allocations.

**Comment by snnn** [comment]
@Maratyszcza does the requirement apply to model weights and inputs too? If it does, it sounds like we need to copy the weights and input tensors before passing them to XNNPack. But I didn't see TFLite has such a logic. TFLite only adds XNN_EXTRA_BYTES to quasi static data. 
And in the bench models in this repo's "models" dir, only very a few tensors are padded with XNN_EXTRA_BYTES. For example, in QS8MobileNetV2, only v0 has it. How do you guarantee the other tensors won't have an out-bound-read error? An fp32-mobilenet-v1.cc even doesn't have such a concern at all.

**Comment by Maratyszcza** [comment]
The requirement apply to input tensors (TFLite tensors are arena-allocated with 64-byte padding). It doesn't apply to weights.

Built-in models don't necessarily satisfy this constraint. I only added `XNN_EXTRA_BYTES` padding in models whenever ASan complained.
