### ISSUE TITLE
armv7 build support dropped?

### ISSUE THREAD

**Issue by ruabmbua** [google/XNNPACK#1909]
I am trying to build tflite, and noticed, that I can`t build since newer version, because this library tries to compile with armv8 features enabled. I have used the CMAKE_SYSTEM_PROCESSOR=armv7 option, so I am a bit surprised.

Is armv7 support completely dropped for this library?

I am asking, because I noticed, that neonv8 sources are always added to the build, when CMAKE_SYSTEM_PROCESOR is set  to armv7.

**Comment by Maratyszcza** [comment]
If by ARMv7 you mean 32-bit ARM architecture, it is still supported, although XNNPACK doesn't strictly target ARMv7: for mobile builds, the minimum is ARMv7-A with NEON, for non-mobile build the minimum is ARMv6 with VFPv2. ARMv8 added some 32-bit instructions too, and XNNPACK detects and uses those when running on ARMv8 processors in 32-bit mode.
