### ISSUE TITLE
Incorrect results for quantized inference when running 32bit binary on 64bit ARM devices

### ISSUE THREAD

**Issue by shanumantesc** [google/XNNPACK#1922]
We get incorrect results for convolution, elementwise multiplication and fully connected layers running QS8 inference when running 32bit binary on a 64bit ARM android device (Reproduces on https://www.gsmarena.com/samsung_galaxy_note10-9788.php#sm-n970u , https://www.gsmarena.com/motorola_moto_e6i-10734.php)

We are able to fix this if we change the check in https://github.com/google/XNNPACK/blob/0bf8afa/src/init.c#L140 to also check for `XNN_ARCH_ARM64` flag which seems to indicate that `cpuinfo_has_arm_neon_dot()` is being reported or used incorrectly.

**Comment by Maratyszcza** [comment]
I managed to partially reproduce the issue: channel-wise quantized convolution produce incorrect results on AArch32 processors with NEON-DOT extension. That bug is fixed in 694d2524757f9040e65a02c374e152a462fe57eb, please check if it fix your use-case as well.

**Comment by Maratyszcza** [comment]
Pulled into TensorFlow Lite in tensorflow/tensorflow@e843d861b6c6d95503810ea84e1ecd6496218b01.

**Comment by Maratyszcza** [comment]
Can you provide a simple repro?

**Comment by shanumantesc** [comment]
```
Input int8: {1, 1, 1, 1, 3, 3, 3, 3, 1, 3, 5, 7, 1, 3, 5, 7}
Input dims (NHWC) : 2x2x4x1
Input scale : 0.5
Input zero Point: -1

Kernel int8: {2, 4, 6, 8, -2, 2, -2, 2, -2, -2, 2, 2, 97, 114, 97, 109}
Kernel dims (OHWI) : 3x2x2x1
Kernel scale: 0.5
kernel zero point: 0
stride: 2
dilation : 1

Bias int32: {1, 2, 3}
Zero point: 0
Scale: 0.25

Output_min: -127
Output_max: 128

Output expected int8: {17, 1, 4, 17, 1, 4, 16, 3, 2, 36, 3, 2}
Output actual int8: {-32, 23, -12, -21, -16, 13, -12, -21, 16, 18, -12, -21} // <-- this keeps changing for the same input across multiple runs
```

**Comment by shanumantesc** [comment]
Update:

It turns out the issue is in our build system -- the neondot functions were being incorrectly stubbed out when building for armeabi-v7a since the march flags are provided by the build system. Updating the logic to remove the stubs fixes this issue.

Thanks for looking into this!
