### ISSUE TITLE
error: incompatible types when assigning to type ‘int32x4_t’ from type ‘int’

### ISSUE THREAD

**Issue by fwz-fpga** [google/XNNPACK#1924]
I have a device with linux os && armv7.
Recently, I need to cross compile to build xnnpack lib,  host is x86_64 cpu. And the toolchain is gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabi.
With this toolchain, the error is 
`error: incompatible types when assigning to type ‘int32x4_t’ from type ‘int’
     vacc0x0123 = vcvtnq_s32_f32(vproduct0x0123);`
I find that arm_neon.h in  gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabi doesn't have this  vcvtnq_s32_f32 intrinsic.
This toolchain is for AArch32, is it the problem of toolchain?
I have tried  gcc-arm-8.2-2018.08-x86_64-arm-linux-gnueabi , it is the same error.

As for complie, I have tried another toolchain gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu  this is for aarch64, it works fine. 

So what's the problem, aarch32 toolchain not support some xnnpack kernels?

**Comment by fwz-fpga** [comment]
Like this, https://github.com/google/XNNPACK/pull/1404/files , modify the cmakelist.txt, remove XNNPACK_NEONDOT_MICROKERNEL_SRCS, it can build success. :(

**Comment by Maratyszcza** [comment]
In which source file do you get the error?

**Comment by fwz-fpga** [comment]
XNNPACK/src/qs8-gemm/gen/1x8c4-minmax-fp32-neondot.c:94:16: error: incompatible types when assigning to type ‘int32x4_t’ from type ‘int’
     vacc0x0123 = vcvtnq_s32_f32(vproduct0x0123);

**Comment by fwz-fpga** [comment]
toolchain.cmake

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR armv7)
set(TOOLCHAIN_DIR /root/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabi/bin)
set(CMAKE_C_COMPILER ${TOOLCHAIN_DIR}/arm-linux-gnueabi-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_DIR}/arm-linux-gnueabi-g++)
add_compile_options(-fstack-protector-all -Wall -mfloat-abi=softfp)

**Comment by Maratyszcza** [comment]
The compiler lacks the right intrinsic function. XNNPACK includes a polyfill for this intrinsic, but for some reason it doesn't get used:

https://github.com/google/XNNPACK/blob/694d2524757f9040e65a02c374e152a462fe57eb/src/xnnpack/intrinsics-polyfill.h#L134-L147

**Comment by fwz-fpga** [comment]
I know the reason, I use this commit 16d79edc423d0a622b190cbfc6703c39ca2c0097
https://github.com/google/XNNPACK/blob/16d79edc423d0a622b190cbfc6703c39ca2c0097/src/xnnpack/intrinsics-polyfill.h#L134-L141    code in(#ifdef __AVX512F__ not compile)
Now master is ok.

**Comment by fwz-fpga** [comment]
THX :)
