### ISSUE TITLE
xnn deconvolution2d_nhwc_f32 produces wrong result when group 2

### ISSUE THREAD

**Issue by sonu1-p** [google/XNNPACK#1951]
Hi Team,
We noticed that xnnpack deconvolution2d_nhwc_f32 produces wrong output when compared to ConvTranspose of other inference engines like onnx runtime (also tried another internal inference engine) when group 2.
Code used to get output from xnnpack:

    xnn_initialize(nullptr);
    const uint32_t pad = 0;
    const uint32_t k = 3;
    const uint32_t stride = 1;
    const uint32_t dilation = 1;
    const uint32_t groups = 2;
    const uint32_t in_channels_per_group = 1;
    const uint32_t out_channels_per_group = 1;
    const uint32_t in_channels = 2;
    const uint32_t out_channels = 2;
    constexpr auto output_min = std::numeric_limits<float>::lowest();
    constexpr auto output_max = std::numeric_limits<float>::max();

    const std::size_t batch_size = 1;
    const std::size_t input_h = 2;
    const std::size_t input_w = 2;
    const std::size_t adj_h = 0;
    const std::size_t adj_w = 0;

    // Not using xnn_extra_bytes in below example but have with tried with them too, I get the same result.
    std::vector<float> x_data = {1.0f, 5.0f, 2.0f, 6.0f, 3.0f, 7.0f, 4.0f, 8.0f}; // data format nhwc
    std::vector<float> w_data = {1.0f, 1.0f, 2.0f, 2.0f, 3.0f, 3.0f, 4.0f, 4.0f, 5.0f, 5.0f, 6.0f, 6.0f, 7.0f, 7.0f, 8.0f, 8.0f, 9.0f, 9.0f }; // data format [out_channel/group, kh, kw, in_channel]
    std::vector<float> y_data(32);

    xnn_operator_t conv_trans_op = nullptr;
    xnn_create_deconvolution2d_nhwc_f32(pad,pad,pad,pad,
                                        k, k,
                                        stride, stride,
                                        dilation, dilation,
                                        groups, in_channels_per_group, out_channels_per_group,
                                        in_channels, out_channels,
                                        w_data.data(),
                                        nullptr,
                                        output_min,
                                        output_max,
                                        0,  
                                        &conv_trans_op);
    xnn_setup_deconvolution2d_nhwc_f32(conv_trans_op, batch_size,
                                       input_h, input_w, adj_h, adj_w,
                                       x_data.data(), y_data.data(), nullptr);
    // run XNNPACK operator
    xnn_run_operator(conv_trans_op, nullptr);

Code used to get output from onnx-runtime for same input:

     import onnx
     import numpy as np
     from onnx import numpy_helper
    
    x_f = np.array([1.,2.,3.,4.,5.,6.,7.,8.]).astype(np.float32)
    x = np.reshape(x_f, (1, 2, 2, 2)) # nchw format
    print(x)
    x_trans = np.transpose(x, (0, 2,3,1)) # To to double check the values used for xnnpack nhwc
    print(x_trans) # This is what we use as x when running xnnpack

    w_f = np.array([1.,2.,3.,4.,5.,6.,7.,8.,9.,1.,2.,3.,4.,5.,6.,7.,8.,9.]).astype(np.float32)
    w = np.reshape(w_f, (2, 1, 3, 3)) # shape [in_channels, out_channels/group, kh, kw] as expected by onnx
    print(w)
    w_trans = np.transpose(w, (1,2,3,0)) # format expected by xnnpack [out_channel.group, kh, kw, input_channels]
    print(w_trans) # This is what we use as w when running xnnpack

    node = onnx.helper.make_node("ConvTranspose", ["X", "W"], ["Y"],
                                                            strides=[1, 1], 
                                                            group=2)
    X = onnx.helper.make_tensor_value_info('X', onnx.TensorProto.FLOAT, [1,2,2,2])
    # Create one output (ValueInfoProto)
    Y = onnx.helper.make_tensor_value_info('Y', onnx.TensorProto.FLOAT, [1,2,4,4])
    W = onnx.helper.make_tensor_value_info('W', onnx.TensorProto.FLOAT, [2,1,3,3])
    W_in = numpy_helper.from_array(w, name='W')

    # Create the graph (GraphProto)
    graph_def = onnx.helper.make_graph(
             [node],
             'conv-trans',
             [X, W], 
             [Y],
             initializer=[W_in])

     # Create the model (ModelProto)
     model_def = onnx.helper.make_model(graph_def, producer_name='rank-4-identity-model')
     onnx.save(model_def, "conv-trans.onnx")
     print('The model is:\n{}'.format(model_def))
     onnx.checker.check_model(model_def)
     print('The model is checked!')

     import onnxruntime as ort 
     ort_sess = ort.InferenceSession('conv-trans.onnx')
     outputs = ort_sess.run(None, {'X': x}) 
     print(outputs)
     # Transpose from nchw to nhwc
     out_trans = np.transpose(outputs[0], (0, 2, 3, 1)) 
     print(out_trans)

We see that the result of onnxruntime is (result is already transposed to nhwc format)
[[[[  1.   5.]
   [  4.  16.]
   [  7.  27.]
   [  6.  18.]]

  [[  7.  27.]
   [ 23.  71.]
   [ 33.  97.]
   [ 24.  60.]]

  [[ 19.  63.]
   [ 53. 149.]
   [ 63. 175.]
   [ 42. 102.]]

  [[ 21.  49.]
   [ 52. 112.]
   [ 59. 127.]
   [ 36.  72.]]]]
   
While result of xnnpack is:

[[[[  1.,  25.],
    [  3.,  60.],
    [  4.,  66.],
    [  4.,  36.]],

   [[  5.,  70.],
    [ 14., 159.],
    [ 19., 172.],
    [ 14.,  96.]],

   [[ 10.,  89.],
    [ 29., 198.],
    [ 34., 211.],
    [ 22., 118.]],

   [[ 12.,  56.],
    [ 28., 127.],
    [ 31., 135.],
    [ 20.,  72.]]]] 
   
   
   Can you please help look into this? Thanks!

**Comment by sonu1-p** [comment]
Created an equivalent tflite model for the onnx example above and transposed its output to nhwc
[model.tflite.pdf](https://github.com/google/XNNPACK/files/7377395/model.tflite.pdf)
(Appended .pdf after model file name to be able to upload it on github. Please remove it if it causes trouble in runnign the model)

Run tflite model using below command:
```
import numpy as np
import tensorflow as tf

interpreter = tf.lite.Interpreter(model_path="./model.tflite")
interpreter.allocate_tensors()
# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
x_f = np.array([1.,2.,3.,4.,5.,6.,7.,8.]).astype(np.float32)
x = np.reshape(x_f, (1, 2, 2, 2)) # nchw format
interpreter.set_tensor(input_details[0]['index'], x)
interpreter.invoke()
# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)

# transpose nchw output of model to nhwc
output_trans = np.transpose(output_data, (0,2,3,1))
print(output_trans)

```
The result of this model is also same as onnxruntime and not xnnpack.

**Comment by Maratyszcza** [comment]
There are many layout variations for grouped deconvolution, and XNNPACK probably use a different variation than you expect. Please see the unit test below for the layout used by XNNPACK:

https://github.com/google/XNNPACK/blob/c67779ebbd52dca1664e9dfd1a516806585e4f2b/test/deconvolution-operator-tester.h#L790-L833
