### ISSUE TITLE
‘XNN_LOG_LEVEL’ undeclared

### ISSUE THREAD

**Issue by arkhadem** [google/XNNPACK#2178]
I'm facing the following errors while doing bash scripts/build-local.sh, any solution?

`
In file included from /home/arkhadem/XNNPACK/src/jit/memory.c:23:0:
/home/arkhadem/XNNPACK/src/xnnpack/log.h:19:4: error: #error "Undefined XNN_LOG_LEVEL"
   #error "Undefined XNN_LOG_LEVEL"
    ^~~~~
In file included from /home/arkhadem/XNNPACK/src/xnnpack/log.h:13:0,
                 from /home/arkhadem/XNNPACK/src/jit/memory.c:23:
/home/arkhadem/XNNPACK/src/xnnpack/log.h: In function ‘xnn_log_debug’:
/home/arkhadem/XNNPACK/src/xnnpack/log.h:22:49: error: ‘XNN_LOG_LEVEL’ undeclared (first use in this function); did you mean ‘XNN_OOB_READS’?
 CLOG_DEFINE_LOG_DEBUG(xnn_log_debug, "XNNPACK", XNN_LOG_LEVEL);
                                                 ^
/home/arkhadem/XNNPACK/src/xnnpack/log.h:22:49: note: each undeclared identifier is reported only once for each function it appears in
/home/arkhadem/XNNPACK/src/xnnpack/log.h: In function ‘xnn_log_info’:
/home/arkhadem/XNNPACK/src/xnnpack/log.h:23:47: error: ‘XNN_LOG_LEVEL’ undeclared (first use in this function); did you mean ‘XNN_OOB_READS’?
 CLOG_DEFINE_LOG_INFO(xnn_log_info, "XNNPACK", XNN_LOG_LEVEL);
                                               ^
/home/arkhadem/XNNPACK/src/xnnpack/log.h: In function ‘xnn_log_warning’:
/home/arkhadem/XNNPACK/src/xnnpack/log.h:24:53: error: ‘XNN_LOG_LEVEL’ undeclared (first use in this function); did you mean ‘XNN_OOB_READS’?
 CLOG_DEFINE_LOG_WARNING(xnn_log_warning, "XNNPACK", XNN_LOG_LEVEL);
                                                     ^
/home/arkhadem/XNNPACK/src/xnnpack/log.h: In function ‘xnn_log_error’:
/home/arkhadem/XNNPACK/src/xnnpack/log.h:25:49: error: ‘XNN_LOG_LEVEL’ undeclared (first use in this function); did you mean ‘XNN_OOB_READS’?
 CLOG_DEFINE_LOG_ERROR(xnn_log_error, "XNNPACK", XNN_LOG_LEVEL);
                                                 ^
/home/arkhadem/XNNPACK/src/xnnpack/log.h: In function ‘xnn_log_fatal’:
/home/arkhadem/XNNPACK/src/xnnpack/log.h:26:49: error: ‘XNN_LOG_LEVEL’ undeclared (first use in this function); did you mean ‘XNN_OOB_READS’?
 CLOG_DEFINE_LOG_FATAL(xnn_log_fatal, "XNNPACK", XNN_LOG_LEVEL);
                                                 ^
CMakeFiles/jit.dir/build.make:92: recipe for target 'CMakeFiles/jit.dir/src/jit/memory.c.o' failed
make[2]: *** [CMakeFiles/jit.dir/src/jit/memory.c.o] Error 1
CMakeFiles/Makefile2:7263: recipe for target 'CMakeFiles/jit.dir/all' failed
make[1]: *** [CMakeFiles/jit.dir/all] Error 2
`

**Comment by Maratyszcza** [comment]
Fixed in 1e9c5ac35fd85d9369d1082b5f656f3e0dff7f5d
