### ISSUE TITLE
convolution with nchw format

### ISSUE THREAD

**Issue by fwz-fpga** [google/XNNPACK#2303]
https://github.com/google/XNNPACK/blob/0fd983b4c3a7f82d9d932a3fac6313237d444932/src/operators/convolution-nchw.c#L166-L172
Does it mean that xnnpack support convolution with nchw format with these cases? Will xnnpack support more nchw format optimized kernels?
Onnx model export from pytorch default with nchw format, so if use xnnpack to run onnx model , it will do lots' of extra things(code) with format change. Such as concat\slice\gather.. 
Any suggestions?

**Comment by Maratyszcza** [comment]
XNNPACK supports only a very limited set of NCHW operators for sparse inference. See [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/xnnpack/README.md#sparse-inference) for details. There are no plans for extending NCHW operator support.
