### ISSUE TITLE
wrong link of downloading clog

### ISSUE THREAD

**Issue by dongxiao92** [google/XNNPACK#235]
Hi, thanks for contrbuting such a good project. I'm trying to build xnnpack on nvidia jetson tx2 using cmake. But it seems the download link of clog and cpuinfo is identical. Is this mistake?

in cmake/DownloadCLog.cmake:

> ExternalProject_Add(clog
>   URL https://github.com/pytorch/cpuinfo/archive/d5e37adf1406cf899d7d9ec1d317c47506ccb970.tar.gz
>   URL_HASH SHA256=3f2dc1970f397a0e59db72f9fca6ff144b216895c1d606f6c94a507c1e53a025
>   SOURCE_DIR "${CMAKE_BINARY_DIR}/clog-source"
>   BINARY_DIR "${CMAKE_BINARY_DIR}/clog"
>   CONFIGURE_COMMAND ""
>   BUILD_COMMAND ""
>   INSTALL_COMMAND ""
>   TEST_COMMAND ""
> )

in cmake/DownloadCpuinfo.cmake:

> ExternalProject_Add(cpuinfo
>   URL https://github.com/pytorch/cpuinfo/archive/d5e37adf1406cf899d7d9ec1d317c47506ccb970.tar.gz
>   URL_HASH SHA256=3f2dc1970f397a0e59db72f9fca6ff144b216895c1d606f6c94a507c1e53a025
>   SOURCE_DIR "${CMAKE_BINARY_DIR}/cpuinfo-source"
>   BINARY_DIR "${CMAKE_BINARY_DIR}/cpuinfo"
>   CONFIGURE_COMMAND ""
>   BUILD_COMMAND ""
>   INSTALL_COMMAND ""
>   TEST_COMMAND ""
> )

**Comment by Maratyszcza** [comment]
The link is not wrong. `clog` doesn't have a separate repository, but lives under `deps/clog` in [cpuinfo repository](https://github.com/pytorch/cpuinfo/tree/master/deps/clog).
