### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by rchardx** [google/XNNPACK#245]
Hi,

Will XNNPACK support iOS in future?
Currently, XNNPACK seems cannot be compiled for iOS.

**Comment by Maratyszcza** [comment]
It would probably just work if you copy one of the `build-ios-*.sh` [scripts from QNNPACK](https://github.com/pytorch/QNNPACK/tree/master/scripts). We haven't really tested iOS build, so please let me know if it works.

**Comment by rchardx** [comment]
Hi, I tried your solution.
After adding iOS to the valid CMAKE_SYSTEM_NAME in CMakeList.txt:46, some invalid instruction mnemonic occured.
It seems that correct ARCHs are needed.
See attachment for details.
[build-ios-arm64.log](https://github.com/google/XNNPACK/files/3930247/build-ios-arm64.log)

**Comment by Maratyszcza** [comment]
iOS support is not a high priority for us (nearly every iOS device has a powerful GPU, and [TensorFlow Lite Metal backend](https://blog.tensorflow.org/2019/01/tensorflow-lite-now-faster-with-mobile.html) usually delivers better performance than we could hope to get from a CPU), so it is unlikely to be fixed soon. However, if you're willing to fix the iOS build yourself, a PR would be welcome!

**Comment by rchardx** [comment]
Thank you for your quick response.
