### ISSUE TITLE
XNNPACK CMake build: dependencies checksum error

### ISSUE THREAD

**Issue by madaosik** [google/XNNPACK#2479]
### Issue: CMake crash due to checksums mismatch

The checksums of the downloaded XNNPACK dependency archives **fp16** and **cpuinfo** do not match the expected values defined in `cmake/DownloadFP16.cmake` and `cmake/DownloadCpuinfo.cmake`, crashing the CMake configure phase.

Relevant parts of the CMake Configure phase output:

> -- verifying file...
>        file='/home/madaos/dev/XNNPACK/build/FP16-download/fp16-prefix/src/0a92994d729ff76a58f692d3028ca1b64b145d91.zip'
> -- SHA256 hash of
>     /home/madaos/dev/XNNPACK/build/FP16-download/fp16-prefix/src/0a92994d729ff76a58f692d3028ca1b64b145d91.zip
**>   does not match expected value
>     expected: 'e66e65515fa09927b348d3d584c68be4215cfe664100d01c9dbc7655a5716d70'
>       actual: '0824f777925030f54fbabc3f3ef6975d74937dfe007725720bf129432cea048d'**
> -- Hash mismatch, removing...

> -- verifying file...
>        file='/home/madaos/dev/XNNPACK/build/cpuinfo-download/cpuinfo-prefix/src/5916273f79a21551890fd3d56fc5375a78d1598d.zip'
> -- SHA256 hash of
>     /home/madaos/dev/XNNPACK/build/cpuinfo-download/cpuinfo-prefix/src/5916273f79a21551890fd3d56fc5375a78d1598d.zip
**>   does not match expected value
>     expected: '2a160c527d3c58085ce260f34f9e2b161adc009b34186a2baf24e74376e89e6d'
>       actual: '873961f35200e59cba59416d57f58ad6b53531bfc30e4a55a1b4c9522ac6d02a'**
> -- Hash mismatch, removing...

### Steps to reproduce

```
git checkout master
mkdir build && cd build
cmake ..
```
### Probable root cause:

GitHub not guaranteeing the checksums to remain constant - as discussed for example [here](https://github.com/spack/spack/issues/5411) and later [here](https://github.com/abseil/federation-hello/issues/3).

### Proposed solution:
`ExternalProject_Add` configuration in the above mentioned `cmake/DownloadFP16.cmake` and `cmake/DownloadCpuinfo.cmake` files could be using just commit hashes for cloning the repository instead of downloading the repository archive and verifying its checksum.

**Comment by madaosik** [comment]
It seems the GitHub archive creation has been reverted, rendering the checksums to be consistent with the expected values defined in CMake configuration. Nonetheless, in order to prevent this situation in the future, it would be good to transition from archive/checksum dependency fetching mechanism to the specific revision related one. A pull request will follow.

**Comment by Maratyszcza** [comment]
Many XNNPACK dependencies are unversioned, and I don't think it is worth fixing.
