### ISSUE TITLE
Functionality/Examples to convert between NCHW and NHWC?

### ISSUE THREAD

**Issue by misterBart** [google/XNNPACK#2657]
Is there functionality/examples in Xnnpack to convert between NCHW and NHWC?
Our company currently supports NCHW only in their inference engine. To speed up the convolutions, I'm building an Xnnpack drop-in replacement. Hence my question.

**Comment by Maratyszcza** [comment]
There's no built-in functionality to convert between NCHW and NHWC (excepting mixed-layout operators for sparse inference).

**Comment by misterBart** [comment]
(1) Can it not be realized via channel stride? Or does that only skip channels? Instead of iterating circularly
(2) Is there no transpose operator in Xnnpack? I noticed transpose examples in folders test/ and bench/ but no transpose function in xnnpack.h

**Comment by misterBart** [comment]
Ok, thanks
