### ISSUE TITLE
Slight difference between how the output shape of conv and maxpool are computed

### ISSUE THREAD

**Issue by snnn** [google/XNNPACK#2904]
In convolution-nhwc.c, the compute_output_dimension uses doz, while in max-pooling-nhwc.c, the one for maxpool doesn't .
I think it makes a difference only when  effective_kernel_dimension - padded_input_dimension > subsampling_dimension  .  It seems TF doesn't handle it at all.

**Comment by Maratyszcza** [comment]
This was fixed & unified in bb3e3dd8f9c86e17576fe6b49d3ea2be7644fbe3
