### ISSUE TITLE
Failed to apply XNNPACK delegate

### ISSUE THREAD

**Issue by GitEasonXu** [google/XNNPACK#3060]
tensorflow version release 2.8.0
1. Build lite benchmark tool.
```
bazel build -c opt --config=android_arm64 --define tflite_with_xnnpack=true --define xnn_eable_qs8=true tensorflow/lite/tools/benchmark:benchmark_model

2.Post-training quantization
```python
convert = tf.lite.TFLiteConverter.from_keras_model(model)
convert.optimizations = [tf.lite.Optimize.EXPERIMENTAL_SPARSITY]
convert.representative_dataset = representative_dataset
tflite_quant_model = convert.convert()
```
```
I run this cmd is work `adb shell /data/local/tmp/benchmark/benchmark_model --graph=/data/local/tmp/benchmark/pruning_model.tflite --num_threads=1 --num_runs=1000`. but when I add this cmd with `--use_xnnpack=true` I get such error logs. 
```
STARTING!
Log parameter values verbosely: [0]
Graph: [pruning_model.tflite]
Use xnnpack: [1]
Loaded model pruning_model.tflite
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
XNNPACK delegate created.
Failed to apply XNNPACK delegate.
Benchmarking failed.
```

**Comment by Maratyszcza** [comment]
Build with `--define xnn_log_level=debug --copt=-DCLOG_LOG_TO_STDIO=1` to get detailed error log

**Comment by GitEasonXu** [comment]
I've recompiled the code, but I cannot get the detail of debug log.
```
# Rebuild benchmark tool
bazel build -c opt --config=android_arm64 --cpu=arm64-v8a --define tflite_with_xnnpack=true --define xnn_log_level=debug --copt=-DCLOG_LOG_TO_STDIO=1 tensorflow/lite/tools/benchmark:benchmark_model
# Run 
./benchmark_model --graph=origin_model_float.tflite --use_xnnpack=true
```
Still，just get this information.
```
STARTING!
Log parameter values verbosely: [0]
Graph: [origin_model_float.tflite]
Use xnnpack: [1]
Loaded model origin_model_float.tflite
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
XNNPACK delegate created.
Failed to apply XNNPACK delegate.
```
Do I have to convert the tensorflow model to fp16 format?

**Comment by GitEasonXu** [comment]
The error is due to my keras model include `ZeroPadding2D` and `GlobalAveragePooling2D` layers. [reference here](https://towardsdatascience.com/accelerating-tensorflow-lite-with-xnnpack-ece7dc8726d0)
