### ISSUE TITLE
CMakeLists.txt doesn't recognize Emscripten as a valid system name

### ISSUE THREAD

**Issue by skottmckay** [google/XNNPACK#3126]
Can 'Emscripten' be added to this list?

https://github.com/google/XNNPACK/blob/30886e4b018b2eaeb59cedc70dc5932b727c816a/CMakeLists.txt#L109

**Comment by Maratyszcza** [comment]
CMake build for Emscripten isn't supported (and there're many issues with Emscripten's CMake support that get in the way). Use Bazel for targeting Emscripten.
