### ISSUE TITLE
Is sparse inference supported for x64?

### ISSUE THREAD

**Issue by vvolhejn** [google/XNNPACK#3170]
Hi, I wanted to ask whether sparse inference as described [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/xnnpack/README.md#sparse-inference) and in the [Fast Sparse ConvNets](https://arxiv.org/pdf/1911.09723.pdf) paper would work on x64 as well. The paper only mentions ARM and WebAssembly, but I haven't managed to find out in the XNNPACK documentation whether these are the only instruction sets supported. Thanks!

**Comment by Maratyszcza** [comment]
Yes, but only for pre-AVX machines.
