### ISSUE TITLE
Slides link to 'The Indirect Convolution Algorithm' broken

### ISSUE THREAD

**Issue by reddragon** [google/XNNPACK#3185]
In the README.md, as per title.

**Comment by Maratyszcza** [comment]
Slides were hosted on the ECV 2019 workshop website: https://sites.google.com/view/ecv2019/presentations?authuser=0

Looks like they are gone now.

**Comment by Darshvino** [comment]
Hi @Maratyszcza,

Do we have a copy of the slides? or any diagrams to understand the indirect convolution better. Would be great if we can it.

Thanks

**Comment by ngzhian** [comment]
https://arxiv.org/abs/1907.02129
