### ISSUE TITLE
Apply Google style?

### ISSUE THREAD

**Issue by depthwise** [google/XNNPACK#32]
Since the author is at Google now, may I ask that `clang-format` is run over the code with Google settings? This is trival to do and it would significantly improve readability. I could send a PR if you'd like.

Thanks!

**Comment by Maratyszcza** [comment]
XNNPACK is closer to Google style than QNNPACK, but doesn't really follow Google style, e.g. lines are wrapped on 120 symbols rather than 80, headers have different order, and names of test cases in unit tests are in upper-case.
