### ISSUE TITLE
Issue when building iOS for arm64

### ISSUE THREAD

**Issue by xta0** [google/XNNPACK#323]
I'm running into an error when compiling asm files in `XNNPACK_AARCH64_ASM_MICROKERNEL_SRCS` for arm64

```shell
error: /Users/taox/Projects/XNNPACK/src/f32-dwconv/up4x9-aarch64-neonfma.S:21:23: error: error: unknown token in expression
error: brackets expression not supported on this target
brackets expression not supported on this target
        LD2R {v30.4s, v31.4s}, [x8]
        STP d10, d11, [sp, 16]
        STP d10, d11, [sp, 16]
```
Seems like the compiler doesn't recognize the syntax. I'm not an expert in ASM,  but my guess is that the compiler flag `-march=armv8.2-a+fp16` is not supported by Clang? However, I did find a link that discussed adding such support - https://reviews.llvm.org/D41792.

**Comment by Maratyszcza** [comment]
The file you mentioned doesn't use the `-march=armv8.2-a+fp16` flag, so it is something else.
Which version of XCode do you use? Do you see this error with other files?

**Comment by xta0** [comment]
yea, you're right, nothing to do with `-march=armv8.2-a+fp16`. Sorry for the confusion. I'm using XCode 11.3.1. Basically, all files in`XNNPACK_NEONFMA_MICROKERNEL_SRCS`can't be compiled on my machine. The errors are different, but mainly complain about the unknown assembly syntax.

**Comment by Maratyszcza** [comment]
The assembly snippets in LLVM test suite seems to use `#` (hash) before the offset in memory instructions: https://github.com/llvm/llvm-project/blob/364b8f5fbe0ac496931dcbd6f0493781f0677e82/llvm/test/MC/AArch64/basic-a64-instructions.s#L3016
Could you check if adding a hash (`LDP  d8,  d9, [sp], 64` -> `LDP  d8,  d9, [sp], #64`) helps?

**Comment by xta0** [comment]
@Maratyszcza I found the issue. It was a typo in CMakeLists.txt at [ line #1464](https://github.com/google/XNNPACK/blob/master/CMakeLists.txt#L1467). `XNNPACK_AARCH64_ASM_UKERNELS ` doesn't exist. Same for the armv7. Will open a PR .
