### ISSUE TITLE
support conv+add fusion?

### ISSUE THREAD

**Issue by fwz-fpga** [google/XNNPACK#3236]
Does xnnpack support convolution && add fusion? Network like this,  
![clipboard_image_1656597800536](https://user-images.githubusercontent.com/29475777/176697531-5b02ecfc-c78c-4553-8349-5ce51a1ad434.png)
Move left input of add to conv, and copy it to conv's output memory before conv inference, then do native conv.

**Comment by Maratyszcza** [comment]
This is currently not supported, but we're working on generic fusion capability using JIT code-generation.
