### ISSUE TITLE
About Convolution Implementation in XNNPACK

### ISSUE THREAD

**Issue by Darshvino** [google/XNNPACK#3306]
Hi @Maratyszcza,

I wanted to know in which way the convolution have been implemented in XNNPACK for FP32 and Int8 precision: GEMM-based, Direct conv, etc?

And would be great if you point me to the main implementation in the repo.

Thank you!

**Comment by Maratyszcza** [comment]
NHWC Convolution implementation follows [The Indirect Convolution Algorithm](https://arxiv.org/abs/1907.02129). The operator is implemented in `src/operators/convolution-nhwc.c`.

**Comment by Darshvino** [comment]
Thank you alot Marat for your kind response.
