### ISSUE TITLE
Understanding about the Gemm implementation

### ISSUE THREAD

**Issue by Darshvino** [google/XNNPACK#3333]
Hi @Maratyszcza,

Thank you a lot for the great work you had done.

I was having a few doubts related to int8 quantized kernels:

If you can see it here: https://github.com/google/XNNPACK/tree/master/src/qs8-gemm

If you consider this for example: **2x8c8-aarch64-neon-mull.S.in**

1.) My doubt is: what is **2x8** and **c8** means here?

2.) And also where is the im2col being called before calling to gemm function?

Look forward to your reply.

Thank you

**Comment by Darshvino** [comment]
Hi @Maratyszcza,

Look forward to your reply.

Thank you!

**Comment by ngzhian** [comment]
You can decipher the microkernel names here https://github.com/google/XNNPACK/blob/master/doc/microkernel-naming-conventions.md

in this case 2x8 is the mr and nr of the microkernel, it computes a 2x8 output matrix.

c8 means that we are doing partial sums, and outside the loop, add 8 values up (based on explanation by @fbarchard )

**Comment by xbwee1024** [comment]
「based on explanation by @fbarchard」
@ngzhian I cannot find this, did you mean the commits message by Frank? Thanks~
btw: xnnpack‘s doc is so weak :-(

**Comment by ngzhian** [comment]
> 「based on explanation by @fbarchard」 @ngzhian I cannot find this, did you mean the commits message by Frank? Thanks~ btw: xnnpack‘s doc is so weak :-(

No, i meant that:
"c8 means that we are doing partial sums, and outside the loop, add 8 values up" - this is an explanation by @fbarchard 

Yes we don't have very good documentation, this project has a small number of contributors, so a lot of information is just passed around directly. We are adding more documentation, see https://github.com/google/XNNPACK/tree/master/doc. Suggestions and contributions are welcome and appreciated!
