### ISSUE TITLE
Doubts regarding the XNNPACK Implementation

### ISSUE THREAD

**Issue by Darshvino** [google/XNNPACK#3398]
Hi XNNPACK team,

 I had a few queries on XNNPACK implementation. Below are my queries and it would be really great if you can assist me in understanding the queries:

1.) How are convolutions are being implemented in XNNPACK? Whether is it GEMM-based implementation or Direct Convolution?
2.) It seems that the XNNPACK's implementation is based on QNNPACK. So, whether there were any changes being made in kernel implementations(for ex: GEMM for ARM and X86)?

Would be really great if you can assist me with the above queries.

Look forward to your reply.

Thank you

**Comment by ngzhian** [comment]
Convolutions are implemented using  a few different microkernels, see https://github.com/google/XNNPACK/blob/master/src/operators/convolution-nhwc.c#L370-L381
There is GEMM based and also indirect convolution (https://arxiv.org/abs/1907.02129).

XNNPACK has probably diverged quite a bit from QNNPACK, but I don't think the differences in GEMM kernel implementations are drastically different.

**Comment by Darshvino** [comment]
Hi @ngzhian,

Thank you so much for your kind response Zhi. It means a lot.

I got a bit of clarity about the kernels in XNNPACK. Also, I had a few doubts based on your answer:

-> What is the difference between gemm and igemm? whether igemm is the indirect convolution? So, for indirect convolution implementation, we do not have im2col and for direct convolution, we have an im2col right?

-> Also, why do we have a separate folder called gen, what does the gen folder mean here: https://github.com/google/XNNPACK/tree/master/src/qu8-gemm ?


Thank you again for your kind response!

**Comment by ngzhian** [comment]
yes igemm is (i)ndirect gemm, using indirection buffers. for igemm, we do not have im2col.
For gemm we also do not have im2col, because we only use gemm when these condition holds
https://github.com/google/XNNPACK/blob/master/src/operators/convolution-nhwc.c#L377 (which means we don't need im2col.

the gen folder contains generated source which are generated from `.in` files using scripts in `scripts/' e.g. look at https://github.com/google/XNNPACK/blob/master/src/qu8-gemm/gen/1x16-minmax-fp32-neon-mlal-lane.c#L2 the comments indicate what is the template file that this was generated from.

**Comment by Darshvino** [comment]
Hi @ngzhian @Maratyszcza,

I had a small doubt on the performance of the GEMM kernels on the AVX2-supported X86 platform.

I was running benchmarks of MobilenetV1 layers and checking the performance of different GEMM kernels. I found that the performance difference between different kernels is quite significant. I am attaching the reference pic below:

![image](https://user-images.githubusercontent.com/41161376/189670987-9576e0eb-61d3-490f-b3f6-9659051da929.png)

My doubt here is why there is a significant performance difference between **1x8c8** vs **3x8c8** kernels. Why do some kernels perform well and some do not? on what factors the performance depends?

Another example is in below-attached image:

<img width="932" alt="image" src="https://user-images.githubusercontent.com/41161376/189671981-912198c1-6a21-4df6-a64f-3d936907fbf2.png">
(2x4c2 vs 4x4c2)


Look forward to your reply.


Thanks

**Comment by ngzhian** [comment]
We implement all kinds of kernels, but only a subset of them are used. The ones we selected are in init.c, e.g. https://github.com/google/XNNPACK/blob/master/src/init.c#L3880

**Comment by Darshvino** [comment]
Hmm, I See got it. 

But when I observed carefully, I found that a larger output tile gives a pretty good performance. I mean let's say in the below image attached, that the 3x8 kernel is better than the 1x8 kernel and so on for other Instruction sets as well. If that's the case then we would have had for larger size right(for example:4x8, 5x8, etc.)?

![image](https://user-images.githubusercontent.com/41161376/189716576-3513864c-5502-44fc-a781-efa64f09822c.png)

Thank you for your help.

**Comment by ngzhian** [comment]
Not necessarily, with large tiles, you might not have enough registers to do efficient blocking, so there will be register spilling. In this case, I'm not sure why we only went up to 3x8, the underlying templates supports up to MR=4, so we should probably generate and test it. https://github.com/google/XNNPACK/blob/master/src/qs8-gemm/MRx8c8-avx2.c.in#L9

**Comment by Darshvino** [comment]
Ohh I See got your point. Yeah, I would also assume that we should get an even better performance for MR=4. Btw how can we generate the kernel for MR = 4? I just want to generate and test the performance.

Thank you

**Comment by ngzhian** [comment]
A quick way to find out is to search for the template file name "MRx8c8-avx2.c.in", you should find the script that reads this template file and generates the kernel.
You should find https://github.com/google/XNNPACK/blob/master/scripts/generate-qs8-gemm.sh#L1285.
Modify it to add a line with MR=4, then run the script.

**Comment by Darshvino** [comment]
Hi @ngzhian,

I am trying to run the script: **scripts/generate-qs8-gemm.sh** , but I get the below error:

<img width="545" alt="image" src="https://user-images.githubusercontent.com/41161376/189733823-23edbaf4-1a63-4a65-8c98-d2a9d984e703.png">

**Comment by ngzhian** [comment]
Use python3

**Comment by Darshvino** [comment]
Yeah, I was able to generate the script for the 4x8 tile. I think I need to modify the bench/qu8-gemm.cc to add the lines for the 4x8 tile right? I mean for benchmarking.

**Comment by ngzhian** [comment]
Yup!

**Comment by Darshvino** [comment]
Hi @ngzhian,

I modified few scripts to make 4x8c8 kernel execute. Below is the benchmarking result:

<img width="948" alt="image" src="https://user-images.githubusercontent.com/41161376/189862619-ac45795f-85f9-44a8-8f7e-3352c303c17b.png">

It seems that 4x8 kernel is slightly better than 3x8(but not that significant difference which we can see between 1x8 vs 3x8 or 2x8 vs 3x8).

**Comment by ngzhian** [comment]
Agree that this looks good, maybe we can use this. We have multiple levels of benchmarking, can you also try adding 4x8c8 to https://github.com/google/XNNPACK/blob/master/bench/qu8-gemm-e2e.cc#L1055 and share the results?

**Comment by Darshvino** [comment]
Sure @ngzhian I will add 4x8c8 to **qu8-gemm-e2e** and share the results.

**Comment by Darshvino** [comment]
Hi @ngzhian @Maratyszcza,

I was benchmarking **qu8-gemm** arm kernels(https://github.com/google/XNNPACK/tree/master/src/qu8-gemm/gen) on raspi4. What I found is some of the kernels perform best and some do not. What is the reason behind that? Is it the mr, nr factors related to cache size and affecting the performance? how mr, nr, and other packing factors affect the performance?

Look forward to your reply.

Thank you!
