### ISSUE TITLE
Error while building XNNPACK on X86 CPU

### ISSUE THREAD

**Issue by Darshvino** [google/XNNPACK#3399]
Hi XNNPACK team,

I am trying to build XNNPACK on X86 CPU, when building QNNPACK on my X86 device, I am getting the below error:

**../../src/xnnpack/math.h:322:44: error: exponent has no digits
     return (uint32_t) double_as_uint64(x + 0x1.0p+52);**

Below is the GCC version I am using:

**gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0**

It would be helpful if I get a reply to resolve the above issue. 

Thanks

**Comment by ngzhian** [comment]
Should be fixed with https://github.com/google/XNNPACK/pull/3400, will try to land it soon.

**Comment by Darshvino** [comment]
Hi @ngzhian,

Thank you alot for your kind response. I have cloned the latest repo and started building on my machine, below is the error(in an image) I am getting:

<img width="949" alt="image" src="https://user-images.githubusercontent.com/41161376/187385354-205b4860-4094-43a3-8fa0-0102c210df4c.png">

Kindly help me to resolve this.

Thanks again Zhi

**Comment by ngzhian** [comment]
I don't see this locally, nor on CI.
what is the output of your `/usr/bin/c++ -v`?

**Comment by Darshvino** [comment]
Hi @ngzhian,

Ohh Ok. As asked please find the output of ` /usr/bin/c++ -v` below:

<img width="956" alt="image" src="https://user-images.githubusercontent.com/41161376/187499467-9f1fa106-ad5e-428a-9f9c-d49e18a36e30.png">

Thank you!

**Comment by ngzhian** [comment]
Any change you can try with a newer release of GCC?

**Comment by Darshvino** [comment]
Okay Sure, may I know the GGC version you are using and worked?

**Comment by ngzhian** [comment]
gcc 11.3.0

**Comment by Darshvino** [comment]
Okay, I will try with the same GCC version and build again. Thank you @ngzhian

**Comment by Darshvino** [comment]
Hi @ngzhian,

I was able to build successfully with GCC version 9.

Thank you!

**Comment by Darshvino** [comment]
Closing this issue, since resolved.
