### ISSUE TITLE
An error occurred when I was building the MediaPipe Android sample application in Ubuntu

### ISSUE THREAD

**Issue by gjn2659338105** [google/XNNPACK#3407]
I downloaded the SDK and NDK in Ubuntu and configured them according to the documents on the official website. However, an error occurred when I executed the command to generate the Android AAR file:

The **command** is:
chmod -R 755 mediapipe/
bazel build -c opt --fat_apk_cpu=arm64-v8a,armeabi-v7a \
//mediapipe/examples/android/src/java/com/google/mediapipe/apps/buid_aar:mediapipe_hand_tracking

And the **error** is:
external/XNNPACK/src/qu8-igemm/gen/1x8c4-minmax-rndnu-neondot.c:77:16: error:  assigning to 'uint32x2_t' (vector of 2 'uint32_t' values) from incompatible type 'int'
vnacc0 = vdot_u32(vnacc0, va_zero_point, va0x01234567);

**Comment by gjn2659338105** [comment]
![image](https://user-images.githubusercontent.com/109133657/187590332-a3ffdb8e-b46b-4561-ab26-82a100dc2009.png)

**Comment by gjn2659338105** [comment]
我上网查了一查，有人说是ndk版本的问题

I checked online and someone said it was the NDK version

My Ubuntu version is 20.04
My SDK version is 30.0.3
My NDK version is: Android-NDK-r18b

After that, I downloaded the NDK version of r21e and reconfigured it, but it was the same error. Does anyone know how to fix it?

**Comment by Maratyszcza** [comment]
`r18b` is too old. `r21e` should work, try to remove all build artifacts and reconfigure.

**Comment by gjn2659338105** [comment]
Which command can help me remove all build artifacts？

**Comment by gjn2659338105** [comment]
> `r18b` is too old. `r21e` should work, try to remove all build artifacts and reconfigure.

Thank you. It is indeed the NDK version. I downloaded R21E before, but forgot to change the path in the workspace, so R18B is still in operation.
Now I've solved the problem！！！
