### ISSUE TITLE
Building XNNPACK on Raspberry pi 3b+

### ISSUE THREAD

**Issue by Darshvino** [google/XNNPACK#3472]
Hi XNNPACK team,

Can I get a step to build XNNPACK on Raspberry pi 3b+? I am trying to build XNNPACK using **build-local.sh** script but I am facing the issue as in the below image: 
<img width="947" alt="image" src="https://user-images.githubusercontent.com/41161376/190240192-03c7874f-6842-44a4-be7d-41f5fe3ab020.png">

I am not sure whether the build-local.sh script has to be used. Kindly assist me to build on rpi3b+

Thanks

**Comment by ngzhian** [comment]
I don't think we test arm64 builds on raspberry pi, and build-script might not be working correctly there.
We do have android builds, using https://github.com/google/XNNPACK/blob/master/scripts/build-android-arm64.sh but even that is building to target android arm64, not building on an Android phone.

I think you might have to set some additional compile flags, like -march=armv7 or -mfpu flag.

**Comment by Darshvino** [comment]
Hi @ngzhian,

I tried modifying the CMakeList.txt script, but no luck :(. 

May I know how did you build the benchmark results mentioned in the Readme?

<img width="587" alt="image" src="https://user-images.githubusercontent.com/41161376/190265533-ff301a72-e0b6-46be-817c-df580a351dc6.png">

**Comment by Maratyszcza** [comment]
Use a newer version of gcc or clang.

**Comment by Darshvino** [comment]
Hi @Maratyszcza @ngzhian 

Thank you for your reply.

Based on your reply, I updated the gcc version from 8.3 to 10.2 that error is resolved, but I get another error as in the pic below:

<img width="931" alt="image" src="https://user-images.githubusercontent.com/41161376/190697594-bcdd4378-667d-440c-b879-f0316017bf94.png">

May I know for what reason the error is occuring? Is it still the version issue or any other?


Thank you

**Comment by Darshvino** [comment]
Hi @Maratyszcza,

I have added this to the build script: `-DXNNPACK_ENABLE_ARM_DOTPROD=OFF` and I did not get the error, but the build is getting stuck in between, not sure if it is because of the memory usage. May I know the reason for this? any trick to make it work? I think it would be common to build on these embedded boards.

Below is the stage where the build is getting stuck.
<img width="931" alt="image" src="https://user-images.githubusercontent.com/41161376/190916569-dd69535b-c81e-4279-8b72-3156d8e559bb.png">

**Comment by Maratyszcza** [comment]
Could be due to swapping into disk under high memory pressure. Try to build in single-threaded mode (`make` rather than `make -j4`).

**Comment by Darshvino** [comment]
Hi @Maratyszcza,

Yeah, you are right, it's because of the **less RAM** in rpi3b+ which is 1GB. So, if we are building with multiple threads it gets stuck in between during the build. So, we have to build with a single thread, but takes a bit long time.

On the other hand on rpi4, it builds successfully with 4 threads since the RAM is 4GB.

Thank you @Maratyszcza @ngzhian

**Comment by ngzhian** [comment]
Think you can update the script to specify the cmake target to build

`cmake --build builddir/ qu8-gemm` or something like this.

**Comment by Maratyszcza** [comment]
Or just change to the build directory and type `make qu8-gemm-minmax-fp32-test`

**Comment by Darshvino** [comment]
Hi @Maratyszcza 

I tried the following steps to build the XNNPACK only for qu8-gemm, but still all the files are building and the same time to build on rpi4

```
mkdir build
cmake ..
make qu8-gemm-minmax-fp32-test
```

I just want to build qu8-gemm files and execute them under the bench.

**Comment by Maratyszcza** [comment]
I regularly do it with Ninja and it works just fine. Try `cmake -G Ninja ..` and `ninja qu8-gemm-minmax-fp32-test`.

**Comment by Darshvino** [comment]
@Maratyszcza,

Thank you very much for your reply. I resolved all the issues and everything is working smoothly.

It just worked with `make qu8-gemm-bench` inorder to build just qu8-gemm scripts for benchmarking.

Thank you!
