### ISSUE TITLE
Delete subgraph

### ISSUE THREAD

**Issue by mcr229** [google/XNNPACK#3529]
https://github.com/google/XNNPACK/blob/master/src/subgraph.c#L1147-L1161

should subgraph->values and subgraph->nodes be guarded by nullptr checks?

In the case where xnn_delete_subgraph is used in a class destructor, and error is thrown before the nodes are defined, the clean up action fails because subgraph->nodes is null. Can we add a nullptr check here to ensure that we can clean this up properly?

**Comment by Maratyszcza** [comment]
`memset` is called with size of 0 and `xnn_release_memory` can handle `nullptr`, so it shouldn't lead to a crash or anything similarly bad. But it is indeed to good idea to check for `nullptr` there.

**Comment by Maratyszcza** [comment]
Done in 56b22d1aba18f2f3060b3dfe749fe624bb15454a
