### ISSUE TITLE
Error when build with CMake iOS

### ISSUE THREAD

**Issue by nguoithichkhampha** [google/XNNPACK#3565]
latest cmake require to set CMAKE_SYSTEM_NAME="iOS"
https://cmake.org/cmake/help/latest/variable/IOS.html
but in the CMake file of project does not allow this value
`IF(NOT CMAKE_SYSTEM_NAME)
  MESSAGE(FATAL_ERROR "CMAKE_SYSTEM_NAME not defined")
ELSEIF(NOT CMAKE_SYSTEM_NAME MATCHES "^(Darwin|Linux|Android|Windows|CYGWIN|MSYS|QURT)$")
  MESSAGE(FATAL_ERROR "Unrecognized CMAKE_SYSTEM_NAME = ${CMAKE_SYSTEM_NAME}")
ENDIF()`

**Comment by Maratyszcza** [comment]
Fixed in e0b58caf465907306de98a10fdc64ae24912548d
