### ISSUE TITLE
Compile error when compile on ARMv8-a processors

### ISSUE THREAD

**Issue by wpy1368064015** [google/XNNPACK#3618]
The cpuinfo version i utilize is the newest on github. However, the compile errors occur.
error: invalid feature modifier ‘bf16’ in ‘-march=armv8.2-a+bf16’
How can i solve this problem?

**Comment by ngzhian** [comment]
that error is from the compiler, not cpuinfo. Try using a newer version of clang/gcc?

**Comment by Maratyszcza** [comment]
You can disable BF16 instructions with `-DXNNPACK_ENABLE_ARM_FP16=OFF` CMake parameters.
