### ISSUE TITLE
 ios armv7 compile fail 

### ISSUE THREAD

**Issue by chenliang110** [google/XNNPACK#3905]
I compile ios armv7，can not compile ok.
armv7/xnnpack/src/qc8-dwconv/up8x3-minmax-fp32-aarch32-neonv8-mla8-cortex-a35.S:118:9: error: instruction requires: armv8
        VCVTN.S32.F32 q12, q12
the master also occur this problem 
Thank you very much

**Comment by Maratyszcza** [comment]
32-bit iOS is no longer supported.
