### ISSUE TITLE
Build issue on macOS arm64

### ISSUE THREAD

**Issue by adamjstewart** [google/XNNPACK#4023]
I'm seeing the following build error on Apple M1:
```
/var/folders/j1/68dlgpr91vlgs26vty2c8xk80000gn/T/ajstewart/spack-stage/spack-stage-xnnpack-master-ajgeikw6mniadpc5at4oduwr4k6zagft/spack-src/src/hardware-config.c:72:43: error: implicit declaration of function 'cpuinfo_has_arm_neon_bf16' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      hardware_config.use_arm_neon_bf16 = cpuinfo_has_arm_neon_bf16();
                                          ^
/var/folders/j1/68dlgpr91vlgs26vty2c8xk80000gn/T/ajstewart/spack-stage/spack-stage-xnnpack-master-ajgeikw6mniadpc5at4oduwr4k6zagft/spack-src/src/hardware-config.c:72:43: note: did you mean 'cpuinfo_has_arm_neon_fp16'?
/var/folders/j1/68dlgpr91vlgs26vty2c8xk80000gn/T/ajstewart/spack-stage/spack-stage-xnnpack-master-ajgeikw6mniadpc5at4oduwr4k6zagft/spack-src/deps/cpuinfo/include/cpuinfo.h:1652:20: note: 'cpuinfo_has_arm_neon_fp16' declared here
static inline bool cpuinfo_has_arm_neon_fp16(void) {
                   ^
1 error generated.
```
Full build log:
* [spack-build-out.txt](https://github.com/google/XNNPACK/files/10230231/spack-build-out.txt)

Any suggested fix for this?

**Comment by adamjstewart** [comment]
Note that this issue only exists when building with `-DXNNPACK_LIBRARY_TYPE:STRING=shared`, which is needed by PyTorch.

**Comment by Maratyszcza** [comment]
Are you building with CMake or Basel?

**Comment by adamjstewart** [comment]
CMake. The build log above contains the exact commands that were run to build the package.

**Comment by Maratyszcza** [comment]
You specify `cpuinfo` source directory via `CPUINFO_SOURCE_DIR`. Is it up-to-date?

**Comment by adamjstewart** [comment]
Probably not. Which version of cpuinfo is required? I couldn't find any version requirements documented for any dependencies...

My goal is to build these as dependencies of PyTorch, so I'm mostly sticking to the versions linked here: https://github.com/pytorch/pytorch/tree/master/third_party

**Comment by Maratyszcza** [comment]
https://github.com/google/XNNPACK/blob/master/cmake/DownloadCpuinfo.cmake lists the required revision

**Comment by adamjstewart** [comment]
Thanks, let me try that and get back to you

**Comment by adamjstewart** [comment]
This got me past this issue. Hit some other issues, but could be similar issues with deps that only work at a specific fork and commit. Will close this and open a new issue if I can't figure those out.
