### ISSUE TITLE
How to build XNNPACK for WebAssembly architecture

### ISSUE THREAD

**Issue by wenyongh** [google/XNNPACK#4094]
Hi, the document mentioned that XNNPACK supports architecture `WebAssembly MVP` and `WebAssembly SIMD`, but I cannot find the guide, is there any detailed instructions or document about it? Thanks.

**Comment by Maratyszcza** [comment]
Bazel build with WebAssembly toolchain should just work. See [TensorFlow.js WAsm backend README](https://github.com/tensorflow/tfjs/tree/master/tfjs-backend-wasm) for some documentation.
