### ISSUE TITLE
Out of bounds read when Tensor is not a multiple of the (e.g. AVX2) vector size

### ISSUE THREAD

**Issue by Flamefire** [google/XNNPACK#4190]
I noticed a test failure in a software using XNNPACK where I observed semi-random results.
It turned out to be a bug in GCC 11.1/11.2 shuffling the AVX2 vector elements erroneously but while debugging this I noticed an out-of-bounds read in `xnn_qs8_vaddc_minmax_ukernel__avx2_mul32_ld64_x16` which might also be present in similar kernels.

Here the OOB reads happens on AVX2 machines/code when the input tensor to the quantized operation (addition of 2 quantized tensors) is not a multiple of 8 bytes in size. This is trivially true for any tensor with less than 8 elements, in the particular case the Python hypothesis module reduced the tensor size to 1 element. But the same would happen with e.g. 9 elements as the bug exists in the handling of the remainder elements starting at https://github.com/google/XNNPACK/blob/76a376433f1944cef991c24c18b0c15127d749f8/src/amalgam/avx2.c#L5823

The code at https://github.com/google/XNNPACK/blob/76a376433f1944cef991c24c18b0c15127d749f8/src/amalgam/avx2.c#L5825 reads 8 bytes from the current value of the `input_a` pointer. Although the later code (on fixed versions of GCC, e.g. GCC 11.3) will only write results from valid memory to the output tensor the read is clearly OOB: The code at https://github.com/google/XNNPACK/blob/76a376433f1944cef991c24c18b0c15127d749f8/src/amalgam/avx2.c#L5841-L5856 handles the case of 1-7 remaining elements. So it is even expected that there are less than 8 elements and for e.g. single-value tensors this is the only code from this function executed so up to 7 bytes (in the case of tensors with 1 value or 8*n+1 value) are read from invalid memory.

Depending on the architecture this might not be a problem but it might also result in crashes and should likely be addressed.

**Comment by Maratyszcza** [comment]
XNNPACK operators can read up to `XNN_EXTRA_BYTES` elements beyond the end of the array. If you're using XNNPACK directly, you need to take care of it. If you use XNNPACK through e.g. TensorFlow Lite, the latter already takes care of it for you.
