### ISSUE TITLE
End to end model speedup results

### ISSUE THREAD

**Issue by Darshvino** [google/XNNPACK#4266]
Hi XNNPACK team,

Is there any way to directly get the end-to-end model speedup results instead of building the TFlite with XNNPACK? 

Basically, I just want to use the XNNPACK and get the model performance results. Also, I am curious to know about the numbers mentioned in the Readme https://github.com/google/XNNPACK#raspberry-pi for the end-to-model performance results, I mean did you build the TFlite with XNNPACK to get the model-level results or got directly from the XNNPACK?

It would be great if you can brief me about the procedure to benchmark the model for the performance results with the XNNPACK

Thanks

**Comment by Darshvino** [comment]
Hi @ngzhian @Maratyszcza,

Do we have any updates on the above?

Thanks!

**Comment by ngzhian** [comment]
Hi, you can run the benchmarks in https://github.com/google/XNNPACK/blob/master/bench/end2end.cc `bazel run :end2end_bench` to be MobileNet V1, V2, V3 for various data types.

**Comment by Darshvino** [comment]
Hi @ngzhian,

Thank you for your kind reply.

1.) What is the way to run the benchmarks on other models like(resnet, etc.)? 

2.) Also, I did not understand the model files in this folder: https://github.com/google/XNNPACK/tree/master/models, I mean if you take any scripts in that folder and look at this https://github.com/google/XNNPACK/blob/e2fd580527ff74af8436e6f058563dd782d4c50f/models/fp16-mobilenet-v1.cc#L24 it's not clear about the definition. Can you please give a brief description of the model script? It would really help to write other models to benchmark.

Thanks

**Comment by ngzhian** [comment]
That file is the entire MobileNetV1 model, expanded out to manually call XNNPack operators. That's what TFLite is doing when using XNNPack delegate.

If you don't want to use TFLite, you need to manually call XNNPack operators, that file shows how it is done. If you want to run resnet, you need to convert the model to call XNNPack operators. XNNPack does not have ability to read TFLite flatbuffers, that is done by TFLite.

I suggest you use TFLite: https://www.tensorflow.org/lite/performance/measurement with with `--use_xnnpack` as the argument.

**Comment by Darshvino** [comment]
Hi @ngzhian,

Thanks a lot for your kind reply.

I will use https://www.tensorflow.org/lite/performance/measurement for benchmarking. 

Also, I have one doubt regarding selecting the kernel while executing the model. If I want to execute the particular kernel(FP32 GEMM kernel with im2col) for executing the  conv kernel, then what needs to be modified inorder to execute that particular FP32 GEMM kernel(with im2col )for Conv op in the model?

Thanks

**Comment by ngzhian** [comment]
The convolution operator does not support im2col now, you likely have to manually modify https://github.com/google/XNNPACK/blob/master/src/operators/convolution-nhwc.c#L286 to add im2col support.

**Comment by Darshvino** [comment]
Ohh Okok got it Zhi. It would be a great help if you can assist in pointing out where exactly the indirection buffer formation is called and the GEMM kernel is called here: https://github.com/google/XNNPACK/blob/master/src/operators/convolution-nhwc.c#L286

Thanks

**Comment by ngzhian** [comment]
Indirection buffer is set up for IGEMM path here https://github.com/google/XNNPACK/blob/master/src/operators/convolution-nhwc.c#L1666-L1680
You will need similar code for the GEMM im2col.
GEMM microkernel is set here https://github.com/google/XNNPACK/blob/master/src/operators/convolution-nhwc.c#L1560-L1618 to be called later in operator-run.c.

**Comment by Darshvino** [comment]
Thanks a lot, Zhi for the detailed answer! I will start working on it!

**Comment by Darshvino** [comment]
Hi @ngzhian,

How can we run the kernel benchmarks using multiple threads? 

Suppose I am running: `qs8-gemm-bench` how can I run the kernel with 4 threads on raspberry pi?

Thanks!

**Comment by ngzhian** [comment]
Those benchmarks only run single threaded, you can modify the call to `xnn_create_runtime` to pass in a threadpool with multiple threads set: https://github.com/google/XNNPACK/blob/master/include/xnnpack.h#L1508

**Comment by Darshvino** [comment]
Hi @ngzhian,

Thanks a lot for your reply!.

Tbh, I did not clearly understand the above comment. Is there any possibility that you can explain in a bit of detail to run the kernel benchmarks with multi thread. 

I want to run this benchmark with multi-thread actually: https://github.com/google/XNNPACK/blob/master/bench/qu8-gemm.cc

Thanks

**Comment by ngzhian** [comment]
https://github.com/google/XNNPACK/blob/master/bench/qu8-gemm.cc does not support multithreading, those benchmark microkernels.
Multi-threading is supported at the operator level, e.g. here https://github.com/google/XNNPACK/blob/master/src/operators/convolution-nhwc.c#L1585.

You can try using this benchmark: https://github.com/google/XNNPACK/blob/master/bench/qu8-gemm-e2e.cc

then you will need to change https://github.com/google/XNNPACK/blob/master/bench/qu8-gemm-e2e.cc#L60, the `nullptr` on that line is the threadpool, create a proper threadpool (something like this https://github.com/google/XNNPACK/blob/master/bench/end2end.cc#L30, look at pthreadpool API to learn more).

Alternatively, you can run end2end_bench: https://github.com/google/XNNPACK/blob/master/BUILD.bazel#L7015 which has multithreaded benchmarks.

**Comment by Darshvino** [comment]
Hi @ngzhian,

Thank you again for your detailed reply. I will follow the links you shared.

But actually, I want to do the multithreaded benchmarks for micro-kernels. Is there any way that I can apply the thread pool for the micro-kernel and see the timings? I just need to benchmark the micro-kernel, not the full model, actually. Is there any way that you can suggest running the microkernel benchmarks with multiple threads?

Thanks

**Comment by ngzhian** [comment]
> I want to do the multithreaded benchmarks for micro-kernels.

There is no straightforward way to do it. You will have to replicate the logic in https://github.com/google/XNNPACK/blob/master/src/operators/convolution-nhwc.c#L1585 to do it.

If you want to compare just microkernels, there is no reason to do multi-threading. Run the microkernels that you are comparing with the same parameters  by picking 1 particular convolution in the network you're benchmarking (MR,NR,KR etc). Then use the qu8-gemm-e2e benchmarks to see how the performance is reflected at the multithreaded level.

You mentioned in https://github.com/google/XNNPACK/issues/4266#issuecomment-1423628640 that you want to benchmark an entire model, qu8-gemm-e2e is the way to do so.

**Comment by Darshvino** [comment]
Hi @ngzhian,

Thank you again for the detailed reply.

Actually, I have tweaked the uint8 kernel to implement the custom GEMM and I am doing the performance benchmark at both the kernel level(one layer) and model level. So, I was a bit curious to see the numbers for the custom kernel(one layer) with a single thread and 4 threads on rpi4 board.

 I think I will follow the method you suggested to add the thread pool here: https://github.com/google/XNNPACK/blob/master/bench/qu8-gemm-e2e.cc#L60

But what I was thinking is: to just put one layer in the model config and run the inference(./qu8-gemm-e2e-bench) with the thread pool in order to get the numbers for one layer with multi-threads right? 

Also, can we run the benchmark at the operator level which uses the custom kernel to use for the computation of that operator? 

Thanks

**Comment by ngzhian** [comment]
> But what I was thinking is: to just put one layer in the model config and run the inference(./qu8-gemm-e2e-bench) with the thread pool in order to get the numbers for one layer with multi-threads right?

that works yes

> Also, can we run the benchmark at the operator level which uses the custom kernel to use for the computation of that operator?

qu8-gemm-e2e-bench is the operator level benchmark, if you look at the model definition (https://github.com/google/XNNPACK/blob/4f2dc6081d2fdda6b37fb96ccbeb6dde25ec6538/models/qu8-mobilenet-v1.cc) it is all creating operator, set up operator.

**Comment by Darshvino** [comment]
Hi @ngzhian,

I was trying to trace the execution of the operator in XNNPACK. And found that at the end it was hitting this call: https://github.com/google/XNNPACK/blob/4f2dc6081d2fdda6b37fb96ccbeb6dde25ec6538/src/operator-run.c#L1518

I had a small doubt on how the micro-kernel(for ex:  any qu8gemm kernel) is getting linked with the above pthreadpool call?

I also found the reference in the pthreadpool repo while tracing the execution: https://github.com/Maratyszcza/pthreadpool/blob/43edadc654d6283b4b6e45ba09a853181ae8e850/include/pthreadpool.h#L300

Thanks.

**Comment by ngzhian** [comment]
https://github.com/google/XNNPACK/blob/master/src/operators/convolution-nhwc.c#L1582-L1618
sets a function pointer for pthreadpool to call

**Comment by Darshvino** [comment]
Thanks a lot @ngzhian!. 

Actually, I have defined a custom kernel with the name: **xnn_qu8_gemm_minmax_rndnu_ukernel_4x16__neon_mlal_lane_1**, I have added the declaration in gemm.h and microfnptr.h, and while I am running the micro-kernel benchmarks it runs perfectly fine and I get the timing numbers, but while running the operator benchmarks(qu8-gemm-e2e-bench) by adding the kernel name in the qu8-gemm-e2e.cc, it is not executing, I mean it is getting stuck here: https://github.com/google/XNNPACK/blob/4f2dc6081d2fdda6b37fb96ccbeb6dde25ec6538/src/operator-run.c#L1518

Not sure where exactly there is an issue. It would be really great if you can assist in resolving the issue Zhi.

Thanks

**Comment by ngzhian** [comment]
What do you mean "getting stuck"? any errors?

**Comment by Darshvino** [comment]
There are no errors. It just hangs. Something like in the below picture: while executing **qu8_gemm_4x16__neon_mlal_lane_1**

<img width="464" alt="image" src="https://user-images.githubusercontent.com/41161376/220774160-034a8247-1231-41d0-add8-332f8c4ee7a9.png">

Seems like the kernel is not properly set for executing the operator? But it is executing perfectly fine while running the micro-kernel benchmarks as I mentioned previously.

**Comment by ngzhian** [comment]
maybe drop into a debugger and see what's going on? Likely there is an error in the implementation when the operator calls it (e.g. not correctly decrementing coutners.)

**Comment by Darshvino** [comment]
Ohh Okok, but actually the kernel is not exactly getting executed, I mean the trace is not inside the kernel Zhi, but as I said previously, I am able to run the microkernel benchmarks correctly and the results are also correct, but not sure why there is an issue while running an operator, is there any link to init.c file?

**Comment by ngzhian** [comment]
> actually the kernel is not exactly getting executed, I mean the trace is not inside the kernel Zhi

If the kernel is not getting executed, then probably you're not specifying it in the benchmarks correctly.

It doesn't need to be in init.c
You might need to run https://github.com/google/XNNPACK/blob/master/tools/update-microkernels.py to make the microkernels get picked up, and maybe https://github.com/google/XNNPACK/blob/master/scripts/generate-amalgamation.sh

If you don't get a compile error is probably fine.

init.c file doesn't need to be changed

**Comment by Darshvino** [comment]
Hi @ngzhian,

Thank you!

I also strongly believe that the kernel is not getting picked up correctly.

I have an old commit of the repo(I think 4 months old), whether the **update-microkernels.py** can be used for the older commits as well? 

Also, If the kernels are getting picked up properly for micro-kernel benchmarks, how it can be the case it is not getting picked up for operator benchmarks?

Thanks

**Comment by ngzhian** [comment]
Not sure, if update-microkernels.py is there, then you can try it. otherwise sync your repo.

> Also, If the kernels are getting picked up properly for micro-kernel benchmarks, how it can be the case it is not getting picked up for operator benchmarks?

I'm not sure, could be a bug. You can trace an existing microkernel in the operator benchmarks, see where the microkernel file is listed, and make sure your new microkernel file is also added to the right places (e.g. CMakeLists.txt)

**Comment by Darshvino** [comment]
Hi @ngzhian,

I checked about the mentioning of kernel names in the different files and the kernel file in different places(eg. CMakeLists.txt), and it seems like everything looks good. But seems like there is an issue here: https://github.com/google/XNNPACK/blob/4f2dc6081d2fdda6b37fb96ccbeb6dde25ec6538/bench/qu8-gemm-e2e.cc#L50:~:text=xnn_params.qu8.gemm.,%5D%20%3D%20xnn_init_hmp_igemm_ukernel(xnn_igemm_ukernel_fn(igemm1))%3B??

because I am using `xnn_qu8_gemm_minmax_ukernel_function1` type for gemm and `xnn_qu8_gemm_minmax_ukernel_function` type for gemm1, do we have to use the same type for gemm and gemm1?

Not exactly sure whats happening here: https://github.com/google/XNNPACK/blob/4f2dc6081d2fdda6b37fb96ccbeb6dde25ec6538/bench/qu8-gemm-e2e.cc#L50:~:text=xnn_params.qu8.gemm.,%5D%20%3D%20xnn_init_hmp_igemm_ukernel(xnn_igemm_ukernel_fn(igemm1))%3B, seems like the kernel assignment for an operator is happening there?

**Comment by ngzhian** [comment]
`gemm1` and `gemm` have the same signature

Yup, that overwrites whatever is microkernel is set in `init.c` with what you specified in the benchmarks.

Operators by default get the microkernels from `xnn_params`, which is set here https://github.com/google/XNNPACK/blob/4f2dc6081d2fdda6b37fb96ccbeb6dde25ec6538/src/init.c#L526

Overwriting xnn_params allow you to benchmark a specific microkernel.

**Comment by Darshvino** [comment]
Thank you! @ngzhian, that is the possible reason why there is a bug. In my case, the signature is not the same for gemm and gemm1. 

For the correction:
I will keep the same signature for both gemm and gemm1 and also change correspondingly in init.c.

Thanks a lot Zhi!

But, is there any specific reason, why we need both gemm and gemm1 instead of just gemm?

**Comment by ngzhian** [comment]
gemm1 is specialized for mr = 1, in many cases you can have a more optimized microkernel. You don't have to implement it, you can pass your gemm as gemm1 (all gemms handle mr smaller than their mr tile.)

**Comment by Darshvino** [comment]
Thank you, Zhi! 

I did not completely get it Zhi, it would be great if you can explain a bit more clearly. My doubt was: If I implement my custom kernel with 4x16 tile, then I am not sure what is the use of 1x16 gemm. 

Also, is there any possibility that I just run **xnn_qu8_gemm_minmax_rndnu_ukernel_4x16__neon_mlal_lane** instead of all 4 here: https://github.com/google/XNNPACK/blob/master/bench/qu8-gemm-e2e.cc#:~:text=xnn_qu8_gemm_minmax_rndnu_ukernel_4x16__neon_mlal_lane%2C,xnn_qu8_igemm_minmax_rndnu_ukernel_1x16__neon_mlal_lane%2C like we have here: https://github.com/google/XNNPACK/blob/master/bench/qu8-gemm.cc#:~:text=xnn_qu8_gemm_minmax_rndnu_ukernel_4x16__neon_mlal_lane%2C

**Comment by ngzhian** [comment]
All gemm microkernels can handle "up to" the specified mr. E.g. xnn_qu8_gemm_minmax_rndnu_ukernel_4x16__neon_mlal_lane can handle mr == 1, 2, 3 or 4, though it is optimized for mr == 4.

So, you can change these 2 lines: https://github.com/google/XNNPACK/blob/master/bench/qu8-gemm-e2e.cc#L518-L519 to xnn_qu8_gemm_minmax_rndnu_ukernel_4x16__neon_mlal_lane and xnn_qu8_igemm_minmax_rndnu_ukernel_4x16__neon_mlal_lane (use the mr 4 microkernel as gemm1 and igemm1) and it should work.

I.e. you don't need to implement another microkernel to pass as gemm1, you can reuse your 4x16 kernel just for benchmarking purposes.

**Comment by Darshvino** [comment]
Hi @ngzhian,

Thanks a lot for all your responses!

I was able to solve and run the custom kernel via an operator layer. Currently, I am working on applying multi-threading to an operator. I am referring to your reply: https://github.com/google/XNNPACK/issues/4266#issuecomment-1433585981

Thanks a lot again Zhi!

**Comment by Darshvino** [comment]
Hi @ngzhian,

I tried to create a thread pool before this line: https://github.com/google/XNNPACK/blob/master/bench/qu8-gemm-e2e.cc#L60, something like this:

```
 const size_t num_threads = 4; 
 std::unique_ptr<pthreadpool, decltype(&pthreadpool_destroy)> threadpool(
 pthreadpool_create(num_threads), pthreadpool_destroy);

 auto execution_plan = model_factory(threadpool.get());

```

But it does not seem to be working Zhi, means there is no difference in the timing while passing nullptr and passing the threadpool.

**Comment by Darshvino** [comment]
Ohh I fixed it Zhi!

Just to pass the threadpool here: https://github.com/google/XNNPACK/blob/407bef64031c4a5977f67564d74f8a75d211f4b4/bench/qu8-gemm-e2e.cc#L68

**Comment by Darshvino** [comment]
Hi @ngzhian,

Hope you are doing well.

I had two doubts about the execution of the model:

1.) What is exactly happening in **create_convolution2d_nhwc()** and **setup_convolution2d_nhwc()** in the script convolution-nhwc.c? I think those were the main functions of the operator and microkernel interface, just wanted to know more about it.

2.) Where is the micro kernel selection is happening during the execution of an operator or a model? Like 
xnn_qu8_gemm_minmax_rndnu_ukernel_4x8__aarch32_neon_mlal_lane_prfm_cortex_a53 or xnn_qu8_gemm_minmax_rndnu_ukernel_4x8__aarch32_neon_mlal_lane_cortex_a7 etc.?

Thanks

**Comment by ngzhian** [comment]
1) you can read the source to find out https://github.com/google/XNNPACK/blob/master/src/operators/convolution-nhwc.c#L419 create does things like packing of weights, set does parallelization

2) we set the microkernels in https://github.com/google/XNNPACK/blob/master/src/init.c

**Comment by Darshvino** [comment]
Thanks a lot, @ngzhian.

I was able to create Doxygen call graphs for XNNPACK and trying to understand the execution calls.

**Comment by ngzhian** [comment]
you don't need any frontends to run end2end_bench.

TFLite is the most supported.

See https://github.com/google/XNNPACK/blob/master/scripts/build-android-arm64.sh for how we crosscompile XNNPack, I imagine TFLite will have something similar, otherwise it is a good question to ask TFLite.

**Comment by Darshvino** [comment]
We actually need a frontends to run a model right? like for ONNX, pytorch models, etc on X86?

**Comment by ngzhian** [comment]
What do you mean run a model? If you have a TFLite model file, then yes you need TFLite.
If you want to run an existing model like MobileNetV2, we already have it in end2end.h https://github.com/google/XNNPACK/blob/master/bench/end2end.h

We converted the model into direct calls to XNNPack API, so we don't need a model file at all. You need to build end2end_bench, and run it.

**Comment by Darshvino** [comment]
Yeah yeah exactly, I mean to run other models than we have in TFLITE(I think we have only for mobilnetv1,v2,v3) but I want to test for other models like resnet, and other models, so I think defining like this is cumbersome right: https://github.com/google/XNNPACK/blob/master/models/fp32-mobilenet-v1.cc. 

So I wanted to go for TFLITE with XNNPACK and build both on raspberry pi. So, while building I was facing issues wrt version compatibility and it was getting stuck sometimes due to less resources for the build on rpi4. So I planned to build XNNPACK with pytorch or ONNXRRT in order to use the XNNPACK kernels while running the Pytorch or ONNX models. 

Thanks.

**Comment by Darshvino** [comment]
Hi @ngzhian,

How you would suggest running the end2end models? Either with Tflite with XNNPACK or ONNXRT with XNNPACK or Pytorch with XNNPACK?

Thanks

**Comment by ngzhian** [comment]
TFLite with XNNPack

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/xnnpack/README.md

or https://blog.tensorflow.org/2020/07/accelerating-tensorflow-lite-xnnpack-integration.html search for "Try out XNNPACK with your TensorFlow Lite model"

**Comment by Darshvino** [comment]
Thanks a lot @ngzhian,

Would you suggest building on Raspberrypi or cross compile?

**Comment by ngzhian** [comment]
Whichever is easier for you to set up, I guess. There's probably no difference in the output.
I usually cross compile, because we have scripts to help do that (see scripts/).

**Comment by Darshvino** [comment]
Ohh okay got it.

I was reading this blog: and it mentions that XNNPACK is already available as part of TFLITE binaries: The XNNPACK backend is already included in pre-built TensorFlow Lite 2.3 binaries

"The XNNPACK backend is already included in pre-built TensorFlow Lite 2.3 binaries"

Is it easier to use XNNPACK with this?

**Comment by ngzhian** [comment]
That's only useful if you don't need to make modifications to XNNPack, but you are making modifications, so probably that doesn't work.

**Comment by Darshvino** [comment]
Ohhh! got it! Zhi. I completely got it.

**Comment by Darshvino** [comment]
Yeah, I mean the output of the whole convolution layer, not the kernel output since it only outputs for certain tile sizes (ex: 4x16). Not sure where exactly we get the whole convolution output? somewhere in the convolution-nhwc.c file?

**Comment by ngzhian** [comment]
https://github.com/google/XNNPACK/blob/master/src/operators/convolution-nhwc.c#L1551

**Comment by Darshvino** [comment]
Thanks a lot, @ngzhian, I completely get it now. Also, where is the actual kernel call with the loops happening(similar to like this: https://github.com/google/XNNPACK/blob/master/bench/f32-im2col-gemm.cc#L116:~:text=%7D-,for%20(uint32_t%20m%20%3D%200%3B%20m%20%3C%20output_size%3B%20m%20%2B%3D%20mr)%20%7B,%7D,-const%20uint64_t%20cpu_frequency)?

**Comment by ngzhian** [comment]
From operators/convolution-nhwc.c, look for the `setup_*` code, which for GEMM is in `setup_gemm` https://github.com/google/XNNPACK/blob/master/src/operators/convolution-nhwc.c#L1505, then look at where we set the context and compute task (https://github.com/google/XNNPACK/blob/master/src/operators/convolution-nhwc.c#L1582), then jump to the definition of the task in operator-run.c https://github.com/google/XNNPACK/blob/5fdc288846dac21e425cccf1b13b4b795a3b9744/src/operator-run.c#L1299 this calls context->ukernel, which is the microkernel that is set in `setup_gemm`.

**Comment by Darshvino** [comment]
Hi @ngzhian,

Thanks a lot for sharing the details. I am able to run the model with all the changes!!. 

Also, I had a small doubt: where do I access the output of the layer in the XNNPACK? I mean I need to get the output of the layer to do some changes. 

Thanks

**Comment by Darshvino** [comment]
Can I be able to access the output of the layer here?: https://github.com/google/XNNPACK/blob/415697db32e338163d79ce346e83e1be4a9fe2cc/src/operators/convolution-nhwc.c#L1730

**Comment by ngzhian** [comment]
Not there, the output is written after the functions in operator-run.c. You can add printf after https://github.com/google/XNNPACK/blob/415697db32e338163d79ce346e83e1be4a9fe2cc/src/operator-run.c#L343 or something, depends on which function runs.

**Comment by ngzhian** [comment]
> Ohh Okok, that is the only place where we can get the changed output after the execution? we will not able to get it in convolution-nhwc.c script?

Yes, convolution-nhwc.c is only setting up the pointers and parameters. We no longer do anything in the file once we get into operator-run.c.

**Comment by Darshvino** [comment]
Ohh Okok got it. So we will have an output getting changed operator-run.c? May I know where exactly we can get the changed output at first?

**Comment by Darshvino** [comment]
Thanks a lot Zhi!

**Comment by ngzhian** [comment]
https://github.com/google/XNNPACK/blob/2e92932898d7f0d8bab024c96e3e7c16526df5f7/src/runtime.c#L691

**Comment by Darshvino** [comment]
Ohh Okok got it Zhi! Thank you :)

**Comment by Darshvino** [comment]
Hi Zhi,

I was tracing the execution and found that the `xnn_compute_igemm()` and 'xnn_compute_gemm()` are called here: https://github.com/google/XNNPACK/blob/03e8ec1082b84768173c32f8a71005be70e23a24/src/operator-run.c#L1536

Can we get the output of the layer after this line: https://github.com/google/XNNPACK/blob/03e8ec1082b84768173c32f8a71005be70e23a24/src/operator-run.c#L1536?

Can I get the output here from op using op->output?

**Comment by ngzhian** [comment]
Yes :)

**Comment by Darshvino** [comment]
Thank you, Zhi!

**Comment by Darshvino** [comment]
This will be the best thread for tweaking the custom changes in XNNPACK!

I am closing this since I got all the clarifications. Thanks again for all your answers.

**Comment by Darshvino** [comment]
Hi @ngzhian,

Just wanted to check where the kernel selection is happening in the master branch? which was previously in init.c

**Comment by Darshvino** [comment]
found it in gemm-config.c, Thank you!

**Comment by ngzhian** [comment]
Any microkernels specified in gemm-config needs to be in src/amalgam/gen/neonfma.c, https://github.com/google/XNNPACK/blob/master/CMakeLists.txt#L387 so add the new file to https://github.com/google/XNNPACK/blob/master/BUILD.bazel#L826 and run https://github.com/google/XNNPACK/blob/master/scripts/generate-amalgamation.sh
you might need to modify https://github.com/google/XNNPACK/blob/master/tools/amalgamate-microkernels.py to make the generate-amalgamation.sh script work.

Alternatively, copy paste the contents of https://github.com/google/XNNPACK/blob/master/src/f32-igemm/gen/f32-igemm-4x8-minmax-aarch64-neonfma-lane-ld128.c to src/amalgam/gen/neonfma.c.

**Comment by Darshvino** [comment]
Ohh Okok got it.

Is it enough if I just copy paste the contents of https://github.com/google/XNNPACK/blob/master/src/f32-igemm/gen/f32-igemm-4x8-minmax-aarch64-neonfma-lane-ld128.c to src/amalgam/gen/neonfma.c.? or are there any extra steps?

**Comment by ngzhian** [comment]
With 81212bb624cdfb2d5ffc0845f1c818bbd8234509
you should be able to modify the BUILD.bazel file and run generate-amalgamation.sh.

**Comment by Darshvino** [comment]
Hi @ngzhian,

May I kow were exactly the output of an operator which is updated here(https://github.com/google/XNNPACK/blob/6bde95ae35196822c4667f50dcf2cd7c63de178a/src/operator-run.c#L1553) will be transferred to the next op?

Atually I want to add an additional output(named output1 or something) in this structure and want to pass that to the next op as an input.

**Comment by ngzhian** [comment]
It is not "transferred", the next op has input pointer set to the output pointer of that op.
https://github.com/google/XNNPACK/blob/master/include/xnnpack.h#L1883
You set the the pointers appropriately.

**Comment by Darshvino** [comment]
Where de we exactly set the pointers Zhi? I mean where do we set the current output to the next input?

**Comment by ngzhian** [comment]
Are you using subgraph or operator?
If using subgraph, then we have a whole memory-planning phase (see memory-planner.c), that allocates tensors to specific offsets in the workspace (https://github.com/google/XNNPACK/blob/master/src/runtime.c#L152).

Imagine Op1 -> Tensor1 -> Op2

Tensor1 is allocated some space (tensor1.data is a pointer to that space)
and we set op1->output to tensor1.data, and op2.input to tensor1.data

https://github.com/google/XNNPACK/blob/master/src/subgraph/convolution-2d.c#L304

**Comment by Darshvino** [comment]
Ohhh Thanks a lot Zhi!

I am using the operator. 

Just wanted to check if I get the output of the op here https://github.com/google/XNNPACK/blob/6bde95ae35196822c4667f50dcf2cd7c63de178a/src/operator-run.c#L1553 in op->output?

**Comment by ngzhian** [comment]
Yup, op->output should work,
otherwise use `context->c`, depending on which task is run https://github.com/google/XNNPACK/blob/6bde95ae35196822c4667f50dcf2cd7c63de178a/src/operator-run.c#L1406

**Comment by Darshvino** [comment]
Ohh Okok got it. Do you anywhere allocate the memory for output? Is there any way that I can create the output1 in this structure: https://github.com/google/XNNPACK/blob/6bde95ae35196822c4667f50dcf2cd7c63de178a/src/xnnpack/operator.h#L131 and allocate the memory for that pointer?

**Comment by ngzhian** [comment]
See here: https://github.com/google/XNNPACK/blob/master/models/fp32-mobilenet-v2.cc
all the tensors are allocated using std::array, and you set pointers accordingly.
