### ISSUE TITLE
Attempting to run unsuccesfully setup operators

### ISSUE THREAD

**Issue by JoshPPrieto** [google/XNNPACK#4318]
Hi all,

When I'm trying to run an inference on a tflite model that contains split operators (e.g.: yolo_v4-tiny) using Tensorflow Lite with XNNPACK enabled, I get the following error: 

`Error in XNNPACK: failed to run operator: operator was not successfully setup`

It might be a model issue, but after digging a little bit on the cause, I have some questions regarding the behavior of `xnn_setup_runtime` and `xnn_invoke_runtime` functions in src/runtime.c.

To my understanding, `xnn_setup_runtime` will call the `setup` function of each operator only if the member `operator_objects[0]` is not null:

```c
enum xnn_status xnn_setup_runtime( /* ... */ )
{
   /* ... */

  for (size_t i = 0; i < runtime->num_ops; i++) {
    const struct xnn_operator_data* opdata = &runtime->opdata[i];
    if (opdata->operator_objects[0] == NULL) {
      // Operator was removed during optimization
      continue;
    }

   /* ... */

    assert(opdata->setup != NULL);
    const enum xnn_status status = opdata->setup(opdata, runtime->blobs, runtime->num_blobs, runtime->threadpool);
    
   /* ... */
}
```

But, in `xnn_invoke_runtime` the checks continue for more `operator_objects`:

```c
enum xnn_status xnn_invoke_runtime( /* ... */ )
{
  /* ... */

  for (size_t i = 0; i < runtime->num_ops; i++) {
    for (size_t j = 0; j < XNN_MAX_OPERATOR_OBJECTS; j++) {
      if (runtime->opdata[i].operator_objects[j] == NULL) {
        // Operator was removed after fusion
        continue;
      }

      const enum xnn_status status = xnn_run_operator_with_index(runtime->opdata[i].operator_objects[j], i, j, runtime->threadpool);  
  
      /* ... */
}
```

In my case, for the split operation, `runtime->opdata[i].operator_objects[0]` is null (operator not set) , but `runtime->opdata[i].operator_objects[1]` is not null, which tries to run the operator without being set, and thus, the error.

So far I tried to patch it by changing the `continue` in `xnn_invoke_runtime` to a `break`, and it works for my models. The reasoning was that:
- The intended behavior is the one described in `xnn_setup_runtime` (setup only if `operator_objects[0]` is not null, as there should not be operators with a null `operator_objects[0]` and non-null `operator_objects[j]` where j > 0)
- [This commit](https://github.com/google/XNNPACK/commit/f3e24a5b07b9637e86ffd4d523c36dc99debc676) gave me some clues on why having multiple `operator_objects` and the relation to split/concatenate operators.

I can try to raise a PR with this change (and check how this affect to the profiling and delete functions) but I wanted to get some feedback before, as I might be missing something important.

Thanks and best regards,

**Comment by ngzhian** [comment]
Can you share reproduction instructions? This could be bug somewhere else.

In general, the optimization is performed at the node/subgraph level, so an entire split/concatenate should be removed (so all the associated operators should be removed all together).

In your case it looks like you have a split that resulted in 2 operators, and operator_objects[0] was somehow optimized away, but operator_objects[1] was left alone, causing this problem.

**Comment by JoshPPrieto** [comment]
Thanks for the comment. 

It should be reproducible in Tensorflow lite (v2.9 or 2.10) using the [`benchmark_model` util](https://www.tensorflow.org/lite/performance/measurement#download_or_build_the_binary) with xnnpack enabled. I'm reproducing it in x86 and aarch64 machines.

`./linux_x86-64_benchmark_model --graph=yolo_v4-tiny_float.tflite --use_xnnpack=true --verbose=1 --num_runs=5`

Note: in the model, the 8th op (first split and cause of the error) 'uses' only one of the branches. This might be related?

[yolo_v4-tiny_float.zip](https://github.com/google/XNNPACK/files/10803401/yolo_v4-tiny_float.zip)

**Comment by ngzhian** [comment]
Thanks for the reproduction instructions. Interesting to see a node drop off half of the channels... I can reproduce the failure, I would like to understand it a bit more, and come up with a regression test case and a fix. Will keep you posted.

**Comment by ngzhian** [comment]
https://github.com/google/XNNPACK/blob/master/src/subgraph/even-split.c#L44

**Comment by ngzhian** [comment]
Btw:
> In my case, for the split operation, runtime->opdata[i].operator_objects[0] is null (operator not set) , but runtime-> opdata[i].operator_objects[1] is not null, which tries to run the operator without being set, and thus, the error.

> So far I tried to patch it by changing the continue in xnn_invoke_runtime to a break, and it works for my models. The reasoning was that:

wont' that lead to wrong result?
because we are skipping the setup of opdata[i].operator_objects[1], so it won't run. Changing it to a break means we won't have a chance to run the split.
