### ISSUE TITLE
How to parallelize the indirect convolution with specific number of threads? 

### ISSUE THREAD

**Issue by wpy1368064015** [google/XNNPACK#4353]
std::vector<float> input(batch_size * input_height * input_width * input_pixel_stride + XNN_EXTRA_BYTES / sizeof(float));
  std::generate(input.begin(), input.end(), std::ref(f32rng));
  std::vector<float> kernel(groups * group_output_channels * kernel_height * kernel_width * group_input_channels);
  std::generate(kernel.begin(), kernel.end(), std::ref(f32rng));
  std::vector<float> bias(groups * group_output_channels);
  std::generate(bias.begin(), bias.end(), std::ref(f32rng));
  const size_t output_elements = batch_size * output_height * output_width * output_pixel_stride;

  xnn_status status = xnn_initialize(nullptr /* allocator */);
  if (status != xnn_status_success) {
    state.SkipWithError("failed to initialize XNNPACK");
    return;
  }

  const size_t num_buffers = 1 +
    benchmark::utils::DivideRoundUp<size_t>(benchmark::utils::GetMaxCacheSize(),
      sizeof(float) * (kernel.size() + bias.size() + output_elements));
  std::vector<float> output(output_elements * num_buffers);

  std::vector<xnn_operator_t> convolution_operators(num_buffers);
  for (xnn_operator_t& convolution_op : convolution_operators) {
    status = xnn_create_convolution2d_nhwc_f32(
      padding_top, padding_right, padding_bottom, padding_left,
      kernel_height, kernel_width,
      subsampling, subsampling,
      dilation, dilation,
      groups, group_input_channels, group_output_channels,
      input_pixel_stride, output_pixel_stride,
      kernel.data(), bias.data(),
      -std::numeric_limits<float>::infinity(), +std::numeric_limits<float>::infinity(),
      0 /* flags */, NULL, &convolution_op);
    if (status != xnn_status_success) {
      state.SkipWithError("failed to create FP32 Convolution operator");
      return;
    }
  }

  for (size_t i = 0; i < convolution_operators.size(); i++) {
    status = xnn_setup_convolution2d_nhwc_f32(
      convolution_operators[i],
      batch_size, input_height, input_width,
      input.data(), output.data() + i * output_elements,
      nullptr /* thread pool */);
    if (status != xnn_status_success) {
      state.SkipWithError("failed to setup FP32 Convolution operator");
      return;
    }
  }

  size_t buffer_index = 0;
  for (auto _ : state) {
    state.PauseTiming();
    benchmark::utils::PrefetchToL1(input.data(), input.size() * sizeof(float));
    buffer_index = (buffer_index + 1) % num_buffers;
    state.ResumeTiming();

    status = xnn_run_operator(convolution_operators[buffer_index], nullptr /* thread pool */);
    if (status != xnn_status_success) {
      state.SkipWithError("failed to run FP32 Convolution operator");
      return;
    }
  }

This code section is selected from bench\convolution.cc, I wonder how to modify the source code to parallelize the indirect convolution with specific number of threads and  capture the runtime?

**Comment by ngzhian** [comment]
You need logic like this: https://github.com/google/XNNPACK/blob/master/src/operators/convolution-nhwc.c#L1582-L1619

**Comment by Maratyszcza** [comment]
Instead of passing `nullptr /* thread pool */` in `xnn_setup_convolution2d_nhwc_f32` and `xnn_run_operator`, create a `pthreadpool_t` object with the required number of threads and pass it as the `threadpool` argument.

**Comment by wpy1368064015** [comment]
Thanks for your careful reply! I wonder whether the timing pseudo-code below is correct to evaluate the parallel performance of indirect convolution?


//creat N threads to calculate N batch simultaneously&nbsp;
pthreadpool_t threadpool= pthreadpool_create(N);


start = time();
xnn_initialize(NULL);
xnn_operator_t convolution_op = NULL;

xnn_create_convolution2d_nhwc_f32(&amp;convolution_op);
// parallelize N batch with N threads
xnn_setup_convolution2d_nhwc_f32(convolution_op, N, threadpool);
xnn_run_operator(convolution_op, threadpool);

end = time();


cost = end - start;


pthreadpool_destroy(threadpool);


wangpengyu
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "google/XNNPACK"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月1日(星期三) 凌晨1:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [google/XNNPACK] How to parallelize the indirect convolution with specific number of threads?  (Issue #4353)





 
Instead of passing nullptr /* thread pool */ in xnn_setup_convolution2d_nhwc_f32 and xnn_run_operator, create a pthreadpool_t object with the required number of threads and pass it as the threadpool argument.

**Comment by wpy1368064015** [comment]
Thanks for your careful reply! I wonder whether the timing pseudo-code below is correct to evaluate the parallel performance of indirect convolution?


//creat N threads to calculate N batch simultaneously&nbsp;
pthreadpool_t threadpool= pthreadpool_create(N);


start = time();
xnn_initialize(NULL);
xnn_operator_t convolution_op = NULL;

xnn_create_convolution2d_nhwc_f32(&amp;convolution_op);
// parallelize N batch with N threads
xnn_setup_convolution2d_nhwc_f32(convolution_op, N, threadpool);
xnn_run_operator(convolution_op, threadpool);

end = time();


cost = end - start;


pthreadpool_destroy(threadpool);



wangpengyu
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "google/XNNPACK"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月1日(星期三) 凌晨0:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [google/XNNPACK] How to parallelize the indirect convolution with specific number of threads?  (Issue #4353)





 
You need logic like this: https://github.com/google/XNNPACK/blob/master/src/operators/convolution-nhwc.c#L1582-L1619

**Comment by Maratyszcza** [comment]
Looks about right

**Comment by Darshvino** [comment]
This worked for me:

```
 const size_t num_threads = 4; 
 std::unique_ptr<pthreadpool, decltype(&pthreadpool_destroy)> threadpool(
 pthreadpool_create(num_threads), pthreadpool_destroy);

```

and replace null with threadpool
