### ISSUE TITLE
Issues about the filter layout when running

### ISSUE THREAD

**Issue by wpy1368064015** [google/XNNPACK#4362]
size_t buffer_index = 0;
  for (auto _ : state) {
    state.PauseTiming();
    benchmark::utils::PrefetchToL1(input.data(), input.size() * sizeof(float));
    buffer_index = (buffer_index + 1) % num_buffers;
    state.ResumeTiming();

    status = xnn_run_operator(convolution_operators[buffer_index], nullptr /* thread pool */);
    if (status != xnn_status_success) {
      state.SkipWithError("failed to run FP32 Convolution operator");
      return;
    }
  }

This code section is selected from bench\convolution.cc, I wonder whether the indirect convolution utilized transformed filter layout or initial KRSC layout? Look forward to and appreciate your reply!

**Comment by Maratyszcza** [comment]
Convolution operator always repacks filter into the layout optimal for the microkernel.
