### ISSUE TITLE
[question] Handling NaN for min/max instruction

### ISSUE THREAD

**Issue by syoyo** [google/XNNPACK#441]
What is the design policy of handling NaN for min/max instruction in XNNPACK?
 
vminq_f32/vmaxq_f32 : Not IEEE754-2008 aware(NaN propagates when either input is NaN)  http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0802b/CIHDEEBE.html

vminnmq_f32/vmaxnmq_f32 : IEEE754-2008 aware(= matches with SSE2's min/max) http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0802b/CIHFCJCF.html
(available only in ARMv8(or AARCH64))

SSE2 _mm_min_ps/_mm_max_ps : IEEE754-2008 aware
https://www.felixcloutier.com/x86/maxps

Currently, XNNPACK uses VMIN/VMAX for min/max instruction, thus at least there is an inconsistency between ARM and x86 code paths when handling NaN value.

Related:

Implement NaN-propagating max/min on Vec256
https://github.com/pytorch/pytorch/pull/13399

**Comment by Maratyszcza** [comment]
XNNPACK provides no guarantees about NaN handling in min/max operations.

SSE `_mm_min_ps` implements `a > b ? a : b` operation, so it match neither `vminq_f32` nor `vminnmq_f32` on ARM, and making min/max consistent across x86 and ARM would be expensive.

**Comment by syoyo** [comment]
> XNNPACK provides no guarantees about NaN handling in min/max operations.

Thanks!

> SSE _mm_min_ps implements a > b ? a : b operation, so it match neither vminq_f32 nor vminnmq_f32 on ARM,

No, `_mm_min_ps` matches with `vminnmq_f32`.

**Comment by tavianator** [comment]
> No, `_mm_min_ps` matches with `vminnmq_f32`.

No it doesn't.  `_mm_min_ps(NaN, 0.0) = 0.0`, but `_mm_min_ps(0.0, NaN) "=" NaN`, since it literally implements `a < b ? a : b` and all comparisons with NaN are false.
