### ISSUE TITLE
configurable attribute "deps" in @XNNPACK//:amalgam_microkernels when build iOS armv7

### ISSUE THREAD

**Issue by sukdamrong** [google/XNNPACK#4598]
This command

bazel build   --ios_minimum_os='10.0' --config=ios_armv7 -c opt --cxxopt=--std=c++17  //tensorflow/lite/ios:TensorFlowLiteC_framework

Error

onfigurable attribute "deps" in @XNNPACK//:amalgam_microkernels doesn't match this configuration. Would a default condition help?

Conditions checked:
 @XNNPACK//:aarch32
 @XNNPACK//:aarch64
 @XNNPACK//:x86
 @XNNPACK//:emscripten_wasm
 @XNNPACK//:emscripten_wasmsimd
 @XNNPACK//:emscripten_wasmrelaxedsimd
 @XNNPACK//:riscv

**Comment by Maratyszcza** [comment]
32-bit builds are no longer supported for iOS.
