### ISSUE TITLE
TFLITE with XNNPACK Int8 layer execution

### ISSUE THREAD

**Issue by Darshvino** [google/XNNPACK#4666]
Hi @Maratyszcza @ngzhian,

I had build the Tflite with XNNPACK with the minimal build https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/examples/minimal

When I am trying to execute the models: only the layers from FP32 TFLITE model are getting delegated to XNNPACK, but not the layers from the INT8 model. Do I have to use any flag during the build to make it enable?

Thanks

**Comment by ngzhian** [comment]
Try this: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/xnnpack/README.md#quantized-operators

**Comment by Darshvino** [comment]
Hi Zhi,

Thank you for sharing the link!

Do we have any similar flag for Cmake? It refers only to the Bazel builds

**Comment by ngzhian** [comment]
Try building with `-DXNNPACK_DELEGATE_ENABLE_QS8=1`.

**Comment by Darshvino** [comment]
Hi Zhi,

I tried to build with this: `cmake -DXNNPACK_DELEGATE_ENABLE_QS8=1 -DXNNPACK_DELEGATE_ENABLE_QU8=1 ../tensorflow_src/tensorflow/lite/examples/minimal`

After this also the layers are not getting delegated to XNNPACK.

Also, we do not have `XNNPACK_DELEGATE_ENABLE_QS8` or `DXNNPACK_DELEGATE_ENABLE_QU8` options here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/CMakeLists.txt

**Comment by ngzhian** [comment]
It's not a CMake flag, it's a macro definition, see https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/xnnpack/xnnpack_delegate.cc#L6288
you can also hack the source to force enable it by default.

**Comment by Darshvino** [comment]
Hi @ngzhian,

Thank you for your answer. I had done a bit hack in **xnnpack_delegate.cc** and **interpreter_builder.cc** inorder to build for int8 inference. Thanks a lot!

**Comment by Darshvino** [comment]
Hi Zhi,

Is there any possible way that I ran the INT8 model using only uint8 kernels?? Let's say I have a normal int8 quantised TFLITE 
 model, I want to use uint8 kernel(https://github.com/google/XNNPACK/blob/master/src/qu8-igemm/gen/qu8-igemm-4x16-minmax-rndnu-neon-mlal-lane.c) to run that, may I know where I can change in order to execute it with the uint8 kernel?

Thanks

**Comment by Darshvino** [comment]
Hi Zhi,

As you mentioned, I changed the kernel to the kernel I want in gemm-config.c and it was working Zhi. Thanks a lot. 

I changed under the QC8 part(from QC8 kernel to QU8 kernel).

**Comment by Darshvino** [comment]
Hi @ngzhian @Maratyszcza,

I had one doubt considering the below 2 points:

1.) I built the TFLite with XNNPACK with a minimal build on Rpi4b (Aarch64): https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/examples/minimal.

2.) I installed `tflite_runtime `via pip on the same machine and it uses the XNNPACK backend(it shows: `INFO: Created TensorFlow Lite XNNPACK delegate for CPU`).

I tested running a resnet18 model using both of the above. But tflite_runtime installed via pip gives the better performance then the minimal build. It is bit strange that even though in both cases the XNNPACK backend is being used but there is a difference in the timings.

Timings:
1.) Minimal build(from source): 106 ms
2.) tflite_runtime pip installed: 86 ms

Model: Resnet18 INT quantized model.

Can you please help me to get the reason for the same?

Thanks

**Comment by ngzhian** [comment]
are you building with optimizations enabled?
you can try to get a performance profile to see if the expected code is running.

**Comment by Darshvino** [comment]
Hi Zhi,

Thank you for your reply.

I did not enable any optimizations.
 
I am building with the below commands:

```
git clone https://github.com/tensorflow/tensorflow.git tensorflow_src
mkdir minimal_build
cd minimal_build
cmake -DTFLITE_ENABLE_XNNPACK=ON ../tensorflow_src/tensorflow/lite/examples/minimal
make install

```

What are the optimizations that need to be enabled and where do we have to enable them?

**Comment by ngzhian** [comment]
That's probably right, i think cmake builds release by default.
Maybe you can run with profiles to see if they look similar.

**Comment by Darshvino** [comment]
Yeah yeah I also thought the same Zhi, and I verified that the build is release.

May I know how can I run with profiles??

**Comment by Darshvino** [comment]
I also checked for FP32 Zhi, it is the same. The tflite_runtime via pip will give a better performance than the minimal build from source.

**Comment by ngzhian** [comment]
try linux perf tools
like https://forums.raspberrypi.com/viewtopic.php?t=287847

**Comment by Darshvino** [comment]
Thank you Zhi! I will try to profile using the above tool and see the reason.

**Comment by Darshvino** [comment]
Hi @ngzhian @Maratyszcza,

I was looking at this: https://github.com/google/XNNPACK/blob/ef20d087c4ae47b190c3538d727a52d52e4f1896/src/operators/convolution-nhwc.c#L596

And found that for config KS=1 and stride !=1 and padding = 0, the layer gets mapped to IGEMM instead of GEMM? What is the possible reason for it? It's just that for condition KS = 1, it has to go for GEMM right? 

It would be great if you can give a possible reason for the above doubt.

Thanks

**Comment by Darshvino** [comment]
Hi @ngzhian @Maratyszcza,

Did you have the chance to look at the above comment?

Thanks

**Comment by ngzhian** [comment]
I think our GEMM microkernels doesn't support non-1 stride/subsampling.

**Comment by Darshvino** [comment]
Yeah yeah I also realized that it should go for IGEMM for KS=1 with stride = 2.

**Comment by Darshvino** [comment]
Hi Zhi,

Just wanted to check if the setup_convolution() part is executing on runtime or compile time? how can we verify that? I mean this setup: https://github.com/google/XNNPACK/blob/379bda63c77678d98946cb81c9d3870a9c0b05f5/src/operators/convolution-nhwc.c#L1671

**Comment by ngzhian** [comment]
`runtime or compile time` don't understand what do you mean. It is called at "setup" time, which happens before inference.

If might be helpful for you to run under a debugger, add a breakpoint at the function `setup_igemm` and see when you hit the breakpoint.

**Comment by Darshvino** [comment]
I mean I just wanted to know whether the setup is being executed during the inference time? I mean if I am running a model and timing it, does the execution time also includes the time for setting up the convolution or not? 

I am just asking because I am having a custom preprocessing done here: https://github.com/google/XNNPACK/blob/379bda63c77678d98946cb81c9d3870a9c0b05f5/src/operators/convolution-nhwc.c#L1671 just wanted to know if that processing time is part of the total execution time of the model.

**Comment by ngzhian** [comment]
Setup is called every time your input/output pointers change. So if in your benchmark, you keep changing input and output pointers, then yes.
It all depends on how you set up your benchmark. I don't know exactly what you have changed.

I suggest you jump into a debugger and verify that what is running is as you expect.

**Comment by Darshvino** [comment]
Ohh Okok thank you! I get it. The setup should actually include the total execution time of the model.

**Comment by Darshvino** [comment]
Hi @ngzhian,

I was having doubts about understanding Depth wise convolution implementation. 

1.) Why there is a difference in the implementation of indirection-based im2col for dw conv( https://github.com/google/XNNPACK/blob/98d809fa866180ebd962997e24a86437a27948d6/src/indirection.c#L201) when compared to the normal conv(https://github.com/google/XNNPACK/blob/98d809fa866180ebd962997e24a86437a27948d6/src/indirection.c#L21), what is the difference between?

2.) I see that the main call for the Dw kernel is happening here: https://github.com/google/XNNPACK/blob/98d809fa866180ebd962997e24a86437a27948d6/src/operator-run.c#L662, my doubt is which parameter is controlling the execution bound(similar to output_size for normal igemm)?


Thanks!
