### ISSUE TITLE
Typo in XNNPACK/doc /dwconv.md

### ISSUE THREAD

**Issue by jazib-sudo** [google/XNNPACK#4922]
line 26.
" * " in the beginning of the line converted into bullet point because of github's markdown file syntax.

Current displaying:
 In each iteration of the main loop, the microkernel will read `channel_tile` biases, `channel_tile
* kernel_tile` inputs, `channel_tile * kernel_tile` weights, and, optionally, `channel_tile` of per-channel scales,
perform the convolution, then write `channel_tile` outputs.

Remove "line change" at the beginning of line 26. It should be:
In each iteration of the main loop, the microkernel will read `channel_tile` biases, `channel_tile * kernel_tile` inputs, 
`channel_tile * kernel_tile` weights, and, optionally, `channel_tile` of per-channel scales,
perform the convolution, then write `channel_tile` outputs.

**Comment by ngzhian** [comment]
Thanks for the report @jazib-sudo !
