### ISSUE TITLE
[question] Will xnnpack support low-precision OPs?

### ISSUE THREAD

**Issue by rednoah91** [google/XNNPACK#515]
Hi,

Will xnnpack support low-precision OPs?

Another question is: TF-Lite can delegate to xnnpack, so will xnnpack replace the Ops implemented in TF-lite for CPU?

Thanks

**Comment by Maratyszcza** [comment]
The focus of XNNPACK is on performant floating-point implementation of neural network operators. In addition to currently implemented FP32 inference, we are working on FP16 inference operators, but fixed-point inference is out of scope.

As was announced at the TensorFlow Dev Summit, TensorFlow Lite will switch to using XNNPACK for floating-point inference in 2.3 release.
