### ISSUE TITLE
building failed on Raspberry Pi 4

### ISSUE THREAD

**Issue by ThomAce** [google/XNNPACK#5535]
with the scripts/build-linux-armhf.sh, it ending up here:

[ 70%] Building C object CMakeFiles/microkernels-all.dir/src/bf16-gemm/gen/bf16-gemm-6x8c2-minmax-neonbf16-bfdot-lane-ld128.c.o
[ 70%] Building C object CMakeFiles/microkernels-all.dir/src/qd8-f32-qc4w-gemm/gen/qd8-f32-qc4w-gemm-1x8c4-minmax-neondot.c.o
[ 70%] Building C object CMakeFiles/microkernels-all.dir/src/qd8-f32-qc4w-gemm/gen/qd8-f32-qc4w-gemm-1x8c8-minmax-neondot-ld64.c.o
/tmp/ccycDMjK.s: Assembler messages:
/tmp/ccycDMjK.s:410: Error: selected processor does not support `vsdot.s8 q11,q13,d7[0]' in ARM mode
/tmp/ccycDMjK.s:422: Error: selected processor does not support `vsdot.s8 q10,q9,d7[0]' in ARM mode
/tmp/ccycDMjK.s:434: Error: selected processor does not support `vsdot.s8 q11,q12,d7[1]' in ARM mode
/tmp/ccycDMjK.s:446: Error: selected processor does not support `vsdot.s8 q10,q8,d7[1]' in ARM mode
/tmp/ccycDMjK.s:936: Error: selected processor does not support `vsdot.s8 q11,q9,d7[0]' in ARM mode
/tmp/ccycDMjK.s:948: Error: selected processor does not support `vsdot.s8 q10,q8,d7[0]' in ARM mode
gmake[2]: *** [CMakeFiles/microkernels-all.dir/build.make:46505: CMakeFiles/microkernels-all.dir/src/qd8-f32-qc4w-gemm/gen/qd8-f32-qc4w-gemm-1x8c4-minmax-neondot.c.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
/tmp/ccX7Cvc6.s: Assembler messages:
/tmp/ccX7Cvc6.s:580: Error: selected processor does not support `vsdot.s8 q15,q12,q10' in ARM mode
/tmp/ccX7Cvc6.s:592: Error: selected processor does not support `vsdot.s8 q2,q9,q10' in ARM mode
/tmp/ccX7Cvc6.s:604: Error: selected processor does not support `vsdot.s8 q13,q11,q10' in ARM mode
/tmp/ccX7Cvc6.s:616: Error: selected processor does not support `vsdot.s8 q3,q8,q10' in ARM mode
gmake[2]: *** [CMakeFiles/microkernels-all.dir/build.make:46518: CMakeFiles/microkernels-all.dir/src/qd8-f32-qc4w-gemm/gen/qd8-f32-qc4w-gemm-1x8c8-minmax-neondot-ld64.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:10463: CMakeFiles/microkernels-all.dir/all] Error 2
gmake: *** [Makefile:160: all] Error 2

**Comment by Maratyszcza** [comment]
You system has a buggy binutils version. Update binutils to top-of-tree, or use `-DXNNPACK_ENABLE_ARM_DOTPROD=OFF` as a work-around.
