### ISSUE TITLE
Regarding the issue with f32-gemm-bench.

### ISSUE THREAD

**Issue by chenkui164** [google/XNNPACK#5537]
When I ran f32-gemm-bench on the x86_64 platform, I found that the highest score was achieved by f32_gemm_3x16__fma3_broadcast. My question is, why isn't it f32_gemm_4x16__fma3_broadcast? In my impression, f32_gemm_3x16__fma3_broadcast should only use 11 YMM registers, while f32_gemm_4x16__fma3_broadcast uses 14 YMM registers. In theory, f32_gemm_4x16__fma3_broadcast should have a higher score, but the actual result is different, and I don't quite understand why.

**Comment by ngzhian** [comment]
Depends on microarchitecture too, we use different f32-gemm microkernels on different microarchitecture: https://github.com/google/XNNPACK/blob/master/src/configs/gemm-config.c#L746-L769

Also, the microkernels are written in C+intrinsics, so we don't control a lot of the instruction scheduling.

**Comment by chenkui164** [comment]
Thanks a lot.
