### ISSUE TITLE
GELU support in XNNPACK

### ISSUE THREAD

**Issue by phoebesv** [google/XNNPACK#5753]
We would like to contribute rvv GELU in XNNPACK.
Does the XNNPACK plan to support GELU (related APIs, scalar code and TFLite delegation, etc.) ?
This is required for bert models (e.g. bert_base and bert_large)

**Comment by bhbruce** [comment]
Hi @fbarchard @Maratyszcza 

Do you have any opinions about this Op?

**Comment by ngzhian** [comment]
@alankelly i think Marat wanted to support this but was not prioritized. see b/272379108

**Comment by alankelly** [comment]
GELU is not on our roadmap, however, please feel free to add the required operator & subgraph support & scalar microkernels.

XNNPACK has strict precision requirements, the maximum error of your implementation will have to be found via exhaustive testing.

**Comment by phoebesv** [comment]
Thank you for your response. We will consider and explore the addition of the required operator, subgraph support, and scalar microkernels for GELU.

**Comment by alankelly** [comment]
XNNPack now supports GELU: https://github.com/google/XNNPACK/commit/8b9fe2602ffc510a42f72d4d8920fff5c9c4447f
