### ISSUE TITLE
Concatenate and Split don't support input that has 0 size dimension

### ISSUE THREAD

**Issue by huningxin** [google/XNNPACK#5807]
(This was raised in WebNN issue [Allow 0 size dimensions](https://github.com/webmachinelearning/webnn/issues/391))

XNNPACK Concatenate ([xnn_define_concatenate2/3/4](https://github.com/google/XNNPACK/blob/master/include/xnnpack.h#L1181)) and Split ([xnn_define_even_split2/3/4](https://github.com/google/XNNPACK/blob/master/include/xnnpack.h#L1279)) operators would report invalid parameter error ([xnn_status_invalid_parameter](https://github.com/google/XNNPACK/blob/master/include/xnnpack.h#L104)) when the input has 0 size dimension.

For example, when concatenating three tensors in shape [1, 2], [0, 2] and [2, 2], XNNPACK reports xnn_status_invalid_parameter error. It looks like the [`create_unary_elementwise_nc()`](https://github.com/google/XNNPACK/blob/03d2a24b53f18103a2bb0f62e2c7123c5cea8890/src/operators/unary-elementwise-nc.c#L81) doesn't allow the `channels` to be 0.

While when adding ([xnn_define_add2](https://github.com/google/XNNPACK/blob/03d2a24b53f18103a2bb0f62e2c7123c5cea8890/include/xnnpack.h#L899C17-L899C32)) two tensors in shape [1, 2] and [0, 2], XNNPACK doesn't report any errors and just treat this is a no-op.

On the high-level, the open is: Does XNNPACK support 0 size dimension tensor? Or is this just a bug for Concatenate and Split?

/cc @fdwr

**Comment by alankelly** [comment]
Thanks for opening this issue. After testing a bit, it looks like XNNPack is unnecessarily rejecting unary elementwise ops with 0 dimensions. I will work on a fix

**Comment by alankelly** [comment]
https://github.com/google/XNNPACK/commit/330063967139bc9e0c6c6890cbb640e261ba5722 should fix this. Please  close if everything is ok

**Comment by huningxin** [comment]
Thanks for the fix! Closing this issue.

**Comment by fdwr** [comment]
@alankelly Great - thanks.
