### ISSUE TITLE
XNNPACK on LicheePi Console 4A

### ISSUE THREAD

**Issue by alexshendi** [google/XNNPACK#6074]
Hi,

I just acquired a LicheePi Console 4A. I would like to check if XNNPACK on RISC V 64 uses only the CPU or could be built to take advantage of the NPU or the GPU? Thanks in advance!

**Comment by fbarchard** [comment]
Hi, congrats on the LicheePi.  Its still early development, but if you have any build issues with XNNPack, please post issues or PR's.

Yes, XNNPack is CPU only... no NPU or GPU support.   Specifically we target RVV - RISC-V Vector and FP16 Vector instruction support.

LicheePi Console 4A uses TH1520 RISC-V CPU (4xC910@2GHz, RV64GCV)
where the 'V' indicated vector support.

**Comment by alexshendi** [comment]
Thank you for the clarification. Compilation was without problem, so no PRs :)
