### ISSUE TITLE
Is running TEST(CONVERT_NC_F16_QD8, unit_batch) failed because it does not support armv7a ?

### ISSUE THREAD

**Issue by JamesWang2007** [google/XNNPACK#6191]
Hello, currently the library compiled by armv7a has failed to run the following test functions in the test cases convert-nc-test and subgraph-fp16-test.
         TEST(CONVERT_NC_F16_QD8, unit_batch)
         TEST(CONVERT_NC_F16_QD8, small_batch)
         TEST(CONVERT_NC_F16_QD8, small_batch_with_input_stride)
         TEST(CONVERT_NC_F16_QD8, small_batch_with_output_stride)
         TEST(CONVERT_NC_F16_QD8, small_batch_with_input_and_output_stride)
         TEST(CONVERT_NC_F16_QD8, output_min) 
         TEST(CONVERT_NC_F16_QD8, output_max) 
         TEST(SUBGRAPH_FP16, fully_connected_qd8_f16_qc8w)

Log analysis is the process of converting a semi precision floating-point type f16 to a deep quantization type qd8, where the output value calculated by the executing function is not as expected, resulting in the failure of the test case.

1、Related source file path:
XNNPACK/src/amalgam/gen/neonfp16arith.c
XNNPACK/src/operator-run.c

2、Declaration of failed function:
void xnn_f16_rminmax_ukernel_neonfp16arith_u32-acc2（
                    size_t batch,
                    const void * input,
                    void * output,
                    const union xnn_f16_default_params parameters

3、Call logic for failed functions:
uint16_t minmax[2];
context->rminmax_ukernel(n, input, minmax, &context->params);

**Is the vpmax_f16 used to calculate both the maximum and minimum values in the following code a bug that caused my test case to ultimately fail ?**
![111](https://github.com/google/XNNPACK/assets/35726056/00e05d87-e8eb-43e0-ba9b-4226a6a06618)

**Comment by fbarchard** [comment]
Thanks for the detailed bug report.  The min value is computed wrong on armv7.  Fix coming
