### ISSUE TITLE
Add benchmarks for vbinary microkernels

### ISSUE THREAD

**Issue by fbarchard** [google/XNNPACK#6396]
F32 and F16 are missing vbinary benchmarks

There are vunary benchmarks which are generated from tests

And a few have 8 bit tests
qs8-vadd.cc:#include <xnnpack/vbinary.h>
qs8-vaddc.cc:#include <xnnpack/vbinary.h>
qs8-vmul.cc:#include <xnnpack/vbinary.h>
qs8-vmulc.cc:#include <xnnpack/vbinary.h>
qu8-vadd.cc:#include <xnnpack/vbinary.h>
qu8-vaddc.cc:#include <xnnpack/vbinary.h>
qu8-vmul.cc:#include <xnnpack/vbinary.h>
qu8-vmulc.cc:#include <xnnpack/vbinary.h>

**Comment by ejparkqc** [comment]
@fbarchard I will jump on this issue. I will add missing benchmarks for vbinary and qs8-vadd both.
