### ISSUE TITLE
Dynamic shape support follow-up

### ISSUE THREAD

**Issue by adonnini** [google/XNNPACK#6423]
@alankelly I am using XNNPACK with Executorch to lower my model to an Android device and run it for inference.
Running the lowered model for inference fails because of a lack of dynamic shape support in XNNPACK.
I saw that back in October dynamic shape support was being worked on (https://github.com/google/XNNPACK/issues/5656).
What is the current status?
By the way, I opened an issue on this in the Executorch repo (https://github.com/pytorch/executorch/issues/1350) and communicating with @mcr229 about it.
Thanks

**Comment by alankelly** [comment]
XNNPack now supports dynamic shapes and this is wired up to TFLite and tested and working. This seems like an ExecuTorch issue so please follow up with them.

**Comment by chenghuaWang** [comment]
@alankelly As TF documented https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/xnnpack/README.md#other-limitations, dose xnnpack still has heavy reinitialization overhead?  Additionally, could you provide some examples of how to utilize the dynamic shape feature? Thanks.

**Comment by alankelly** [comment]
XNNPack can efficiently handle models with dynamic tensors and there is no reinitialization overhead. I have updated the TF doc. 

The dynamic shape feature is used automatically. You simply call ResizeInputTensor followed by AllocateTensors to change the input shape.

**Comment by chenghuaWang** [comment]
@alankelly Thank you for your response. I am using the `xnnpack` API to implement the functionality. I think I should directly use `xnn_reshape_external_value` to reshape, right?  When running the same graph for the second time, use xnn_reshape_external_value to reshape the inputs and outputs, and then set up and invoke a runtime.
