### ISSUE TITLE
RVV fp16arith testing

### ISSUE THREAD

**Issue by oliIMG** [google/XNNPACK#6865]
Currently there is no testing done for the RISC-V kernels that are utilizing the zvfh extension. More over some of the kernels that are currently present are failing tests we enable this extension. From what I can see there is no unit testing for this currently.
Running main() from /jenkins/workspace/xnnpack_unit_tests/IMG-XNNPACK/build/linux/riscv64-clang-128/googletest-source/googletest/src/gtest_main.cc
[==========] Running 28 tests from 4 test suites.
[----------] Global test environment set-up.
[----------] 7 tests from F16_VCLAMP__RVVFP16ARITH_U1V
[ RUN      ] F16_VCLAMP__RVVFP16ARITH_U1V.batch_eq_1v
[       OK ] F16_VCLAMP__RVVFP16ARITH_U1V.batch_eq_1v (14 ms)
[ RUN      ] F16_VCLAMP__RVVFP16ARITH_U1V.batch_div_1v
[       OK ] F16_VCLAMP__RVVFP16ARITH_U1V.batch_div_1v (100 ms)
[ RUN      ] F16_VCLAMP__RVVFP16ARITH_U1V.batch_lt_1v
[       OK ] F16_VCLAMP__RVVFP16ARITH_U1V.batch_lt_1v (24 ms)
[ RUN      ] F16_VCLAMP__RVVFP16ARITH_U1V.batch_gt_1v
[       OK ] F16_VCLAMP__RVVFP16ARITH_U1V.batch_gt_1v (4 ms)
[ RUN      ] F16_VCLAMP__RVVFP16ARITH_U1V.inplace
[       OK ] F16_VCLAMP__RVVFP16ARITH_U1V.inplace (23 ms)
[ RUN      ] F16_VCLAMP__RVVFP16ARITH_U1V.qmin
/jenkins/workspace/xnnpack_unit_tests/IMG-XNNPACK/test/vunary-microkernel-tester.h:434: Failure
The difference between fp16_ieee_to_fp32_value(y[i]) and y_ref[i] is 15114, which exceeds tol(y_ref[i]), where
fp16_ieee_to_fp32_value(y[i]) evaluates to 15360,
y_ref[i] evaluates to 246, and
tol(y_ref[i]) evaluates to 0.12300000339746475.
at 0 / 1, x[0] = 246
Google Test trace:
/jenkins/workspace/xnnpack_unit_tests/IMG-XNNPACK/test/replicable_random_device.h:33: To replicate this failure, re-run the test with `--gunit_random_seed=10593`.
/jenkins/workspace/xnnpack_unit_tests/IMG-XNNPACK/test/vunary-microkernel-tester.h:434: Failure
The difference between fp16_ieee_to_fp32_value(y[i]) and y_ref[i] is 15114, which exceeds tol(y_ref[i]), where
fp16_ieee_to_fp32_value(y[i]) evaluates to 15360,
y_ref[i] evaluates to 246, and
tol(y_ref[i]) evaluates to 0.12300000339746475.
at 0 / 8, x[0] = 246
Google Test trace:
/jenkins/workspace/xnnpack_unit_tests/IMG-XNNPACK/test/replicable_random_device.h:33: To replicate this failure, re-run the test with `--gunit_random_seed=10593`.
/jenkins/workspace/xnnpack_unit_tests/IMG-XNNPACK/test/vunary-microkernel-tester.h:434: Failure
The difference between fp16_ieee_to_fp32_value(y[i]) and y_ref[i] is 15114, which exceeds tol(y_ref[i]), where
fp16_ieee_to_fp32_value(y[i]) evaluates to 15360,
y_ref[i] evaluates to 246, and
tol(y_ref[i]) evaluates to 0.12300000339746475.
at 0 / 15, x[0] = 246
Google Test trace:
/jenkins/workspace/xnnpack_unit_tests/IMG-XNNPACK/test/replicable_random_device.h:33: To replicate this failure, re-run the test with `--gunit_random_seed=10593`.
/jenkins/workspace/xnnpack_unit_tests/IMG-XNNPACK/test/vunary-microkernel-tester.h:434: Failure
The difference between fp16_ieee_to_fp32_value(y[i]) and y_ref[i] is 15114, which exceeds tol(y_ref[i]), where
fp16_ieee_to_fp32_value(y[i]) evaluates to 15360,
y_ref[i] evaluates to 246, and
tol(y_ref[i]) evaluates to 0.12300000339746475.
at 0 / 22, x[0] = 246
Is there any chance to add a unit test for this in the future? Thanks!

**Comment by fbarchard** [comment]
The issue is:
const _Float16 vmin = params->fp16arith.min;
casts a uint16 to Float16.

**Comment by fbarchard** [comment]
This PR should fix it
https://github.com/google/XNNPACK/pull/6926

Can you confirm?

**Comment by oliIMG** [comment]
Yes, the tests are now passing as expected. Thanks!
