### ISSUE TITLE
Plans for ARM SME support?

### ISSUE THREAD

**Issue by UsmanNadeem** [google/XNNPACK#7121]
I recently saw https://github.com/google/XNNPACK/pull/7061 which adds `sme` to `xnn_hardware_config`.

Are there any plans for adding SME support? If so, then which kernels/operations are being prioritized for this?

Thanks

**Comment by fbarchard** [comment]
SME is mainly interesting for its matrix multiply, which is GEMM and IGEMM for all datatypes.
Hardware doesnt really exist yet, except maybe Apple M4, so when macOS supports SME it may be feasible to explore.

**Comment by Lomasuno** [comment]
Para fijar un clip, manténlo presionado. Después de una hora, se borrarán todos los clips que no estén fijados.
