### ISSUE TITLE
Unable to Enable Debug Logging in XNNPACK Despite Setting `XNN_LOG_LEVEL=4` and `-DCMAKE_BUILD_TYPE=Debug`

### ISSUE THREAD

**Issue by wewe5215** [google/XNNPACK#7206]
Hi XNNPACK Developers,

I'm experiencing an issue where I'm unable to see debug messages from XNNPACK despite setting `XNN_LOG_LEVEL=4` during the build process. I've attempted this on both macOS (arm64) and Ubuntu(amd64) platforms, but the debug messages do not appear in either case.

**Problem Description:**

I am trying to enable debug logging in XNNPACK to understand which microkernels are being selected during the execution of my program. Despite setting `XNN_LOG_LEVEL=4` and rebuilding the library and my application multiple times, I do not see any debug messages from XNNPACK when running my application.

**Steps Taken to Resolve the Issue:**

1. **Built XNNPACK in Debug Mode:**
   - Used `-DCMAKE_BUILD_TYPE=Debug` during the CMake configuration.
   - Confirmed that the build configuration is set to `Debug`.
2. **Set `XNN_LOG_LEVEL=4` During Build:**
   - Modified the build script to include `-DXNN_LOG_LEVEL=4` in `CMAKE_C_FLAGS` and `CMAKE_CXX_FLAGS`.
   - Verified via verbose build output that `-DXNN_LOG_LEVEL=4` is being passed to the compiler.
3. **Ensured No Conflicting Definitions:**
   - Removed any custom definitions of `XNN_LOG_LEVEL` in my application code.

4. **Checked for Logging Symbols in the Library:**
   - Ran `nm libXNNPACK.a | grep xnn_log_debug` and found the following:

     ```
     0000000000000c98 t _xnn_log_debug_
     00000000000004e8 t _xnn_log_debug_
     ...
     ```

   - Noted that the symbols are local (`t`) and have underscores, which seems unusual.

5. **Used a Debugger:**
   - Attempted to set breakpoints at `xnn_log_debug`, but the debugger cannot detect the symbol.
   - Stepped through the code and confirmed that logging functions are not being called.

6. **Modified `CMakeLists.txt`:**
   - Added `add_definitions(-DXNN_LOG_LEVEL=4)` to force the log level.
   - Modified `TARGET_COMPILE_DEFINITIONS` to always set `XNN_LOG_LEVEL=4`.
   - Rebuilt the library and application, but still no debug messages appear.

7. **Checked Output Streams and Buffering:**
   - Ensured that output is not being redirected or suppressed.
   - Used `fflush(stdout)` and `fflush(stderr)` to flush output streams.

8. **Confirmed Correct Library Linking:**
   - Verified that my application is linking against the newly built XNNPACK library.
   - Used absolute paths in linker settings to avoid conflicts.

**Build Environment and Configuration:**

- **Platforms Tested:**
  - macOS Sequoia 15.0 (arm64, Apple M2)
  - Ubuntu 20.04 LTS (x86_64)

- **Compiler Versions:**
  - Clang/LLVM 15.0.0 on macOS

- **Build Script:**

  ```bash
  #!/bin/bash
  set -e

  mkdir -p build/local

  CMAKE_ARGS=()
  CMAKE_ARGS+=("-DCMAKE_BUILD_TYPE=Debug")
  CMAKE_ARGS+=("-DCMAKE_POSITION_INDEPENDENT_CODE=ON")
  CMAKE_ARGS+=("-DCMAKE_VERBOSE_MAKEFILE=ON")
  CMAKE_ARGS+=("-DCMAKE_C_FLAGS=-O0 -g -DXNN_LOG_LEVEL=4")
  CMAKE_ARGS+=("-DCMAKE_CXX_FLAGS=-O0 -g -DXNN_LOG_LEVEL=4")

  # If Ninja is installed, prefer it to Make
  if [ -x "$(command -v ninja)" ]
  then
    CMAKE_ARGS+=("-GNinja")
  fi

  CMAKE_ARGS+=("-DXNNPACK_LIBRARY_TYPE=static")
  CMAKE_ARGS+=("-DXNNPACK_BUILD_BENCHMARKS=ON")
  CMAKE_ARGS+=("-DXNNPACK_BUILD_TESTS=ON")

  cd build/local && cmake ../.. "${CMAKE_ARGS[@]}"

  # Cross-platform parallel build
  if [ "$(uname)" == "Darwin" ]
  then
    cmake --build . -- "-j$((2*$(sysctl -n hw.ncpu)))"
  else
    cmake --build . -- "-j$((2*$(nproc)))"
  fi
  ```

- **CMakeLists.txt Snippet:**

  ```cmake
  # Set `XNN_LOG_LEVEL` transitively for all targets that depend on `logging`.
  TARGET_COMPILE_DEFINITIONS(logging PUBLIC "XNN_LOG_LEVEL=4")
  ```

**Sample Code:**

```cpp
#include "xnnpack.h"
#include "xnnpack/log.h"

int main() {
  xnn_initialize(nullptr);
  xnn_log_debug("Test debug message from XNNPACK");
  return 0;
}
```

**Observations:**

- The `xnn_log_debug` symbols in `libXNNPACK.a` have leading and trailing underscores and are local (`t`), which may indicate that the symbols are not accessible outside the library.
- The logging functions may not be included in the compiled library due to conditional compilation or symbol visibility issues.
- Attempted compiling with `-fvisibility=default` and `-fno-inline` to prevent symbols from being hidden or inlined, but this did not resolve the issue.
- No debug messages appear when running the application, and inserting `printf` statements in `xnn_log_debug` does not produce any output.

**Questions and Request for Assistance:**

- **Is there an additional macro or build configuration I need to set to enable logging in XNNPACK?**
- **Are there any known issues with logging functionality in XNNPACK on macOS arm64 or Ubuntu?**
- **Is there a specific way to ensure that logging functions are included and accessible when building XNNPACK?**

Any guidance on how to properly enable debug logging in XNNPACK would be greatly appreciated. I'm happy to provide more details or try out suggestions to resolve this issue.

Thank you for your time and assistance.

Best regards

**Comment by gonnet** [comment]
Hi Chi-Wei,

Thanks for raising this issue!

In `src/xnnpack/log.h`, `xnn_log_debug` is declared as a macro that calls the actual function `xnn_log_debug_`, which in turn is a wrapper to `xnn_vlog_debug`. So you won't see any symbols for `xnn_log_debug`, but you should for `xnn_vlog_debug`.

Can you run your build with `cmake --build . -- -v` to print the compiler invocations, and see if `XNN_LOG_LEVEL` is being set, and if so, to what, for both `scr/xnnpack/log.c` and your sample binary?

Cheers, Pedro

**Comment by wewe5215** [comment]
**Hi Pedro,**

**Thank you for your prompt reply!**

I have tried the suggestions you offered and have gathered the following information:

1. **Output of `nm libXNNPACK.a | grep xnn_vlog_debug`:**

   The command shows no output:

   ```bash
   $ nm libXNNPACK.a | grep xnn_vlog_debug
   # No output
   ```

   This suggests that `xnn_vlog_debug` is not present in the library.

2. **Compiler Invocation for `src/log.c`:**

   Here is the compiler command when building `src/log.c`:

   ```bash
   /Library/Developer/CommandLineTools/usr/bin/cc -DPTHREADPOOL_NO_DEPRECATED_API=1 -DXNN_ENABLE_ARM_BF16=1 -DXNN_ENABLE_ARM_DOTPROD=1 -DXNN_ENABLE_ARM_FP16_SCALAR=1 -DXNN_ENABLE_ARM_FP16_VECTOR=1 -DXNN_ENABLE_ARM_I8MM=1 -DXNN_ENABLE_ASSEMBLY=1 -DXNN_ENABLE_AVX256SKX=1 -DXNN_ENABLE_AVX256VNNI=1 -DXNN_ENABLE_AVX256VNNIGFNI=1 -DXNN_ENABLE_AVX512AMX=1 -DXNN_ENABLE_AVX512FP16=1 -DXNN_ENABLE_AVX512VNNIGFNI=1 -DXNN_ENABLE_AVXVNNI=1 -DXNN_ENABLE_AVXVNNIINT8=0 -DXNN_ENABLE_CPUINFO=1 -DXNN_ENABLE_DWCONV_MULTIPASS=0 -DXNN_ENABLE_GEMM_M_SPECIALIZATION=1 -DXNN_ENABLE_HVX=1 -DXNN_ENABLE_KLEIDIAI=1 -DXNN_ENABLE_MEMOPT=1 -DXNN_ENABLE_RISCV_VECTOR=1 -DXNN_ENABLE_SPARSE=1 -DXNN_ENABLE_VSX=1 -DXNN_LOG_LEVEL=4 -I/Users/wewe5215/Desktop/XNNPACK/include -I/Users/wewe5215/Desktop/XNNPACK/src -I/Users/wewe5215/Desktop/XNNPACK/build/local/pthreadpool-source/include -I/Users/wewe5215/Desktop/XNNPACK/build/local/kleidiai-source/. -g -std=c99 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk -fPIC -MD -MT CMakeFiles/logging.dir/src/log.c.o -MF CMakeFiles/logging.dir/src/log.c.o.d -o CMakeFiles/logging.dir/src/log.c.o -c /Users/wewe5215/Desktop/XNNPACK/src/log.c
   ```

   **Observations:**

   - `-DXNN_LOG_LEVEL=4` is present.
   - There are no `XNN_NO_LOGGING` or `NDEBUG` flags present.

3. **Compiler Invocation for My Sample Binary:**

   Here's the compiler command when building my sample binary (`conv2d_bias_add_relu_5.cpp`):

   ```bash
   clang++ -fPIC -Wconversion -fno-strict-aliasing -fvisibility=hidden -O3 -std=c++17 -v -I/Users/wewe5215/Desktop/XNNPACK/include -I/Users/wewe5215/Desktop/XNNPACK/build/local/pthreadpool-source/include -L/Users/wewe5215/Desktop/XNNPACK/build/local/ /Users/wewe5215/Desktop/XNNPACK/build/local/*.a -L/Users/wewe5215/Desktop/XNNPACK/build/local/cpuinfo -L/Users/wewe5215/Desktop/XNNPACK/build/local/kleidiai -L/Users/wewe5215/Desktop/XNNPACK/build/local/pthreadpool -lxnnpack -lkleidiai -lpthreadpool -lcpuinfo -lpthread -g -DXNN_LOG_LEVEL=4 -o conv2d_bias_add_relu_5 conv2d_bias_add_relu_5.cpp
   ```

   **Observations:**

   - `-DXNN_LOG_LEVEL=4` is present.
   - The include paths point to the correct XNNPACK headers.
   - The linker flags include the correct libraries.

   - **Possible Issue:**
     It appears that `XNN_LOG_LEVEL` might not be correctly influencing the compilation of logging functions, even though it's set to `4`.

5. **Questions:**

   - Is there any other macro or condition that might prevent `xnn_vlog_debug` from being compiled into the library?
   - Could the presence of other `XNN_ENABLE_*` macros affect the inclusion of logging functions?
   - Do you have any suggestions on further steps I can take to ensure that logging functions are included?

**Thank you for your assistance!**

**Comment by gonnet** [comment]
Hi Chi-Wei,

Thank you for the detailed information! And sorry for the somewhat late reply, I was out most of the last two weeks.

I think the problem is in `CMakeLists.txt`, namely the lines

```
  TARGET_LINK_LIBRARIES(XNNPACK PRIVATE xnnpack-base allocator cache hardware-config indirection logging memory microkernel-utils microparams-init mutex normalization operators operator-run operator-utils packing microkernels-prod subgraph)
  TARGET_LINK_LIBRARIES(XNNPACK PUBLIC pthreadpool)
```

i.e. the `logging` library is linked to the `XNNPACK` as `PRIVATE`.

I think the solution would be to move `logging` to the line below, alongside `pthreadpool`. Does this work for you?

Cheers, Pedro

**Comment by wewe5215** [comment]
Hi Pedro,

Thank you for your help! I revised the `CMakeLists.txt` and set the `logging` library linked to `XNNPACK` as `PUBLIC`, and I found that your advice worked! However, I noticed that `_xnn_vlog_debug` doesn't appear.

Here’s the output from running `nm libXNNPACK.a | grep xnn_vlog`:
```
...
000000000000003c t _xnn_vlog
00000000000002ac T _xnn_vlog_error
0000000000000348 s _xnn_vlog_error.error_prefix
00000000000002e8 T _xnn_vlog_fatal
000000000000035a s _xnn_vlog_fatal.fatal_prefix
0000000000000000 T _xnn_vlog_info
0000000000000324 s _xnn_vlog_info.info_prefix
0000000000000270 T _xnn_vlog_warning
0000000000000334 s _xnn_vlog_warning.warning_prefix
0000000000000372 s l___func__.xnn_vlog
```

After checking `src/xnnpack/log.h`, I found that `XNN_LOG_DEBUG` is defined as `5`, but in `CMakeLists.txt`, the line `TARGET_COMPILE_DEFINITIONS(logging PUBLIC "XNN_LOG_LEVEL=$<$<CONFIG:Debug>:4>$<$<NOT:$<CONFIG:Debug>>:0>")` sets `DXNN_LOG_LEVEL` to 4. After revising it to `TARGET_COMPILE_DEFINITIONS(logging PUBLIC "XNN_LOG_LEVEL=$<$<CONFIG:Debug>:5>$<$<NOT:$<CONFIG:Debug>>:0>")`, the Debug Logging was successfully enabled!

Best regards,  
Chi-Wei

**Comment by gonnet** [comment]
Hi Chi-Wei,

Oh, good catch! Would you like to submit a PR for these changes?

Cheers, Pedro

**Comment by wewe5215** [comment]
Hi Pedro,

Thank you! I've submitted a pull request for the changes here: [https://github.com/google/XNNPACK/pull/7270](https://github.com/google/XNNPACK/pull/7270). Please let me know if any further adjustments are needed.

Best regards,  
Chi-Wei
