### ISSUE TITLE
Why remove the neondot and neoni8mm support in QU8? The performance drop a lot on Cortex-A55.

### ISSUE THREAD

**Issue by feng-nxp** [google/XNNPACK#7605]
We found that the performance drop a lot since commit 1d8b40267304890c193f9d027a3eb87e3a09e64b on Cortext-A55.
And due to this issue, the tensorflow-lite xnnpack deegate performance also drop a lot since version 2.17.0.
 
I want to know why do you remove the neondot and neoni8mm support in QU8?

The performance with "neondot and neoni8mm":
----------------------------------------------------------------------------------------------------------------------------------------------------
Running ./qu8-gemm-bench
Run on (2 X 1700 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x2)
  L1 Instruction 32 KiB (x2)
  L2 Unified 64 KiB (x2)
  L3 Unified 256 KiB (x1)
Load Average: 0.01, 0.01, 0.09
qu8_gemm_4x8c4__asm_aarch64_neondot_cortex_a55/mobilenet_v1/M:12544/N:32/K:27/real_time                        1.76 ms         1.74 ms          399s
qu8_gemm_4x8c4__asm_aarch64_neondot_cortex_a55/mobilenet_v1/M:12544/N:64/K:32/real_time                        3.05 ms         3.03 ms          229s
qu8_gemm_4x8c4__asm_aarch64_neondot_cortex_a55/mobilenet_v1/M:3136/N:128/K:64/real_time                        2.09 ms         2.06 ms          337s
qu8_gemm_4x8c4__asm_aarch64_neondot_cortex_a55/mobilenet_v1/M:3136/N:128/K:128/real_time                       3.36 ms         3.33 ms          208s
qu8_gemm_4x8c4__asm_aarch64_neondot_cortex_a55/mobilenet_v1/M:784/N:256/K:128/real_time                        1.69 ms         1.68 ms          415s

The performance without "neondot and neoni8mm"
----------------------------------------------------------------------------------------------------------------------------------------------------
Running ./qu8-gemm-bench
Run on (2 X 1700 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x2)
  L1 Instruction 32 KiB (x2)
  L2 Unified 64 KiB (x2)
  L3 Unified 256 KiB (x1)
Load Average: 0.01, 0.01, 0.09
qu8_gemm_4x16__asm_aarch64_neon_mlal_lane_cortex_a53/mobilenet_v1/M:12544/N:32/K:27/real_time                  2.71 ms         2.68 ms          259s
qu8_gemm_4x16__asm_aarch64_neon_mlal_lane_cortex_a53/mobilenet_v1/M:12544/N:64/K:32/real_time                  5.88 ms         5.83 ms          119s
qu8_gemm_4x16__asm_aarch64_neon_mlal_lane_cortex_a53/mobilenet_v1/M:3136/N:128/K:64/real_time                  5.28 ms         5.25 ms          132s
qu8_gemm_4x16__asm_aarch64_neon_mlal_lane_cortex_a53/mobilenet_v1/M:3136/N:128/K:128/real_time                 10.3 ms         10.3 ms           68s
qu8_gemm_4x16__asm_aarch64_neon_mlal_lane_cortex_a53/mobilenet_v1/M:784/N:256/K:128/real_time                  5.05 ms         5.02 ms          138s

**Comment by alankelly** [comment]
Hi, we removed this as there is a bug with Arm's unsigned dot product. This would randomly crash, affecting many apps. The only solution here is to re-export your model with signed quantization. This has been the default for a long time so your model must be quite old.

**Comment by feng-nxp** [comment]
thanks for your information
