### ISSUE TITLE
Raspberry Pi 4B configuraion for performace test data

### ISSUE THREAD

**Issue by hexins** [google/XNNPACK#814]
Hi
Could you tell me the detail configuration of Raspberry Pi 4(RPi 4 (BCM2711)) in the performance data table?
for example, the memory of the RPi 4 is 1G,2G,4G or 8G? the OS is Raspbian Buster 32 bit or 64 bit, and release date？ 
I ran the benchmark command but did not got the same performance result, 
and I'm not sure which result from the end2end-bench output you are checking.
I'm running it in a 64 bit Ubuntu build.
here is the result:

ubuntu@ubuntu:~$ sudo cpupower frequency-set --governor performance
Setting cpu: 0
Setting cpu: 1
Setting cpu: 2
Setting cpu: 3
ubuntu@ubuntu:/mnt/home/ubuntu/XNNPACK/build/local$ ./end2end-bench --benchmark_min_time=5
2020-07-09 13:45:46
Running ./end2end-bench
Run on (4 X 1500 MHz CPU s)
------------------------------------------------------------------------------------------
Benchmark                                   Time           CPU Iterations UserCounters...
------------------------------------------------------------------------------------------
FP32MobileNetV1/T:1/real_time          312008 us     311970 us         22 Freq=1.5G
FP32MobileNetV1/T:2/real_time          186397 us     186380 us         37 Freq=1.5G
FP32MobileNetV1/T:3/real_time          147883 us     147872 us         48 Freq=1.5G
FP32MobileNetV1/T:4/real_time          142362 us     142349 us         49 Freq=1.5G
FP32MobileNetV2/T:1/real_time          193028 us     193004 us         36 Freq=1.5G
FP32MobileNetV2/T:2/real_time          106852 us     106843 us         65 Freq=1.5G
FP32MobileNetV2/T:3/real_time           81655 us      81648 us         85 Freq=1.5G
FP32MobileNetV2/T:4/real_time           72311 us      72304 us         97 Freq=1.5G
FP32MobileNetV3Large/T:1/real_time     156868 us     156850 us         45 Freq=1.5G
FP32MobileNetV3Large/T:2/real_time      91508 us      91499 us         76 Freq=1.5G
FP32MobileNetV3Large/T:3/real_time      71158 us      71150 us         98 Freq=1.5G
FP32MobileNetV3Large/T:4/real_time      65070 us      65061 us        107 Freq=1.5G
FP32MobileNetV3Small/T:1/real_time      48827 us      48821 us        143 Freq=1.5G
FP32MobileNetV3Small/T:2/real_time      31378 us      31375 us        223 Freq=1.5G
FP32MobileNetV3Small/T:3/real_time      24950 us      24947 us        280 Freq=1.5G
FP32MobileNetV3Small/T:4/real_time      22732 us      22729 us        309 Freq=1.5G
failed to create operation #0
FP16MobileNetV1/T:1/real_time      ERROR OCCURRED: 'failed to create a model'
failed to create operation #0
FP16MobileNetV1/T:2/real_time      ERROR OCCURRED: 'failed to create a model'
failed to create operation #0
FP16MobileNetV1/T:3/real_time      ERROR OCCURRED: 'failed to create a model'
failed to create operation #0
FP16MobileNetV1/T:4/real_time      ERROR OCCURRED: 'failed to create a model'
failed to create operation #0
FP16MobileNetV2/T:1/real_time      ERROR OCCURRED: 'failed to create a model'
failed to create operation #0
FP16MobileNetV2/T:2/real_time      ERROR OCCURRED: 'failed to create a model'
failed to create operation #0
FP16MobileNetV2/T:3/real_time      ERROR OCCURRED: 'failed to create a model'
failed to create operation #0
FP16MobileNetV2/T:4/real_time      ERROR OCCURRED: 'failed to create a mode

**Comment by Maratyszcza** [comment]
This was benchmarked on Raspberry Pi 4 with 4 GB RAM and Raspbian buster 32-bit. You’d need a good heatsink or fan on the Raspberry Pi, because without it Raspberry Pi easily overheats in multi-threaded inference.
