### ISSUE TITLE
How to support the hard sigmoid function

### ISSUE THREAD

**Issue by hexins** [google/XNNPACK#901]
There is a hard sigmoid function in Mobilenet v3, how could we support this function in XNNPACK?

**Comment by Maratyszcza** [comment]
MobileNet v3 use hard swish rather than hard sigmoid. Hard swish is supported.

If you do need hard sigmoid, it can be implemented as a Multiply operator with the second input = `{ 0.5 }`, `output_min = -1` and `output_max = 1`.

**Comment by hexins** [comment]
it seems we should plus 1 after that?

**Comment by Maratyszcza** [comment]
Use an Add operator. If the previous operator is Convolution/Deconvolution/Fully-Connected, you may fuse this addition into bias.
