### ISSUE TITLE
Perform coordinate regression, this optimization will cause errors

### ISSUE THREAD

**Issue by vonchenplus** [google/XNNPACK#958]
Hi,

I build a coordinate regression network based on MobileNetV2.
When I used the xnnpack delegate, I found that the results of inference had a big error, and  found the error caused by the optimization here in xnnpack.
https://github.com/google/XNNPACK/blob/f124e88a7dcc24e108f8b1c85a4da857c34551b5/src/subgraph.c#L548

Through more detailed research, it is found that when InputSize is (384, 384), MobileNetV2 will perform a ZeroPadding2D operation with Pad Size of (0,1)(0,1), similar to this:
![image](https://user-images.githubusercontent.com/3349963/89751829-5d4e8300-db04-11ea-91ce-364339c7cd4c.png)

I think it should be caused by this unconventional operation.

Thanks.

**Comment by Maratyszcza** [comment]
Thank you for the detailed report. There was indeed a bug. Could you check if #959 fix the error for you?

**Comment by vonchenplus** [comment]
Hello Marat,
I tested this submission and it works fine for me.
Thanks.
