### ISSUE TITLE
Question about "ModifyGraphWithDelegate is disallowed"

### ISSUE THREAD

**Issue by honglh** [google/XNNPACK#994]
Hi

I have built XNN pack successfully for target device (RPI2) and can run the benchmark tests. However, when I built libtensorflow-lite.a (or .so)  with XNNPACK and run with the prebuilts models I run into  `ModifyGraphWithDelegate is disallowed` error 
```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
ERROR: ModifyGraphWithDelegate is disallowed when graph is immutable.
```

The inference still ran successfully with correct result, but I guess it didn't benefit from the XNNPACK speedup because of the error.

In my testing, I used these two models from google prebuilt:
```
ssd_mobilenet_v3_small_coco_2020_01_14.tflite 
coco_ssd_mobilenet_v1_1.0_quant_2018_06_29.tflite
```

Is this `ModifyGraphWithDelegate is disallowed` expected when the model I used didn't comply to certain requirements?  Can you give some pointers how to get around this issue?  

You can also find more details of my setup at [this tensorflow issue I created](https://github.com/tensorflow/tensorflow/issues/42757). 

Thanks!

**Comment by Maratyszcza** [comment]
This is the question for tensorflow/tensorflow repo

**Comment by dhirajnitk** [comment]
I am getting same errors on native windows/linux.  Is there any solution. I am using the latest tensorflow from master branch
```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
ERROR: ModifyGraphWithDelegate is disallowed when graph is immutable.
ERROR: Ignoring failed application of the default TensorFlow Lite delegate indexed at 0.
```
